import type {Aircraft,TrailPoint} from '../types.ts';
import {AIRPORTS} from './airportCatalog.ts';
import {distanceNm} from './experience.ts';
import {movement} from './exploration.ts';
export function recentFlights(rows:Aircraft[],now:number){return rows.filter(a=>a.targetKind==='aircraft'&&Number.isFinite(a.lat)&&Number.isFinite(a.lon)&&a.observedAt!==null&&Number.isFinite(a.observedAt)&&now-a.observedAt<=30000&&now-a.observedAt>=-5000);}
export function discoverFlights(rows:Aircraft[],now:number,center:{lat:number;lon:number}){return recentFlights(rows,now).map(a=>({a,distance:distanceNm(center.lat,center.lon,a.lat!,a.lon!)})).sort((a,b)=>a.distance-b.distance);}
export function busyObservedAirports(rows:Aircraft[],now:number){const fresh=recentFlights(rows,now);return Object.entries(AIRPORTS).map(([id,airport])=>({id,airport,count:fresh.filter(a=>Math.abs(a.lat!-airport.lat)<.35&&distanceNm(airport.lat,airport.lon,a.lat!,a.lon!)<=20).length})).filter(a=>a.count>0).sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id)).slice(0,8);}
export type BoardFilter='all'|'approaching'|'departing'|'ground';
export function trafficBoard(rows:Aircraft[],histories:Map<string,TrailPoint[]>,airport:string,now:number){const home=AIRPORTS[airport];if(!home)return [];return rows.filter(a=>a.targetKind==='aircraft'&&Number.isFinite(a.lat)&&Number.isFinite(a.lon)).flatMap(a=>{const distance=distanceNm(home.lat,home.lon,a.lat!,a.lon!);if(!Number.isFinite(distance)||distance>20)return [];const inference=movement(a,histories.get(a.hex)??[],airport,now),fresh=a.observedAt!==null&&now-a.observedAt<=30000&&now-a.observedAt>=-5000;const category=!fresh?'other':a.ground&&distance<=5?'ground':inference?.direction==='Approaching'?'approaching':inference?.direction==='Moving away'?'departing':'other';return [{a,distance,category,label:category==='ground'?'Reported ground':category==='approaching'?'Approaching · inferred':category==='departing'?'Moving away · inferred':fresh?'Movement unclassified':'Stale observation'}];}).sort((a,b)=>a.distance-b.distance);}
export interface Favorites {airports:string[];airlines:string[];aircraft:{hex:string;label:string}[];}
export function sanitizeFavorites(value:unknown):Favorites{const v=(value&&typeof value==='object'?value:{}) as Partial<Favorites>;return {airports:[...new Set((Array.isArray(v.airports)?v.airports:[]).filter(id=>typeof id==='string'&&Object.hasOwn(AIRPORTS,id)))].slice(0,50),airlines:[...new Set((Array.isArray(v.airlines)?v.airlines:[]).filter(id=>typeof id==='string'&&/^[A-Z]{3}$/.test(id)))].slice(0,50),aircraft:[...new Map((Array.isArray(v.aircraft)?v.aircraft:[]).filter(a=>a&&typeof a.hex==='string'&&/^[a-f\d]{6}$/i.test(a.hex)&&typeof a.label==='string').map(a=>[a.hex.toLowerCase(),{hex:a.hex.toLowerCase(),label:a.label.slice(0,80)}])).values()].slice(0,50)};}
