export const flightPreferenceKey='skyward.flight-view.v1';
export const flightDefaults={view:'side',side:'left',savedView:'side',savedSide:'left',savedDistance:1.15,distance:1.15,compact:false,focus:false,sheet:42,cabinSide:'right',cabinSeat:-.06,cabinLook:0,shade:0,mapZoom:8,labelDensity:'normal',highlights:false};
export function sanitizeFlightPreferences(value:unknown){
 const v=value&&typeof value==='object'?value as Record<string,unknown>:{};
 const bounded=(key:string,min:number,max:number,fallback:number)=>typeof v[key]==='number'&&Number.isFinite(v[key])?Math.max(min,Math.min(max,v[key] as number)):fallback;
 return {cabinSide:v.cabinSide==='left'?'left':'right',cabinSeat:bounded('cabinSeat',-.28,.2,-.06),cabinLook:bounded('cabinLook',-35,35,0),shade:bounded('shade',0,100,0),mapZoom:bounded('mapZoom',1,64,8),labelDensity:v.labelDensity==='sparse'?'sparse':v.labelDensity==='rich'?'rich':'normal',highlights:v.highlights===true,savedView:typeof v.savedView==='string'&&['side','wing','tail','chase','bird','front','cabin','orbit'].includes(v.savedView)?v.savedView:'side',savedSide:v.savedSide==='right'?'right':'left',savedDistance:typeof v.savedDistance==='number'&&Number.isFinite(v.savedDistance)?Math.max(.8,Math.min(2.4,v.savedDistance)):1.15,side:v.side==='right'?'right':'left',view:typeof v.view==='string'&&['chase','side','orbit','area','front','pilot','cockpit','cabin','bird','wing','tail','director'].includes(v.view)?(v.view==='pilot'?'front':v.view):'side',distance:typeof v.distance==='number'&&Number.isFinite(v.distance)?Math.max(.8,Math.min(2.4,v.distance)):1.15,compact:v.compact===true,focus:v.focus===true,sheet:typeof v.sheet==='number'&&Number.isFinite(v.sheet)?Math.max(24,Math.min(72,v.sheet)):42};
}
export function readFlightPreferences(){try{return sanitizeFlightPreferences(JSON.parse(localStorage.getItem(flightPreferenceKey)??'null'));}catch{return {...flightDefaults};}}
export function saveFlightPreferences(patch:Partial<typeof flightDefaults>){try{localStorage.setItem(flightPreferenceKey,JSON.stringify(sanitizeFlightPreferences({...readFlightPreferences(),...patch})));window.dispatchEvent(new Event('skyward-view-preferences'));return true;}catch{return false;}}
