import {validAirport} from './airportCatalog.ts';
export const backupKeys=['skyward.last-flight.v1','skyward.favorites.v1','skyward.collections.v1','skyward.camera-bookmarks.v1','skyward.map.v1','skyward.watches.v1','skyward.route-unit','skyward.flight-view.v1'] as const;
export interface LocalBackup{format:'skyward-local-backup';version:1;createdAt:string;values:Record<string,string>;}
const text=(v:unknown,max=100):v is string=>typeof v==='string'&&v.length<=max;
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const array=(v:unknown,max:number,check:(v:any)=>boolean)=>Array.isArray(v)&&v.length<=max&&v.every(check);
const hex=(v:unknown)=>typeof v==='string'&&/^[a-f\d]{6}$/i.test(v);
export function validBackupValue(key:string,raw:string):boolean{
 if(key==='skyward.route-unit')return ['nm','km','mi'].includes(raw);
 let v:any;try{v=JSON.parse(raw);}catch{return false;}
 if(key==='skyward.last-flight.v1')return object(v)&&hex(v.hex)&&text(v.label,80);
 if(key==='skyward.favorites.v1')return object(v)&&array(v.airports,50,(a)=>typeof a==='string'&&validAirport(a))&&array(v.airlines,50,a=>typeof a==='string'&&/^[A-Z]{3}$/.test(a))&&array(v.aircraft,50,a=>object(a)&&hex(a.hex)&&text(a.label,80));
 if(key==='skyward.collections.v1')return array(v,20,a=>object(a)&&text(a.id,60)&&text(a.name,60)&&array(a.airports,50,id=>typeof id==='string'&&validAirport(id)));
 if(key==='skyward.watches.v1')return array(v,30,a=>object(a)&&hex(a.hex)&&['callsign','registration','aircraftType'].every(k=>text(a[k])));
 if(key==='skyward.camera-bookmarks.v1')return array(v,20,a=>object(a)&&text(a.id)&&text(a.name,60)&&['3D','2D'].includes(String(a.mode))&&object(a.pose)&&['lon','lat','height','heading','pitch','roll'].every(k=>Number.isFinite(a.pose[k]))&&Math.abs(a.pose.lon)<=180&&Math.abs(a.pose.lat)<=90&&a.pose.height>0&&a.pose.height<=100000000&&object(a.layers)&&['atlas','satellite'].includes(String(a.layers.basemap))&&['labels','structures','grid','terrain'].every(k=>typeof a.layers[k]==='boolean'));
 if(key==='skyward.flight-view.v1')return object(v)&&['chase','side','orbit','area','pilot','front','cockpit','cabin','bird'].includes(v.view)&&Number.isFinite(v.distance)&&v.distance>=.8&&v.distance<=2.4&&Number.isFinite(v.sheet)&&v.sheet>=24&&v.sheet<=72&&typeof v.compact==='boolean'&&typeof v.focus==='boolean';
 if(key==='skyward.map.v1'){const enums:Record<string,string[]>={lighting:['daylight','natural'],quality:['low','balanced','high'],basemap:['atlas','satellite']};const booleans=['offlineMaps','autoQuality','shadows','declutter','structures','labels','grid','terrain','reducedMotion','largeLabels','highContrast'];return object(v)&&Object.entries(v).every(([k,x])=>enums[k]?typeof x==='string'&&enums[k].includes(x):booleans.includes(k)&&typeof x==='boolean');}
 return false;
}
export function parseBackup(raw:string):LocalBackup{if(raw.length>1048576)throw Error('Backup exceeds 1 MB.');let value:any;try{value=JSON.parse(raw);}catch{throw Error('Invalid JSON backup.');}if(!object(value)||value.format!=='skyward-local-backup'||value.version!==1||!text(value.createdAt)||!object(value.values)||!Object.keys(value.values).length)throw Error('Not a supported Skyward backup.');for(const [k,v] of Object.entries(value.values))if(!backupKeys.includes(k as typeof backupKeys[number])||typeof v!=='string'||!validBackupValue(k,v))throw Error('Unsupported or invalid backup category: '+k);return value as unknown as LocalBackup;}
export function makeBackup(storage:Pick<Storage,'getItem'>):LocalBackup{const values:Record<string,string>={};for(const k of backupKeys){const v=storage.getItem(k);if(v!==null){if(!validBackupValue(k,v))throw Error('Stored category is invalid: '+k);values[k]=v;}}return {format:'skyward-local-backup',version:1,createdAt:new Date().toISOString(),values};}
export function restoreBackup(input:LocalBackup,storage:Pick<Storage,'getItem'|'setItem'|'removeItem'>){const b=parseBackup(JSON.stringify(input)),before=new Map(Object.keys(b.values).map(k=>[k,storage.getItem(k)]));try{for(const [k,v] of Object.entries(b.values))storage.setItem(k,v);}catch{let failed=false;for(const [k,v] of before)try{if(v===null)storage.removeItem(k);else storage.setItem(k,v);}catch{failed=true;}throw Error(failed?'Storage failed and rollback was incomplete. Keep your exported backup.':'Storage unavailable or full; previous settings restored.');}}
