import {useCallback,useEffect,useState} from 'react';
function configure(worker:ServiceWorker,enabled:boolean,clear=false){return new Promise<void>((resolve,reject)=>{const channel=new MessageChannel(),timeout=setTimeout(()=>{channel.port1.close();reject(new Error('Cache worker timeout'));},8000);channel.port1.onmessage=()=>{clearTimeout(timeout);channel.port1.close();resolve();};worker.postMessage({kind:'SET_ENABLED',enabled,clear},[channel.port2]);});}
export function useOfflineMaps(enabled:boolean){
 const [online,setOnline]=useState(navigator.onLine),[status,setStatus]=useState('Preparing local map cache…'),[stats,setStats]=useState({entries:0,bytes:0});
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener('online',update);addEventListener('offline',update);return()=>{removeEventListener('online',update);removeEventListener('offline',update);};},[]);
 const refresh=useCallback(async()=>{try{const registration=await navigator.serviceWorker?.getRegistration('/');const worker=registration?.active;if(!worker)return;const channel=new MessageChannel(),timeout=setTimeout(()=>channel.port1.close(),5000);channel.port1.onmessage=e=>{clearTimeout(timeout);setStats(e.data);channel.port1.close();};worker.postMessage({kind:'STATS'},[channel.port2]);}catch{setStatus('Map cache unavailable.');}},[]);
 useEffect(()=>{let alive=true;if(!('serviceWorker' in navigator)||!isSecureContext){setStatus('Offline storage requires HTTPS or localhost and a service-worker-capable browser.');return;}
  void (async()=>{try{const legacy=await navigator.serviceWorker.getRegistration('/watch/');if(legacy?.scope===location.origin+'/watch/'&&legacy.active?.scriptURL.endsWith('/watch/offline-worker.js'))await legacy.unregister();if(!enabled){await navigator.serviceWorker.register('/offline-worker.js',{scope:'/'});const r=await navigator.serviceWorker.ready;if(alive&&r?.active?.scriptURL.endsWith('/offline-worker.js'))await configure(r.active,false);if(alive)setStatus('Map caching disabled.');return;}
   await navigator.serviceWorker.register('/offline-worker.js',{scope:'/'});const r=await navigator.serviceWorker.ready;if(!alive||!r.active)return;await configure(r.active,true);if(!alive)return;setStatus('Local map assets are retained as you explore. Live traffic is never cached.');r.active.postMessage({kind:'WARM',urls:[location.origin+'/',...performance.getEntriesByType('resource').map(e=>e.name)]});void refresh();
  }catch{if(alive)setStatus('Map cache unavailable. Normal online viewing still works.');}})();return()=>{alive=false;};
 },[enabled,refresh]);
 const clear=useCallback(async()=>{try{const r=await navigator.serviceWorker?.getRegistration('/');if(r?.active?.scriptURL.endsWith('/offline-worker.js'))await configure(r.active,false,true);else if('caches' in window)for(const name of await caches.keys())if(name.startsWith('skyward-map-'))await caches.delete(name);setStats({entries:0,bytes:0});setStatus('Cached map assets cleared.');}catch{setStatus('Cache could not be cleared. Try again when this tab is active.');}},[]);
 return {online,status,stats,refresh,clear};
}
