import {parseRecording,SESSION_LIMITS,type Recording} from './sessionRecording';
export interface SavedSession {id:string;name:string;bytes:number;createdAt:number;recording:Recording;}
const LIMIT=100*1024*1024;
async function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('skyward-sessions',1);r.onupgradeneeded=()=>r.result.createObjectStore('sessions',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Close other Skyward tabs to update session storage.'));});}
async function transact<T>(mode:IDBTransactionMode,run:(store:IDBObjectStore,done:(value:T)=>void,fail:(reason:Error)=>void)=>void):Promise<T>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('sessions',mode);let value:T;let failure:Error|undefined;tx.oncomplete=()=>{db.close();resolve(value);};tx.onabort=()=>{db.close();reject(failure??tx.error??Error('Session storage could not be updated.'));};tx.onerror=()=>{};try{run(tx.objectStore('sessions'),v=>{value=v;},reason=>{failure=reason;tx.abort();});}catch(e){tx.abort();db.close();reject(e);}});}
export async function listSessions(){return transact<SavedSession[]>('readonly',(s,done)=>{const r=s.getAll();r.onsuccess=()=>done(r.result.sort((a:SavedSession,b:SavedSession)=>b.createdAt-a.createdAt));});}
export async function saveSession(raw:Recording){const recording=parseRecording(raw),bytes=new Blob([JSON.stringify(recording)]).size;if(bytes>SESSION_LIMITS.bytes)throw Error('Session exceeds 20 MB.');const entry:SavedSession={id:crypto.randomUUID(),name:recording.name,bytes,createdAt:Date.now(),recording};return transact<string>('readwrite',(s,done,fail)=>{const r=s.getAll();r.onsuccess=()=>{if(r.result.length>=20||r.result.reduce((n:number,e:SavedSession)=>n+e.bytes,0)+bytes>LIMIT){fail(Error('Library limit reached (20 sessions / 100 MB). Export or delete a session before saving another.'));return;}s.put(entry);done(entry.id);};});}
export async function deleteSession(id:string){return transact<void>('readwrite',(s,done)=>{s.delete(id);done();});}
export async function renameSession(id:string,name:string){name=name.trim().slice(0,80);if(!name)throw Error('Enter a session name.');return transact<void>('readwrite',(s,done)=>{const r=s.get(id);r.onsuccess=()=>{const row=r.result as SavedSession|undefined;if(!row){s.transaction.abort();return;}row.name=name;row.recording={...row.recording,name};row.bytes=new Blob([JSON.stringify(row.recording)]).size;s.put(row);done();};});}
