import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {validateCatalog,publishedCatalog,resolveAirframe,canonicalId,normalizedFollows,observedStatus,mergeAirframes,validateCatalogTransition} from '../src/lib/airframeCatalog.ts';
import source from '../data/airframe-catalog.json' with {type:'json'};
import {validateLibrary,createAccountLibrary} from './account-library.mjs';
import {airframePage,airframeDocument,airframePaths} from './airframe-pages.mjs';
const e={sourceUrl:'https://example.org/registry',sourceName:'Registry fixture',verifiedAt:'2026-09-30',confidence:'HIGH'};
const identity=(value,validFrom=null,validTo=null)=>({...e,value,validFrom,validTo});
function fixture(){return {version:1,aircraft:[{id:'frame-one',manufacturer:'Example',model:'Jet',category:'Test',serialNumber:'123',sources:[e],registrations:[identity('N123AB','2020-01-01','2024-01-01'),identity('N456CD','2024-01-01')],icaoIdentities:[identity('aaaaaa','2020-01-01','2024-01-01'),identity('bbbbbb','2024-01-01')]}],entities:[{id:'team-one',slug:'team-one',displayName:'Example team',description:'Fixture',entityType:'SPORTS_TEAM'}],associations:[{...e,id:'association-one',entityId:'team-one',aircraftId:'frame-one',associationType:'TEAM_AIRCRAFT',validFrom:null,validTo:null,reviewed:true}]};}
test('catalog validates starter evidence and excludes unpublished material',()=>{validateCatalog(source);const c=fixture();c.associations[0].notes='Internal';assert.equal(publishedCatalog(c).associations[0].notes,undefined);c.associations[0].confidence='LOW';assert.equal(publishedCatalog(c).associations.length,0);c.associations[0].confidence='HIGH';c.associations[0].reviewed=false;assert.equal(publishedCatalog(c).associations.length,0);c.associations[0].reviewed=true;c.associations[0].archived=true;assert.equal(publishedCatalog(c).associations.length,0);c.associations[0].archived=false;c.entities[0].entityType='PERSON';assert.equal(publishedCatalog(c).associations.length,0);});
test('missing sources, unsafe links, invalid dates and oversized catalogs fail',()=>{const c=fixture();delete c.associations[0].sourceUrl;assert.throws(()=>validateCatalog(c));c.associations[0].sourceUrl='javascript:alert(1)';assert.throws(()=>validateCatalog(c));c.associations[0].sourceUrl=e.sourceUrl;c.aircraft[0].registrations[0].validFrom='2024-02-30';assert.throws(()=>validateCatalog(c));assert.throws(()=>validateCatalog({...fixture(),padding:'x'.repeat(1024*1024)}));});
test('serial matches survive new registration and ICAO; serial needs manufacturer scope',()=>{const c=fixture();for(const extra of [{registration:'N999AA'},{icaoHex:'cccccc'}])assert.equal(resolveAirframe(c,{manufacturer:'Example',serialNumber:'123',...extra}).aircraftId,'frame-one');assert.equal(resolveAirframe(c,{serialNumber:'123'}).aircraftId,null);c.aircraft.push({...c.aircraft[0],id:'frame-two',manufacturer:'Other'});assert.equal(resolveAirframe(c,{manufacturer:'Example',serialNumber:'123'}).aircraftId,'frame-one');});
test('different MSN and identifier conflicts never merge automatically',()=>{const c=fixture();assert.equal(resolveAirframe(c,{manufacturer:'Example',serialNumber:'999',registration:'N456CD'}).aircraftId,null);assert.equal(resolveAirframe(c,{registration:'N456CD'}).aircraftId,null);c.aircraft.push({...c.aircraft[0],id:'frame-two',serialNumber:'999'});assert.equal(resolveAirframe(c,{manufacturer:'Example',serialNumber:'123',registration:'N456CD'}).aircraftId,null);assert.throws(()=>mergeAirframes(c,'frame-one','frame-two'));});
test('registration and hex reuse resolve by time; ambiguity stays unresolved',()=>{const c=fixture();assert.equal(resolveAirframe(c,{registration:'N123AB',icaoHex:'aaaaaa',at:'2022-01-01'}).aircraftId,'frame-one');assert.equal(resolveAirframe(c,{registration:'N123AB',icaoHex:'aaaaaa',at:'2025-01-01'}).aircraftId,null);c.aircraft.push({...c.aircraft[0],id:'frame-two'});assert.equal(resolveAirframe(c,{registration:'N456CD',icaoHex:'bbbbbb',at:'2025-01-01'}).aircraftId,null);});
test('merge redirects preserve follows and reject cycles',()=>{const c=fixture();c.aircraft.push({...structuredClone(c.aircraft[0]),id:'frame-two'});const next=mergeAirframes(c,'frame-one','frame-two');assert.equal(canonicalId(next,'frame-one'),'frame-two');assert.deepEqual(normalizedFollows(next,['frame-one','frame-two']),['frame-two']);assert.deepEqual(normalizedFollows(c,['frame-one','frame-one']),['frame-one']);assert.throws(()=>normalizedFollows(c,Array(51).fill('frame-one')));next.aircraft[1].mergedInto='frame-one';assert.throws(()=>validateCatalog(next));});
test('follows reference airframe, unaffected by changed registration or hex',()=>{const c=fixture();const before=normalizedFollows(c,['frame-one']);c.aircraft[0].registrations.push(identity('NNEW1'));c.aircraft[0].icaoIdentities.push(identity('cccccc'));assert.deepEqual(normalizedFollows(c,before),before);assert.deepEqual(normalizedFollows(c,[]),[]);});
test('status keeps stale/unknown separate and never treats simulation as telemetry',()=>{const now=1000000;assert.equal(observedStatus(null,now),'Unknown');assert.equal(observedStatus({observedAt:null},now),'Unknown');assert.equal(observedStatus({observedAt:now,ground:false},now),'Airborne');assert.equal(observedStatus({observedAt:now,ground:true},now),'Ground');assert.match(observedStatus({observedAt:now-150000,ground:true},now),/stale/);assert.equal(observedStatus({observedAt:now,simulation:{}},now),'Unknown');assert.equal(observedStatus({observedAt:now+60000},now),'Unknown');});
test('account follow storage is premium, bounded, revision checked, isolated and strips extras',async()=>{const db=new DatabaseSync(':memory:');let entitled=false;const library=createAccountLibrary(db,{now:()=>10,entitlement:async()=>entitled});const call=async(user,method,b={})=>{let value;await library('/api/account/library',method,{id:user},new URL('https://site/api/account/library?kind=aircraftfollows'),b,(_status,data)=>value=data);return value;};const value={ids:['nasa-sca-905','nasa-sca-905'],notifyArrival:true},b={kind:'aircraftfollows',key:'airframes',value,revision:0};await assert.rejects(call('one','POST',b),/Premium/);entitled=true;await call('one','POST',b);assert.deepEqual(validateLibrary('aircraftfollows',value),{ids:['nasa-sca-905']});await assert.rejects(call('one','POST',b),/changed|revision|updated/i);assert.equal((await call('two','GET')).items.length,0);assert.equal((await call('one','GET')).items.length,1);await call('one','POST',{...b,revision:1,value:{ids:[]}});assert.deepEqual((await call('one','GET')).items[0].value.ids,[]);db.close();});
test('static routes distinguish profiles, private following and missing IDs',()=>{assert.equal(airframePage('/aircraft/missing/'),null);assert.equal(airframePage('/following/').privatePage,true);assert.equal(airframePage('/admin/notable-aircraft/').privatePage,true);assert.ok(airframePaths().includes('/aircraft/nasa-sca-905/'));const html=airframeDocument(airframePage('/aircraft/nasa-sca-905/'),'<html><head><title>Old</title><meta name="description" content="old"><link rel="canonical" href="https://skyvvard.com/"></head></html>');assert.match(html,/N905NA/);assert.match(html,/https:\/\/skyvvard.com\/aircraft\/nasa-sca-905\//);});

test('publication cannot drop IDs, overwrite serials, or bypass verified merge rules',()=>{const before=fixture(),next=structuredClone(before);next.aircraft=[];assert.throws(()=>validateCatalogTransition(before,next));next.aircraft=structuredClone(before.aircraft);next.aircraft[0].serialNumber='999';assert.throws(()=>validateCatalogTransition(before,next));next.aircraft=structuredClone(before.aircraft);next.aircraft.push({...structuredClone(before.aircraft[0]),id:'frame-two',serialNumber:'999'});next.aircraft[0].mergedInto='frame-two';assert.throws(()=>validateCatalogTransition(before,next));});
test('unverified airframes and their associations never enter public artifact',()=>{const c=fixture();c.aircraft[0].sources[0]={...e,confidence:'LOW'};const p=publishedCatalog(c);assert.equal(p.aircraft.length,0);assert.equal(p.associations.length,0);});

test('published merge aliases skip withdrawn intermediate records',()=>{const c=fixture();c.aircraft.push({...structuredClone(c.aircraft[0]),id:'frame-two',mergedInto:'frame-three',sources:[{...e,confidence:'LOW'}]},{...structuredClone(c.aircraft[0]),id:'frame-three'});c.aircraft[0].mergedInto='frame-two';const published=publishedCatalog(validateCatalog(c));assert.equal(published.aircraft.some(a=>a.id==='frame-two'),false);assert.equal(canonicalId(published,'frame-one'),'frame-three');assert.deepEqual(normalizedFollows(published,['frame-one']),['frame-three']);});
