import {discoveryCategories,discoveryCategory} from '../src/lib/discoveryCategories.ts';
import {directoryMatches,entityAircraftGroups} from '../src/lib/notableDirectory.ts';
import source from '../data/airframe-catalog.json' with {type:'json'};
import {publishedCatalog,canonicalId} from '../src/lib/airframeCatalog.ts';
const catalog=publishedCatalog(source);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function airframePage(path){
 const p=path.split('/').filter(Boolean),collection=discoveryCategory(path);let content='',socialDescription='',title,description='Explore verified aircraft identities and follow an airframe across registration changes.',privatePage=false;
 if(p.length===1&&['aircraft','notable-aircraft','following'].includes(p[0])){title={aircraft:'Aircraft directory','notable-aircraft':'Notable aircraft',following:'Following aircraft'}[p[0]];privatePage=p[0]==='following';}
 else if(collection){title=collection.title;description=collection.description;content='<ul>'+directoryMatches(catalog,'',collection.category).map(e=>`<li><a href="/notable/${escape(e.slug)}/">${escape(e.displayName)}</a> — ${escape(e.description)}</li>`).join('')+'</ul>';}
 else if(p.length===2&&p[0]==='admin'&&p[1]==='notable-aircraft'){title='Aircraft review workbench';privatePage=true;}
 else if(p.length===2&&p[0]==='aircraft'){const a=catalog.aircraft.find(a=>a.id===p[1]);if(!a)return null;if(a.mergedInto)return {redirect:`/aircraft/${canonicalId(catalog,a.id)}/`};socialDescription=catalog.associations.filter(v=>canonicalId(catalog,v.aircraftId)===a.id).map(v=>catalog.entities.find(e=>e.id===v.entityId)?.displayName).filter(Boolean).join(' · ')+'. Explore the aircraft, its story and available 3D flight views.';content=`<h2>Aircraft identity</h2><p>${escape(a.manufacturer)} ${escape(a.model)} · ${escape(a.category)}</p><h2>Sources</h2><ul>${a.sources.map(v=>`<li><a href="${escape(v.sourceUrl)}">${escape(v.sourceName)}</a> · ${escape(v.verifiedAt)}</li>`).join('')}</ul><h2>Associated organizations</h2><ul>${catalog.associations.filter(v=>canonicalId(catalog,v.aircraftId)===a.id).map(v=>{const e=catalog.entities.find(e=>e.id===v.entityId);return e?`<li><a href="/notable/${escape(e.slug)}/">${escape(e.displayName)}</a></li>`:'';}).join('')}</ul>`;title=`${a.registrations.at(-1)?.value??a.id} — ${a.manufacturer} ${a.model}`;description=`${title}. Verified aircraft details, registration history and sources. Aircraft activity does not establish who is onboard.`;}
 else if(p.length===2&&p[0]==='notable'){const e=catalog.entities.find(e=>e.slug===p[1]);if(!e)return null;title=e.displayName+' aircraft';description=e.description;socialDescription=`Explore the ${e.displayName} aircraft collection: registrations, sourced stories and available flight views.`;content=Object.entries(entityAircraftGroups(catalog,e.id)).map(([group,rows])=>`<h2>${group==='history'?'Historical':'Current'} aircraft</h2><ul>${rows.map(a=>`<li><a href="/aircraft/${escape(a.id)}/">${escape(a.registrations.at(-1)?.value??a.id)} · ${escape(a.manufacturer)} ${escape(a.model)}</a></li>`).join('')}</ul>`).join('');}
 else return null;
 return {title,description,socialDescription,content,privatePage,path:'/'+p.join('/')+'/'};
}
export const airframeSocialPath=path=>'/watch/social/'+path.split('/').filter(Boolean).join('--')+'.png';
export function airframeDocument(page,shell){const image='https://skyvvard.com'+(page.privatePage?'/watch/social-card.png':airframeSocialPath(page.path));return shell.replace(/<meta (?:property="og:image"|name="twitter:image")[^>]*>/g,t=>t.replace(/content="[^"]*"/,`content="${image}"`)).replace('</main>',`${page.privatePage?'':page.content??''}<p><a href="/notable-aircraft/">Explore aircraft</a> · <a href="/collections/sports/">Sports</a> · <a href="/collections/companies/">Companies</a> · <a href="/collections/special/">Special aircraft</a></p></main>`).replace(/<title>[^<]*<\/title>/,'<title>'+escape(page.title)+' · skyVVard</title>').replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${escape(page.description)}">`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="https://skyvvard.com${page.path}">`).replace(/<meta property="og:title"[^>]*>/,`<meta property="og:title" content="${escape(page.title)} · skyVVard">`).replace(/<meta property="og:description"[^>]*>/,`<meta property="og:description" content="${escape(page.description)}">`).replace(/<meta property="og:url"[^>]*>/,`<meta property="og:url" content="https://skyvvard.com${page.path}">`).replace(/(<h1 id="startup-title"[^>]*>)[^<]*/,`$1${escape(page.title)}`).replace(/(<p id="startup-message"[^>]*>)[^<]*/,`$1${escape(page.description)}`).replace('</head>',`<meta name="twitter:title" content="${escape(page.title)} · skyVVard"><meta name="twitter:description" content="${escape(page.description)}"></head>`).replace('</head>',page.privatePage?'<meta name="robots" content="noindex,nofollow"></head>':'</head>');}
export function airframePaths(){return ['/aircraft/','/notable-aircraft/','/following/','/admin/notable-aircraft/',...discoveryCategories.map(c=>`/collections/${c.slug}/`),...catalog.aircraft.map(a=>`/aircraft/${a.id}/`),...catalog.entities.map(e=>`/notable/${e.slug}/`)];}
