import {airlineDesignators} from '../shared/flight-identifiers.mjs';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function airlineBoard(code,name){
 const iata=Object.entries(airlineDesignators).find(([,icao])=>icao===code)?.[0];
 return `<link rel="stylesheet" href="/watch/airport-board.css"><p>Airline tracking code: <strong>${code}</strong>${iata?` · Ticket prefix: <strong>${iata}</strong>`:''}. Flight codes may be shared by partner airlines; this board lists the operating airline supplied by the schedule service.</p><div class="airport-board-links"><a href="/airlines/">All airlines</a><a href="/airports/">Airport boards</a></div>
 <section class="airport-board airline-board" aria-label="Airline flight board" data-airline="${code}" data-timezone="UTC">
 <div class="board-masthead"><div><span class="board-kicker">AIRLINE FLIGHT INFORMATION</span><h2>${code}<span>${escape(name)}</span></h2></div><div class="board-clock"><time id="board-clock">Current UTC time</time><small>All dates and times in UTC</small></div></div>
 <div class="board-actions"><div role="tablist" aria-label="Flight activity"><button role="tab" id="all-tab" aria-controls="board-panel" aria-selected="true" data-direction="all">All supplied</button><button role="tab" id="current-tab" aria-controls="board-panel" aria-selected="false" tabindex="-1" data-direction="current">Active</button><button role="tab" id="upcoming-tab" aria-controls="board-panel" aria-selected="false" tabindex="-1" data-direction="upcoming">Upcoming</button></div><button id="board-fullscreen" type="button">Full screen</button></div>
 <div class="board-tools"><label>Find a flight<input id="board-search" type="search" placeholder="Flight, airport or aircraft type" maxlength="80"></label><button id="board-refresh" type="button" disabled>Load flights</button></div>
 <p id="board-access" role="status">Checking schedule availability…</p><a id="board-account" href="/account/" hidden>Sign in / Premium</a>
 <div id="board-panel" role="tabpanel" aria-labelledby="all-tab"><p id="board-update">No schedules loaded.</p><p id="board-error" role="alert" hidden></p><div class="board-table-scroll" tabindex="0" role="region" aria-label="Scrollable flight board"><table><caption id="board-caption">${code} flights · dates and times in UTC</caption><thead><tr><th scope="col">Flight</th><th scope="col">From</th><th scope="col">To</th><th scope="col">Departure (UTC)</th><th scope="col">Arrival (UTC)</th><th scope="col">Aircraft</th><th scope="col">Status</th></tr></thead><tbody id="board-rows"></tbody></table></div><p id="board-empty">Load the board to see available flights.</p></div>
 <p class="board-note">AirLabs supplies schedules up to 10 hours ahead, with up to 50 results per check here. This is a partial view, not the airline’s complete timetable. Active means provider-reported active status. Upcoming means scheduled with a future departure time. Aircraft types, terminals and gates appear only when supplied. Checks use your Premium allowance; shared results may be up to five minutes old.</p></section><noscript><p>Enable JavaScript to load flight schedules.</p></noscript><script type="module" src="/watch/airport-board.js"></script>`;
}
