// Public policy text describes implemented behavior; no invented jurisdiction or company address.
const contact='<a href="mailto:contact@skyvvard.com">contact@skyvvard.com</a>';
const section=(title,text)=>`<section><h2>${title}</h2>${text}</section>`;
export const legalPages={
 '/terms/':{title:'Terms of Service',description:'Terms for using Skyward, operated by SSARI Inc.',content:`<p>Last updated: September 30, 2026. These terms apply to Skyward at skyvvard.com, operated by SSARI Inc. (“we”, “us”). Contact: ${contact}.</p>`+
 section('Using Skyward','<p>By creating an account or using Skyward, you agree to these terms. If you cannot legally enter this agreement, a parent or guardian must authorize and supervise your use. You are responsible for your account credentials and for content you submit.</p>')+
 section('Exploration and simulation','<p>Skyward is an exploration and entertainment service, not an aviation navigation, air traffic control, emergency or safety system. Do not use it to make operational flight decisions.</p><p>Received aircraft observations may be delayed, incomplete or unavailable. Estimated motion, animated landings, taxiing, gates, weather effects and fictional Skyward traffic are visualizations, not confirmation of real events. Premium does not guarantee real-time coverage everywhere or access to passenger manifests.</p>')+
 section('Your trips and shared content','<p>Import only boarding passes and information you have permission to use. A submitted name, seat or trip is user-provided information, not proof that someone is onboard. Keep sensitive booking details private.</p><p>You retain rights to your content and authorize us to process and display it as needed to provide the features you choose. Publishing a traveler profile or sharing a link makes the selected information available to its audience. You can stop sharing, but we cannot recall copies made by others. Do not publish another person’s travel information without their permission.</p>')+
 section('Premium and payments','<p>Available features, prices, billing interval and usage allowances are shown before purchase. Test-mode checkout is labeled and does not create a live paid subscription. In live mode, recurring subscriptions renew under the terms displayed at checkout until canceled. Use the account billing controls, when available, or contact us for cancellation or billing help.</p><p>Cancellation stops future renewals; the checkout and account screens describe remaining access. For refund requests or billing errors, contact us. Nothing here removes mandatory cancellation, refund or consumer rights that apply to you.</p>')+
 section('Fair use and ownership','<p>Do not bypass access controls or usage limits, interfere with the service, attempt unauthorized access, harass people, or use tracking and shared trips to stalk or expose someone’s private information. Do not upload malicious or unlawful content.</p><p>Skyward software, branding and supplied content remain the property of their respective owners. Maps, aircraft models, music and other third-party material have their own licenses and credits. Access to the service does not grant permission to redistribute those assets.</p>')+
 section('Availability and changes','<p>Features depend on external data, network availability and service capacity. We may maintain, change or suspend features, and may restrict accounts for abuse or security reasons. Where practical, we will explain material restrictions and offer a way to contact us. We will communicate material changes affecting a paid subscription as required by applicable law.</p>')+
 section('Responsibility and disputes',`<p>To the extent permitted by applicable law, the service is provided as available without a guarantee of uninterrupted operation or accurate flight information. Nothing in these terms excludes liability or rights that cannot lawfully be excluded. Contact ${contact} to resolve a concern. These terms do not require arbitration or take away your right to use an applicable court or consumer authority.</p>`)+
 section('Privacy and updates','<p>Our <a href="/privacy/">Privacy Policy</a> explains how information is handled. We will publish revised terms here with an updated date and provide additional notice of material changes where required.</p>')},
 '/privacy/':{title:'Privacy Policy',description:'How SSARI Inc. handles information when you use Skyward.',content:`<p>Last updated: September 30, 2026. SSARI Inc. operates Skyward at skyvvard.com and is responsible for the personal information described here. For privacy requests, contact ${contact}.</p>`+
 section('Information you provide','<p>Accounts use your name, email address, password hash, email-verification state and session information. We do not store your password in plain text. Supported account features may store saved flights, trips, viewing preferences, compact simulator progress and notification settings. Support requests contain the information you choose to email us.</p><p>If you buy Premium, the payment provider processes payment information. Skyward stores the identifiers and subscription status needed to manage access; it does not store your full payment-card details.</p>')+
 section('Boarding passes and private trips','<p>The scanner decodes camera images and imported photos or PDFs in your browser. The scanner does not upload the raw pass or barcode to our account service. Shared files may be held temporarily on your device while you complete an import.</p><p>You review the extracted trip before saving it. The supported saved fields include a display name or initials, flight, airports, date and seat. Choose initials or a nickname if you do not want to retain a name. Saving or syncing a trip sends the reviewed fields needed for that feature. Do not put booking references or sensitive identity information in free-text fields. We do not retrieve airline passenger manifests or automatically read all passes in your wallet.</p>')+
 section('Local storage and permissions','<p>Preferences, guest watchlists, downloaded data and local recordings may remain in your browser’s storage. Clearing site data removes local copies and may sign you out; it does not delete account data on our servers. Supported synchronization is separate from local storage.</p><p>Essential cookies maintain sign-in and security. Camera access requires your browser permission and is used for scanning when you choose it. Push notifications require permission. You can revoke permissions through your browser.</p>')+
 section('Public travelers and sharing','<p>Public traveler profiles and shared journeys are optional. Their audience can see the display name and trip or viewing details included in the sharing preview. Public profiles are not official passenger lists. Keep private information out of your display name. A private link can be forwarded by its recipients.</p><p>You can revoke sharing or let a link expire. This does not remove screenshots or other copies already made by recipients. Saving a private boarding pass does not by itself publish a traveler profile.</p>')+
 section('Technical information','<p>Requests expose network information such as IP address, browser information and request times to the services handling them. Authentication uses session and security information to protect accounts. Map requests contain the region being viewed; that is not necessarily your physical location. Connected map, imagery, audio and aviation services may also receive requests from your browser or our servers.</p>')+
 section('Why we use information','<p>We process account and subscription information to deliver the service you request, maintain security, prevent abuse and answer support requests. Optional sharing and notification features operate according to your choices. Where applicable law requires a legal basis, these purposes rely on performance of our agreement, legitimate interests in operating a secure service, legal obligations, or consent for optional processing that requires it. You may withdraw consent for optional processing without affecting processing already performed lawfully.</p>')+
 section('Service providers and international processing','<p>Our deployment uses Cloudflare for hosting, account storage and assets, Resend for account emails, and a configured payment provider such as Stripe for checkout. Connected aviation, map and optional audio services supply their respective features. Providers process the information necessary for those tasks and may operate outside your country. Their own policies apply to information they collect directly.</p><p>We do not sell personal information or use submitted boarding passes for advertising. We may disclose information where legally required, to protect users and the service, or as part of a business transfer subject to applicable protections.</p>')+
 section('Retention and security','<p>Account data is retained while needed to provide your account and requested features, resolve disputes and meet applicable legal obligations. Sessions expire, and scheduled maintenance removes eligible expired authentication records in batches. Deleting a saved item or revoking a share removes it from the active feature; necessary security or legal records may have separate retention.</p><p>We use access controls, password hashing and encrypted connections. No system can promise absolute security. Never send passwords, payment-card details or raw boarding-pass barcodes to support.</p>')+
 section('Your choices and rights',`<p>You can edit or remove supported saved items in the app, stop sharing, and change browser permissions. Contact ${contact} to request account deletion, access, correction, an export, or other applicable privacy rights. We may need to verify your identity before acting. Depending on your location, you may also have rights to restrict or object to processing and complain to your local data-protection authority.</p><p>Skyward is not directed at children under 13, and we do not knowingly collect their personal information. Contact us if you believe a child has supplied it so we can investigate and remove it as appropriate.</p>`)+
 section('Policy updates',`<p>We will update this page when our practices change and provide additional notice where required. For questions about this policy or our company’s contact details, email ${contact}. See also our <a href="/terms/">Terms of Service</a>.</p>`)}
};
