import test from 'node:test';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';
import {parseMetars,nearestReport,createLocalWeather} from './local-weather.mjs';
import {altitudeWeather,weatherSummary,reportDistanceKm} from '../src/lib/localWeather.ts';
const now=Date.parse('2026-09-28T12:00:00Z');
const csv='raw_text,station_id,observation_time,latitude,longitude,elevation_m,wx_string,sky_cover,cloud_base_ft_agl,sky_cover,cloud_base_ft_agl,visibility_statute_mi,wind_dir_degrees,wind_speed_kt,wind_gust_kt,temp_c\n"METAR TEST +TSRA, BKN010 OVC030",TEST,2026-09-28T11:30:00Z,38,-77,100,+TSRA,BKN,1000,OVC,3000,2,270,10,20,5\nMETAR SNOW -SN,SNOW,2026-09-28T11:40:00Z,60,25,0,-SN,OVC,500,,,3,180,5,,0\nMETAR CLEAR CAVOK,CLEAR,2026-09-28T11:50:00Z,39,-78,50,,,,,,10+,0,0,,15\n';
test('CSV preserves quoted METAR text, cloud layers and AGL-to-MSL altitude; rain/snow/storm differ',()=>{const rows=parseMetars(csv);assert.equal(rows.length,3);assert.match(rows[0].raw,/,/);assert.equal(rows[0].clouds[0].baseM,404.8);assert.equal(rows[0].clouds.length,2);assert.equal(rows[0].storm,true);assert.equal(rows[0].rain,1);assert.equal(rows[1].snow,.55);assert.equal(rows[1].rain,0);assert.equal(rows[2].cloudsKnown,true);assert.equal(rows[2].visibilityKm,16.09344);assert.match(weatherSummary(rows[1]),/Snow/);});
test('Nearby selection rejects stale, future and remote reports; unknown oceans are not clear',()=>{const rows=parseMetars(csv);assert.equal(nearestReport(rows,38,-77,now).station,'TEST');assert.equal(nearestReport(rows,0,0,now),null);assert.equal(nearestReport(rows,38,-77,now+10800000),null);assert.equal(nearestReport(rows,38,-77,now-10800000),null);assert.ok(reportDistanceKm({lat:0,lon:179.9},{lat:0,lon:-179.9})<25);});
test('Aircraft above the depicted cloud tops do not get surface rain; cloud penetration uses layer altitude',()=>{const r=parseMetars(csv)[0];assert.equal(altitudeWeather(r,600).inside,true);assert.equal(altitudeWeather(r,12000).precipitation,0);assert.equal(altitudeWeather(r,100).precipitation,1);});
test('Global snapshot is shared, cached, bounded on failure and retains original observation times',async()=>{let calls=0,time=now,fail=false;const service=createLocalWeather({now:()=>time,fetchImpl:async()=>{calls++;await new Promise(r=>setTimeout(r,2));return fail?new Response('',{status:503}):new Response(gzipSync(csv));}});const [a,b]=await Promise.all([service(38,-77),service(60,25)]);assert.equal(calls,1);assert.equal(a.status,'current');assert.equal(b.report.station,'SNOW');await service(39,-78);assert.equal(calls,1);time+=601000;fail=true;const stale=await service(38,-77);assert.equal(stale.status,'stale');assert.equal(stale.report.observedAt,Date.parse('2026-09-28T11:30:00Z'));await service(38,-77);assert.equal(calls,2);time+=7200000;assert.equal((await service(38,-77)).status,'unavailable');await assert.rejects(service(NaN,0),/valid location/);});

test('Globe overview shares the download and excludes expired reports',async()=>{let calls=0,time=now;const service=createLocalWeather({now:()=>time,fetchImpl:async()=>{calls++;return new Response(gzipSync(csv));}});const [local,overview]=await Promise.all([service(38,-77),service.overview()]);assert.equal(calls,1);assert.equal(local.report.station,'TEST');assert.equal(overview.reports.length,2);assert.ok(overview.reports.every(r=>r.clouds.length));time+=10800000;assert.deepEqual((await service.overview()).reports,[]);});
