import {gunzipSync} from 'node:zlib';
const SOURCE='https://aviationweather.gov/data/cache/metars.cache.csv.gz';
function csv(line){const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){cells.push(value);value='';}else value+=c;}cells.push(value);return cells;}
const num=v=>v!==''&&v!=null&&Number.isFinite(Number(v))?Number(v):null;
export function parseMetars(input){const lines=input.split(/\r?\n/),head=lines.findIndex(l=>l.startsWith('raw_text,station_id,'));if(head<0)throw Error('Weather schema unavailable.');const names=csv(lines[head]),index=name=>names.indexOf(name),cloudIndices=names.flatMap((n,i)=>n==='sky_cover'?[i]:[]);return lines.slice(head+1).filter(Boolean).flatMap(line=>{const row=csv(line),get=name=>row[index(name)]??'',lat=num(get('latitude')),lon=num(get('longitude')),observedAt=Date.parse(get('observation_time'));if(lat===null||lon===null||Math.abs(lat)>90||Math.abs(lon)>180||!Number.isFinite(observedAt))return [];
 const elevation=num(get('elevation_m')),wx=get('wx_string'),raw=get('raw_text').slice(0,500),storm=/TS/.test(wx),clouds=cloudIndices.flatMap(i=>{const cover=row[i],base=num(row[i+1]);return ['FEW','SCT','BKN','OVC','VV'].includes(cover)&&base!==null&&base>=0&&base<=60000&&elevation!==null&&elevation>=-500&&elevation<=9000?[{cover,baseM:base*.3048+elevation}]:[];});const visibility=parseFloat(get('visibility_statute_mi'));
 return [{station:get('station_id'),lat,lon,observedAt,elevationM:elevation,raw,clouds,cloudsKnown:clouds.length>0||/\b(CAVOK|SKC|CLR|NSC|NCD)\b/.test(raw),rain:/RA|DZ/.test(wx)?wx.includes('+')?1:wx.includes('-')?.35:.7:0,snow:/SN|SG|PL|IC/.test(wx)?wx.includes('+')?1:.55:0,hail:/GR|GS/.test(wx),storm,fog:/FG|BR/.test(wx),visibilityKm:Number.isFinite(visibility)?visibility*1.609344:null,temperatureC:num(get('temp_c')),windDirection:num(get('wind_dir_degrees')),windKnots:num(get('wind_speed_kt')),gustKnots:num(get('wind_gust_kt'))}];});}
export function weatherDistance(a,b){const r=Math.PI/180,dlat=(a.lat-b.lat)*r,dlon=(a.lon-b.lon)*r,h=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlon/2)**2;return 12742*Math.asin(Math.sqrt(Math.min(1,h)));}
export function nearestReport(rows,lat,lon,now){let report=null,distance=150;for(const row of rows){if(now-row.observedAt>7200000||row.observedAt-now>300000)continue;const d=weatherDistance(row,{lat,lon});if(d<distance){report=row;distance=d;}}return report?{...report,distanceKm:Math.round(distance*10)/10}:null;}
export function createLocalWeather({fetchImpl=fetch,now=Date.now}={}){let rows=[],fetchedAt=0,pending=null,retryAt=0,failed=false;
 async function refresh(){if(pending)return pending;if(now()<retryAt)return;pending=(async()=>{try{const r=await fetchImpl(SOURCE,{headers:{'User-Agent':'Skyward-weather/1.0'},signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('Weather unavailable');const parts=[];let size=0;for await(const part of r.body){size+=part.length;if(size>4*1024*1024)throw Error('Weather download too large');parts.push(part);}const buffer=Buffer.concat(parts),decoded=buffer[0]===31&&buffer[1]===139?gunzipSync(buffer,{maxOutputLength:16*1024*1024}):buffer;const next=parseMetars(decoded.toString());if(!next.length)throw Error('Weather empty');rows=next;fetchedAt=now();failed=false;}catch{failed=true;retryAt=now()+60000;}finally{pending=null;}})();return pending;}
 const weather=async function weather(lat,lon){if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw Object.assign(Error('Choose a valid location.'),{status:400});if(!fetchedAt||now()-fetchedAt>=600000)await refresh();const report=nearestReport(rows,lat,lon,now());return {status:report?(failed?'stale':'current'):'unavailable',fetchedAt:fetchedAt||null,report,sourceUrl:SOURCE,detail:'Nearby surface observation. Cloud thickness and lightning effects are illustrative, not measured storm positions.'};};
 weather.overview=async()=>{if(!fetchedAt||now()-fetchedAt>=600000)await refresh();const cells=new Map();for(const r of rows){if(now()-r.observedAt>7200000||r.observedAt-now()>300000||!r.clouds.length)continue;const key=`${Math.floor(r.lat)},${Math.floor(r.lon)}`;if(!cells.has(key)||cells.get(key).observedAt<r.observedAt)cells.set(key,r);}return {status:!cells.size?'unavailable':failed?'stale':'current',fetchedAt:fetchedAt||null,reports:[...cells.values()].slice(0,2500),detail:'Illustrative clouds near reporting stations; not a satellite cloud map. Unreported areas are unknown.'};};
 return weather;
}
