import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createServer} from 'node:http';
import {sqlitePremiumStore} from './premium-store.mjs';
import {createPremiumExtras,spotterMatches,inboundEvidence} from './premium-extras.mjs';
import {passportSummary,passportRoute} from '../src/lib/flightPassport.ts';
import {replayHighlights} from '../src/lib/replayHighlights.ts';
import {validateLibrary} from './account-library.mjs';
const start=Date.parse('2026-09-29T12:00:00Z');
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());const store=sqlitePremiumStore(db),u={id:'owner'},j={key:'THY1:unassigned:2026-09-29',callsign:'THY1',date:'2026-09-29'},state={now:start,paid:true,rows:[],sent:[]};const tools=createPremiumExtras({store,entitlement:async()=>state.paid,userById:async id=>id==='owner'?u:null,readJourney:async(id,key)=>id==='owner'&&key===j.key?j:null,listJourneys:async()=>[j],observations:()=>state.rows,notifyVerified:async(...args)=>state.sent.push(args),now:()=>state.now,env:{SKYWARD_PUBLIC_ORIGIN:'http://localhost:8000'}});return {store,u,j,state,tools};}
test('Family groups are premium, owner scoped, bounded and removable after downgrade',async t=>{const f=fixture(t),path='/api/premium/family';f.state.paid=false;await assert.rejects(f.tools.handle(path,'POST',f.u,{label:'Family',journeyKey:f.j.key}),e=>e.status===403);f.state.paid=true;await assert.rejects(f.tools.handle(path,'POST',{id:'other'},{label:'Family',journeyKey:f.j.key}),e=>e.status===404);for(let i=0;i<10;i++)await f.tools.handle(path,'POST',f.u,{key:'f'+i,label:'Family '+i,journeyKey:f.j.key});await assert.rejects(f.tools.handle(path,'POST',f.u,{label:'Extra',journeyKey:f.j.key}),e=>e.status===429);f.state.paid=false;await f.tools.handle(path,'POST',f.u,{key:'f0',remove:true});assert.equal(f.store.list('owner','family').length,9);});
test('Spotter rules reject stale, simulated, mismatched and non-approaching aircraft; deduplicate sightings',async t=>{const f=fixture(t),rule={airport:'IAD',type:'A388',airline:'',registration:'',radius:25,phase:'any'},a={hex:'abcdef',callsign:'UAE1',aircraftType:'A388',targetKind:'aircraft',lat:38.96,lon:-77.45,observedAt:start,altitude:5000,ground:false};assert.ok(spotterMatches(rule,a,null,start));assert.equal(spotterMatches(rule,{...a,simulation:{}},null,start),false);assert.equal(spotterMatches(rule,{...a,observedAt:start-180000},null,start),false);assert.equal(spotterMatches(rule,{...a,aircraftType:'B738'},null,start),false);assert.equal(spotterMatches({...rule,phase:'approach'},a,null,start),false);assert.ok(spotterMatches({...rule,phase:'approach'},a,{time:start-10000,distance:20,altitude:6000},start));await f.tools.handle('/api/premium/spotter','POST',f.u,{...rule,key:'rule'});f.state.rows=[a];await f.tools.handle('/api/premium/spotter/check','POST',f.u,{});assert.equal(f.state.sent.length,1);f.state.now+=60000;await f.tools.tick();assert.equal(f.state.sent.length,1);assert.equal(f.store.list('owner','spotter-hit').length,1);await f.tools.handle('/api/premium/spotter','POST',f.u,{key:'rule',remove:true});assert.equal(f.store.get('owner','spotter-state','rule'),null);});
test('Inbound evidence needs verified matching aircraft, connecting airport and an earlier leg',()=>{const details=flight=>({mode:'live',status:'MATCHED_RECENT_AIRCRAFT',flight}),current={key:'next',details:details({hex:'abcdef',callsign:'THY2',departure:{airport:'IST',scheduledAt:start}})},previous={key:'prev',details:details({hex:'abcdef',callsign:'THY1',arrival:{airport:'IST',scheduledAt:start-3600000,estimatedAt:start+600000}})};assert.equal(inboundEvidence(current,[previous]).lateInbound,true);assert.equal(inboundEvidence(current,[{...previous,details:{...previous.details,mode:'demo'}}]).available,false);assert.equal(inboundEvidence({...current,details:null},[previous]).available,false);assert.equal(inboundEvidence(current,[{...previous,details:details({...previous.details.flight,hex:'123456'})}]).available,false);});
test('Watch rooms keep state in memory, protect host control, validate cameras, expire and revoke guests',async t=>{const f=fixture(t),room=await f.tools.handle('/api/premium/rooms','POST',f.u,{create:true});assert.equal(f.store.scan('room').length,0);await assert.rejects(f.tools.handle('/api/premium/rooms','POST',{id:'other'},{key:room.key,hex:null,camera:null}),e=>e.status===404);await assert.rejects(f.tools.handle('/api/premium/rooms','POST',f.u,{key:room.key,hex:'abcdef',camera:'999,0,100,0,0,0'}),e=>e.status===400);f.state.now+=4000;await f.tools.handle('/api/premium/rooms','POST',f.u,{key:room.key,hex:'abcdef',camera:'20,40,10000,0,-1,0'});const server=createServer((req,res)=>void f.tools.publicHandle(req,res,new URL(req.url,'http://localhost')));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url=`http://127.0.0.1:${server.address().port}/api/watch-room/${room.url.split('=')[1]}`;let response=await fetch(url);assert.equal(response.status,200);const data=await response.json();assert.equal(data.state.hex,'abcdef');assert.equal(data.userId,undefined);assert.equal(response.headers.get('cache-control'),'private, no-store');f.state.now+=2000;response=await fetch(url,{method:'POST',headers:{Origin:'http://localhost:8000','Content-Type':'application/json'},body:JSON.stringify({reaction:'wave'})});assert.equal(response.status,200);f.state.now+=2000;f.state.paid=false;assert.equal((await fetch(url)).status,404);f.state.paid=true;const next=await f.tools.handle('/api/premium/rooms','POST',f.u,{create:true});f.state.now+=7200001;assert.equal((await fetch(url.replace(room.url.split('=')[1],next.url.split('=')[1]))).status,404);});
test('Passport separates watched from flown, filters annual recaps, handles dateline routes',()=>{const flights=[{date:'2026-09-29',from:'IST',to:'IAD',aircraftType:'B789',durationMinutes:600},{date:'2025-01-01',from:'LHR',to:'JFK',aircraftType:'A388',durationMinutes:420,experience:'watched'}];const all=passportSummary(flights,'all');assert.equal(all.flown,1);assert.equal(all.watched,1);assert.equal(all.types.length,2);assert.equal(passportSummary(flights,'2026').flights.length,1);assert.ok(all.km>10000);assert.ok(!passportRoute('NRT','LAX',180).includes('NaN'));assert.equal(validateLibrary('logbook',{...flights[1],callsign:'BAW1'}).experience,'watched');});
test('Replay highlights never infer takeoff across recording gaps',()=>{const p=(time,ground)=>({time,ground,lat:38,lon:-77,altitude:ground?0:500,groundSpeed:100});const r={tracks:[{identity:{hex:'abcdef',callsign:'AAL1'},points:[p(1000,true),p(11000,false),p(21000,true),p(400000,false)]}]};assert.deepEqual(replayHighlights(r).map(x=>x.kind),['Takeoff transition','Landing transition']);});
