import {airlineBoard} from './airline-board.mjs';
import {airportBoard} from './airport-board.mjs';
import {validPublishedFlight} from './published-flights.mjs';
import {airlineNames} from '../src/lib/airlineNames.ts';
import {specialFlightRoute} from '../src/lib/specialFlightRoutes.ts';
import {airframePaths,airframePage,airframeSocialPath} from './airframe-pages.mjs';
import {legalPages} from './legal-pages.mjs';
import {SITE_ORIGIN,CONTACT_EMAIL,SUPPORT_EMAIL,BILLING_EMAIL,PRIVACY_EMAIL,SECURITY_EMAIL,siteSchema} from './site.mjs';
import {errorPage} from './error-pages.mjs';
import catalog from '../data/airport-catalog.json' with {type:'json'};
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const boardMatchPath=path=>/^\/airports\/[^/]+\/board\/$/.test(path);
const airports=Object.entries(catalog).sort((a,b)=>a[1].name.localeCompare(b[1].name));
export function publicOrigin(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.origin:'';}catch{return '';}}
function page(title,description,content,path,origin,noindex=false,socialImage='/watch/social-card.png'){
 const canonical=origin?origin+path:'';
 const schema=siteSchema(origin||SITE_ORIGIN),airport=path.startsWith('/airports/')?catalog[path.split('/')[2]]:null;
 const base=origin||SITE_ORIGIN,airportId=airport?path.split('/')[2]:null,airlineCode=path.startsWith('/airlines/')?path.split('/')[2]:null;
 if(airport){
  const airportUrl=base+`/airports/${airportId}/`,items=[{'@type':'ListItem',position:1,name:'Skyward',item:base+'/'},{'@type':'ListItem',position:2,name:'Airports',item:base+'/airports/'},{'@type':'ListItem',position:3,name:airport.name,item:airportUrl}];
  if(boardMatchPath(path))items.push({'@type':'ListItem',position:4,name:'Arrivals & departures',item:canonical});
  schema['@graph'].push({'@type':'Airport',name:airport.name,iataCode:airport.iata,icaoCode:airport.icao,url:airportUrl,geo:{'@type':'GeoCoordinates',latitude:airport.lat,longitude:airport.lon}},{'@type':'BreadcrumbList',itemListElement:items});
 }
 if(airlineCode&&Object.hasOwn(airlineNames,airlineCode))schema['@graph'].push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Skyward',item:base+'/'},{'@type':'ListItem',position:2,name:'Airlines',item:base+'/airlines/'},{'@type':'ListItem',position:3,name:airlineNames[airlineCode],item:canonical}]});
 return {status:200,type:'text/html; charset=utf-8',body:`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Skyward</title><meta name="description" content="${escape(description)}">${noindex?'<meta name="robots" content="noindex,follow">':''}${canonical?`<link rel="canonical" href="${escape(canonical)}"><meta property="og:url" content="${escape(canonical)}">`:''}<meta property="og:title" content="${escape(title)} · Skyward"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Skyward"><meta property="og:image" content="${escape((origin||SITE_ORIGIN)+socialImage)}"><meta name="twitter:card" content="summary_large_image"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Skyward flight observatory"><meta name="twitter:image" content="${escape((origin||SITE_ORIGIN)+socialImage)}"><meta name="twitter:image:alt" content="Skyward flight observatory"><meta name="twitter:title" content="${escape(title)} · Skyward"><meta name="twitter:description" content="${escape(description)}"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script><link rel="stylesheet" href="/watch/public-pages.css"></head><body><header><a class="brand" href="/" aria-label="Skyward globe"><img src="/watch/brand-orbit.svg" width="32" height="32" alt="" style="vertical-align:middle;margin-right:10px"><span style="display:inline-block;white-space:nowrap;text-transform:none;letter-spacing:.035em;color:#e4eef3;font-weight:700">sky<span style="color:#8fdfc8">VV</span>ard</span></a><nav aria-label="Main"><a href="/">Globe</a><a href="/airports/">Airports</a><a href="/airlines/">Airlines</a><a href="/collections/sports/">Sports teams</a><a href="/collections/special/">Special aircraft</a><a href="/flights/">Find a flight</a><a href="/premium/">Premium</a><a href="/account/">Account</a></nav></header><main><h1>${escape(title)}</h1><p class="intro">${escape(description)}</p>${content}</main><footer><a href="/terms/">Terms</a><a href="/privacy/">Privacy</a><a href="/contact/">Contact</a><a href="/about/">About Skyward &amp; data</a><a href="/methodology/">Methodology</a><span>For exploration. Coverage varies; animations are not flight observations.</span></footer>${(path.startsWith('/flights/')||path.startsWith('/airlines/')||boardMatchPath(path))?'':'<script defer src="/watch/special-flights.js"></script>'}</body></html>`};
}
export function publicPage(url,env=process.env,{flights=[]}={}){
 flights=flights.filter(validPublishedFlight);
 const origin=publicOrigin(env.SKYWARD_PUBLIC_ORIGIN),path=url.pathname;
 const special=specialFlightRoute(path);
 if(special){if(path!==special.path)return {status:308,location:special.path+url.search};return {...page(`${special.name} · ${special.registration}`,`${special.relationship}. Watch this aircraft when recent observations are available. Aircraft activity does not establish who is onboard.`,`<p><a href="/aircraft/${special.aircraftId}/">Aircraft identity and sources</a></p><p>No current position is asserted by this page. The observatory checks the registered aircraft when opened.</p>`,special.path,origin,true,airframeSocialPath(`/aircraft/${special.aircraftId}/`)),observatory:true};}
 if(['/404','/404/'].includes(path))return errorPage(404);
 if(['/500','/500/'].includes(path))return errorPage(500);
 if(path==='/robots.txt')return {status:200,type:'text/plain; charset=utf-8',body:`User-agent: *\nDisallow: /api/\nDisallow: /account/\nDisallow: /following/\nDisallow: /admin/\nDisallow: /share/\nDisallow: /flight-simulator/\nDisallow: /airport-simulation/\n${origin?`Sitemap: ${origin}/sitemap.xml\n`:''}`};
 if(path==='/sitemap.xml')return origin?{status:200,type:'application/xml; charset=utf-8',body:`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/methodology/','/terms/','/privacy/','/contact/','/explore/','/airports/','/airlines/','/flights/','/premium/','/about/',...airports.flatMap(([id])=>[`/airports/${id}/`,`/airports/${id}/board/`]),...Object.keys(airlineNames).sort().map(code=>`/airlines/${code}/`),...airframePaths().filter(p=>{const page=airframePage(p);return !page.privatePage&&!page.redirect;})].map(p=>`<url><loc>${escape(origin+p)}</loc></url>`).join('')}${flights.map(f=>`<url><loc>${escape(origin+'/flights/'+f.code+'/')}</loc><lastmod>${new Date(Math.max(f.observedAt,f.routeCheckedAt)).toISOString()}</lastmod></url>`).join('')}</urlset>`}:{status:503,type:'text/plain',body:'Set SKYWARD_PUBLIC_ORIGIN to enable the sitemap.'};
 if(['/terms','/privacy','/contact','/airports','/explore','/about','/premium','/flights','/account'].includes(path))return {status:308,location:path+'/'+url.search};
 if(path==='/airlines')return {status:308,location:'/airlines/'+url.search};
 if(path==='/airlines/')return page('Airline directory','Choose an airline to explore its available current and upcoming flight schedules.',`<ul class="airport-grid">${Object.entries(airlineNames).sort((a,b)=>a[1].localeCompare(b[1])).map(([code,name])=>`<li><a href="/airlines/${code}/"><b>${escape(name)}</b><span>${code} · Flight board</span></a></li>`).join('')}</ul>`,path,origin);
 const airlineMatch=path.match(/^\/airlines\/([a-z]{3})\/?$/i);
 if(airlineMatch){const code=airlineMatch[1].toUpperCase();if(!Object.hasOwn(airlineNames,code))return errorPage(404);const canonical=`/airlines/${code}/`;if(path!==canonical)return {status:308,location:canonical+url.search};return page(`${airlineNames[code]} (${code}) flights`,'Current flights and schedules up to 10 hours ahead, with routes, aircraft types and updates when supplied.',airlineBoard(code,airlineNames[code]),canonical,origin);}
 const boardMatch=path.match(/^\/airports\/([a-z0-9-]{3,12})\/board\/?$/i);
 if(boardMatch){const id=boardMatch[1].toUpperCase(),a=catalog[id];if(!a)return errorPage(404);const canonical=`/airports/${id}/board/`;if(path!==canonical)return {status:308,location:canonical+url.search};return page(`${id} arrivals & departures`,`${a.name} · ${a.city}, ${a.country}. Flight times, terminals and gates when supplied.`,airportBoard(id,a),canonical,origin);}
 const airportMatch=path.match(/^\/airports\/([a-z0-9-]{3,12})\/?$/i);
 if(airportMatch){const id=airportMatch[1].toUpperCase(),a=catalog[id];if(!a)return errorPage(404);
  if(path!==`/airports/${id}/`)return {status:308,location:`/airports/${id}/`+url.search};
  return {...page(`${a.name} (${id})`,`${a.city}, ${a.country}. Explore the airport and available aircraft observations in Skyward.`,`<p><a class="cta" href="/#airport=${id}">Explore ${id} on the globe</a> · <a href="/airports/${id}/board/">Arrivals &amp; departures board</a></p><dl><dt>IATA / ICAO</dt><dd>${escape(a.iata)} / ${escape(a.icao)}</dd><dt>Location</dt><dd>${escape(a.city)}, ${escape(a.country)}</dd><dt>Coordinates</dt><dd>${a.lat.toFixed(4)}°, ${a.lon.toFixed(4)}°</dd></dl><h2>What you can explore</h2><p>Open the globe to see available runway geometry, aircraft observations and flight views. Terminal, gate and building detail varies by airport.</p><h2>Traffic coverage</h2><p>Aircraft appear only when our connected feeds receive their positions. An empty map does not mean there are no flights. This reference page does not show a live flight count or timetable.</p><p>Airport reference data: <a href="https://ourairports.com/airports/${escape(a.icao)}/">OurAirports</a>. <a href="/airports/">Browse other airports</a>.</p>`,path,origin),observatory:true};
 }
 if(path==='/airports/'){
  const q=(url.searchParams.get('q')??'').trim().slice(0,100),matched=airports.filter(([id,a])=>`${id} ${a.icao} ${a.name} ${a.city} ${a.country}`.toLowerCase().includes(q.toLowerCase()));
  const pages=Math.max(1,Math.ceil(matched.length/60)),raw=Number(url.searchParams.get('page')??1),n=Number.isInteger(raw)?Math.max(1,Math.min(pages,raw)):1;
  const href=p=>`/airports/?q=${encodeURIComponent(q)}&page=${p}`;
  return page('Airport directory','Find an airport by name, city, country or airport code.',`<form action="/airports/"><label for="airport-query">Search airports</label><div class="search"><input id="airport-query" name="q" value="${escape(q)}" maxlength="100" placeholder="Tashkent, TAS, Istanbul…"><button>Search</button></div></form><p>${matched.length} airports · page ${n} of ${pages}</p><ul class="airport-grid">${matched.slice((n-1)*60,n*60).map(([id,a])=>`<li><a href="/airports/${id}/"><b>${id} · ${escape(a.name)}</b><span>${escape(a.city)}, ${escape(a.country)}</span></a></li>`).join('')}</ul><nav aria-label="Directory pages">${n>1?`<a href="${escape(href(n-1))}">← Previous</a>`:''}${n<pages?`<a href="${escape(href(n+1))}">Next →</a>`:''}</nav>`,path,origin,!!q||n>1);
 }
 if(path==='/flights/'){
  const q=(url.searchParams.get('q')??'').trim().toUpperCase().replace(/\s+/g,'');
  if(/^[A-Z0-9]{2,10}$/.test(q))return {status:303,location:`/flights/${q}/`};
  const offset=Math.max(0,Math.min(Math.ceil(flights.length/60)-1,Number.parseInt(url.searchParams.get('page')||'1',10)-1)||0)*60;
  const directory=flights.length?`<h2>Observed flight codes</h2><p>These flight codes have a retained aircraft observation and a position-compatible reported route. They are not a departure timetable.</p><ul class="airport-grid">${flights.slice(offset,offset+60).map(f=>`<li><a href="/flights/${f.code}/"><b>${f.code} · ${escape(airlineNames[f.code.slice(0,3)])}</b><span>${f.airports.map(id=>escape(catalog[id].city||catalog[id].name)+' ('+escape(id)+')').join(' → ')}</span></a></li>`).join('')}</ul><nav aria-label="Flight directory pages">${offset?`<a href="/flights/?page=${offset/60}">Previous</a>`:''}${offset+60<flights.length?`<a href="/flights/?page=${offset/60+2}">Next</a>`:''}</nav>`:'';
  return page('Find a flight','Enter the flight number on your ticket or a tracking callsign.',`<form action="/flights/"><label for="flight-query">Flight number</label><div class="search"><input id="flight-query" name="q" maxlength="16" pattern="[A-Za-z0-9 ]{2,16}" required placeholder="UA613 or UAL613"><button>Find flight</button></div></form><p>Search current activity worldwide. Supported airline codes work in either format, such as UA613 or UAL613. Codeshares and changed callsigns may require the operating airline’s flight code. Flight numbers repeat each day; confirm the route and date with your traveller. Past and scheduled flights may not be available.</p>${directory}`,path,origin,offset>0);
 }
 const flightMatch=path.match(/^\/flights\/([a-z0-9]{2,10})(?:\/(\d{4}-\d{2}-\d{2}))?\/?$/i);
 if(flightMatch){const code=flightMatch[1].toUpperCase(),date=flightMatch[2];if(date&&(!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date))return errorPage(404);const canonical=`/flights/${code}/${date?date+'/':''}`;if(path!==canonical)return {status:308,location:canonical+url.search};const published=!date&&url.searchParams.get('live')!=='1'&&flights.find(f=>f.code===code);if(published)return publishedFlightPage(published,origin);return {...page(`${code}${date?' · '+date:''} flight lookup`,date?`Available observations for ${code} on ${date} (UTC). Historical tracking is not available.`:'Look for the most recent available aircraft observation.',`<p><a class="cta" href="/?flight=${code}">Look up ${code} on the globe</a></p><p>No current position or route has been verified on this page. A callsign can be reused across dates. ${date?'This link is limited to observations dated '+date+' (UTC). It does not provide a historical replay.':'The globe will query the connected feeds.'}</p>`,canonical,origin,true),observatory:true};}
 if(legalPages[path]){const legal=legalPages[path];return page(legal.title,legal.description,legal.content,path,origin);}
 if(path==='/contact/')return page('Contact Skyward','Questions, feedback or help with your account?',`<p><a class="cta" href="mailto:${CONTACT_EMAIL}">Email ${CONTACT_EMAIL}</a></p><dl><dt>Product and account help</dt><dd><a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></dd><dt>Subscriptions and billing</dt><dd><a href="mailto:${BILLING_EMAIL}">${BILLING_EMAIL}</a></dd><dt>Privacy and deletion requests</dt><dd><a href="mailto:${PRIVACY_EMAIL}">${PRIVACY_EMAIL}</a></dd><dt>Security reports</dt><dd><a href="mailto:${SECURITY_EMAIL}">${SECURITY_EMAIL}</a></dd></dl><p>For a technical issue, include your browser, the airport or flight you were viewing, and what happened. Please do not send passwords, payment details or raw boarding-pass barcodes.</p>`,path,origin);
 if(path==='/explore/')return page('Explore the sky','Follow aircraft on an interactive 3D globe and explore airports around the world.',`<p><a class="cta" href="/">Open the flight observatory</a></p><div class="cards"><section><h2>Follow a flight</h2><p>Explore aircraft models, cockpit views and available route information.</p><a href="/flights/">Find a callsign →</a></section><section><h2>Explore an airport</h2><p>Find airports by city or code, then open their location on the globe.</p><a href="/airports/">Browse airports →</a></section><section><h2>Take the controls</h2><p>Premium flight simulation with Easy and Advanced controls.</p><a href="/premium/">Explore Premium →</a></section></div>`,path,origin);
 if(path==='/premium/')return page('Skyward Premium','More ways to follow, save and simulate your journeys.',`<ul><li>Private boarding-pass scanner: camera, photo and PDF</li><li>Manual private trips with name or display name, flight and seat</li><li>My next flight home, guided setup and calendar import/export</li><li>Personalized aviation feed from recent received observations</li><li>Premium usage dashboard and monthly allowance reset dates</li><li>Trimmed replays, camera sequences and titled portrait/landscape video export</li><li>Synced viewing setups and compact simulator progress</li><li>Personal flight passport, route globe and annual recap</li><li>Family flight groups and expiring private links</li><li>Cinematic replay with local highlight video export</li><li>Private watch-together rooms with shared globe cameras</li><li>Plane-spotter rules and saved airport live desks</li><li>Flight and airport simulators</li><li>Richer flight details where available, within account usage limits</li></ul><p>Free and Premium share the same observed map coverage. Richer flight details require a connected service; Premium does not unlock additional aircraft. Flight-status monitoring uses synthetic checks by default; live checks require a configured provider and verified paid subscription. Verified inbound-flight evidence and notifications require connected data and delivery setup.</p><p>Open your account to check current checkout and live-data availability, annual pricing and usage limits. Airline passenger lists and actual onboard counts are unavailable. Private names and seats are entered or imported by the user.</p><p><a class="cta" href="/?premiumPreview=1">Try a fictional 3D preview</a> <a class="cta" href="/account/">Open your account</a></p>`,path,origin);
 if(path==='/methodology'||path==='/methodology/')return page('Aircraft data methodology','How skyVVard identifies aircraft, evaluates sources and distinguishes observations from animation.',`<h2>Aircraft identity and sources</h2><p>We use public aviation registries, operator disclosures and documented aviation references. Each curated aircraft has a stable aircraft ID; registration and ICAO address changes are recorded separately. A callsign is not a physical aircraft identity.</p><h2>Associations and verification</h2><p>Aircraft associations describe documented organizational relationships. Aircraft activity does not establish who is onboard. VERIFIED records have reviewed evidence; HISTORICAL records are labeled as history; UNVERIFIED records remain unpublished. Associations enter a review queue after 90 days. Review dates do not guarantee that ownership or paint schemes have remained unchanged.</p><h2>Received observations and estimated movement</h2><p>Live discovery requires an airborne observation within two minutes. Every observation retains its source timestamp. Missing coverage, privacy mechanisms and provider restrictions can make tracking incomplete. Smooth motion and animated landings are presentation estimates, not evidence of actual movements or confirmed gates. Unknown destinations remain unknown.</p><h2>Data credits and permitted use</h2><p><a href="https://www.adsb.lol/">ADSB.lol</a> publishes its data under the <a href="https://opendatacommons.org/licenses/odbl/1-0/">Open Database License</a>. Optional <a href="https://flyitalyadsb.com/en/dati/api/">FlyItalyADSB</a> data is credited under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>, subject to API limits. AirLabs details are separately subject to the configured plan and provider terms. Source availability varies; a listed source is not a claim that it is currently connected.</p><h2>Privacy and source restrictions</h2><p>We do not publish private contact information from registry records, identify occupants, reconstruct withheld provider data, or deanonymize temporary privacy addresses. No provider's public availability alone authorizes unrestricted republication. Aircraft profiles link to their reference sources; original photos and registry documents are not reproduced.</p><p><a href="/notable-aircraft/">Explore aircraft collections</a> · <a href="/contact/">Report an incorrect association</a></p>`, '/methodology/',origin);
 if(path==='/about/')return page('About Skyward','A flight observatory for exploring aircraft, airports and the world.',`<h2>Observations and animation</h2><p>Tracking feeds provide received positions, not continuous coverage. Smooth motion between updates and animated arrivals are estimates or simulations. They are not evidence of a real landing, runway assignment or gate.</p><h2>Reference data</h2><p>Airport directory facts use <a href="https://ourairports.com/">OurAirports</a>. The globe’s About the data panel includes credits and licenses for maps, models and connected feeds.</p><h2>Private by default</h2><p>Guest watchlists stay on your device. Accounts can sync supported saved content. We do not provide passenger manifests.</p><p><a class="cta" href="/">Explore the globe</a></p>`,path,origin);
 return null;
}

function publishedFlightPage(f,origin){
 const [from,to]=f.airports.map(id=>catalog[id]),operator=airlineNames[f.code.slice(0,3)];
 const airportLink=(a,id)=>`<a href="/airports/${escape(id)}/">${escape(a.name)} (${escape(id)} / ${escape(a.icao)})</a>`;
 return page(`${f.code} · ${operator} · ${f.airports.join(' → ')}`,`Explore ${f.code}, its last reported route from ${from.name} to ${to.name}, and the most recently retained aircraft observation.`,
 `<p><a class="cta" href="/flights/${f.code}/?live=1">Look for ${f.code} on the live globe</a></p>
 <h2>Reported route</h2><p>${airportLink(from,f.airports[0])} → ${airportLink(to,f.airports[1])}</p>
 <p>This route was compatible with the aircraft position when checked on <time datetime="${new Date(f.routeCheckedAt).toISOString()}">${new Date(f.routeCheckedAt).toUTCString()}</time>. It is standing-data route information, not a confirmed flight plan, schedule or current flight status. Flight codes can be reused and routes can change.</p>
 <h2>Last retained aircraft observation</h2><dl><dt>Tracking callsign</dt><dd>${f.code}</dd><dt>Operator identified by callsign prefix</dt><dd><a href="/airlines/${f.code.slice(0,3)}/">${escape(operator)}</a></dd><dt>Observed at (UTC)</dt><dd><time datetime="${new Date(f.observedAt).toISOString()}">${new Date(f.observedAt).toUTCString()}</time></dd>${f.aircraftType?`<dt>Aircraft type code</dt><dd>${escape(f.aircraftType)}</dd>`:''}${f.registration?`<dt>Registration reported by the feed</dt><dd>${escape(f.registration)}</dd>`:''}</dl>
 <p>This retained observation is not a claim that the aircraft is currently airborne. Use the live globe to check for newer available observations. The observation date is not a scheduled departure date.</p>
 <h2>Sources and coverage</h2><p>Aircraft observations: <a href="https://www.adsb.lol/">ADSB.lol</a> (ODbL). Reported route: <a href="https://github.com/adsblol/api">ADSB.lol / Virtual Radar Server standing data</a>. Airport reference data: <a href="https://ourairports.com/">OurAirports</a>. Read our <a href="/methodology/">methodology and coverage limitations</a>.</p><p><a href="/flights/">Browse observed flight codes</a></p><script defer src="/watch/flight-reference.js"></script>`, `/flights/${f.code}/`,origin);
}
