import {legalPages} from './legal-pages.mjs';
import {SITE_ORIGIN,CONTACT_EMAIL,siteSchema} from './site.mjs';
import {errorPage} from './error-pages.mjs';
import catalog from '../data/airport-catalog.json' with {type:'json'};
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const airports=Object.entries(catalog).sort((a,b)=>a[1].name.localeCompare(b[1].name));
export function publicOrigin(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.origin:'';}catch{return '';}}
function page(title,description,content,path,origin,noindex=false){
 const canonical=origin?origin+path:'';
 const schema=siteSchema(origin||SITE_ORIGIN),airport=path.startsWith('/airports/')?catalog[path.split('/')[2]]:null;
 if(airport)schema['@graph'].push({'@type':'Airport',name:airport.name,iataCode:airport.iata,icaoCode:airport.icao,url:canonical,geo:{'@type':'GeoCoordinates',latitude:airport.lat,longitude:airport.lon}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Skyward',item:(origin||SITE_ORIGIN)+'/'},{'@type':'ListItem',position:2,name:'Airports',item:(origin||SITE_ORIGIN)+'/airports/'},{'@type':'ListItem',position:3,name:airport.name,item:canonical}]});
 return {status:200,type:'text/html; charset=utf-8',body:`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Skyward</title><meta name="description" content="${escape(description)}">${noindex?'<meta name="robots" content="noindex,follow">':''}${canonical?`<link rel="canonical" href="${escape(canonical)}"><meta property="og:url" content="${escape(canonical)}">`:''}<meta property="og:title" content="${escape(title)} · Skyward"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Skyward"><meta property="og:image" content="${escape((origin||SITE_ORIGIN)+'/watch/social-card.png')}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script><link rel="stylesheet" href="/watch/public-pages.css"></head><body><header><a class="brand" href="/explore/"><img src="/watch/brand-orbit.svg" width="32" height="32" alt="" style="vertical-align:middle;margin-right:10px">SKYWARD</a><nav aria-label="Main"><a href="/">Globe</a><a href="/airports/">Airports</a><a href="/flights/">Find a flight</a><a href="/premium/">Premium</a><a href="/account/">Account</a></nav></header><main><h1>${escape(title)}</h1><p class="intro">${escape(description)}</p>${content}</main><footer><a href="/terms/">Terms</a><a href="/privacy/">Privacy</a><a href="/contact/">Contact</a><a href="/about/">About Skyward &amp; data</a><span>For exploration. Coverage varies; animations are not flight observations.</span></footer></body></html>`};
}
export function publicPage(url,env=process.env){
 const origin=publicOrigin(env.SKYWARD_PUBLIC_ORIGIN),path=url.pathname;
 if(['/404','/404/'].includes(path))return errorPage(404);
 if(['/500','/500/'].includes(path))return errorPage(500);
 if(path==='/robots.txt')return {status:200,type:'text/plain; charset=utf-8',body:`User-agent: *\nDisallow: /api/\nDisallow: /account/\nDisallow: /share/\nDisallow: /flight-simulator/\nDisallow: /airport-simulation/\n${origin?`Sitemap: ${origin}/sitemap.xml\n`:''}`};
 if(path==='/sitemap.xml')return origin?{status:200,type:'application/xml; charset=utf-8',body:`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/terms/','/privacy/','/contact/','/explore/','/airports/','/flights/','/premium/','/about/',...airports.map(([id])=>`/airports/${id}/`)].map(p=>`<url><loc>${escape(origin+p)}</loc></url>`).join('')}</urlset>`}:{status:503,type:'text/plain',body:'Set SKYWARD_PUBLIC_ORIGIN to enable the sitemap.'};
 if(['/terms','/privacy','/contact','/airports','/explore','/about','/premium','/flights','/account'].includes(path))return {status:308,location:path+'/'+url.search};
 const airportMatch=path.match(/^\/airports\/([a-z0-9]{3,4})\/?$/i);
 if(airportMatch){const id=airportMatch[1].toUpperCase(),a=catalog[id];if(!a)return errorPage(404);
  if(path!==`/airports/${id}/`)return {status:308,location:`/airports/${id}/`};
  return page(`${a.name} (${id})`,`${a.city}, ${a.country}. Explore the airport and available aircraft observations in Skyward.`,`<p><a class="cta" href="/#airport=${id}">Explore ${id} on the globe</a></p><dl><dt>IATA / ICAO</dt><dd>${escape(a.iata)} / ${escape(a.icao)}</dd><dt>Location</dt><dd>${escape(a.city)}, ${escape(a.country)}</dd><dt>Coordinates</dt><dd>${a.lat.toFixed(4)}°, ${a.lon.toFixed(4)}°</dd></dl><h2>What you can explore</h2><p>Open the globe to see available runway geometry, aircraft observations and flight views. Terminal, gate and building detail varies by airport.</p><h2>Traffic coverage</h2><p>Aircraft appear only when our connected feeds receive their positions. An empty map does not mean there are no flights. This reference page does not show a live flight count or timetable.</p><p>Airport reference data: <a href="https://ourairports.com/airports/${escape(a.icao)}/">OurAirports</a>. <a href="/airports/">Browse other airports</a>.</p>`,path,origin);
 }
 if(path==='/airports/'){
  const q=(url.searchParams.get('q')??'').trim().slice(0,100),matched=airports.filter(([id,a])=>`${id} ${a.icao} ${a.name} ${a.city} ${a.country}`.toLowerCase().includes(q.toLowerCase()));
  const pages=Math.max(1,Math.ceil(matched.length/60)),raw=Number(url.searchParams.get('page')??1),n=Number.isInteger(raw)?Math.max(1,Math.min(pages,raw)):1;
  const href=p=>`/airports/?q=${encodeURIComponent(q)}&page=${p}`;
  return page('Airport directory','Find an airport by name, city, country or airport code.',`<form action="/airports/"><label for="airport-query">Search airports</label><div class="search"><input id="airport-query" name="q" value="${escape(q)}" maxlength="100" placeholder="Tashkent, TAS, Istanbul…"><button>Search</button></div></form><p>${matched.length} airports · page ${n} of ${pages}</p><ul class="airport-grid">${matched.slice((n-1)*60,n*60).map(([id,a])=>`<li><a href="/airports/${id}/"><b>${id} · ${escape(a.name)}</b><span>${escape(a.city)}, ${escape(a.country)}</span></a></li>`).join('')}</ul><nav aria-label="Directory pages">${n>1?`<a href="${escape(href(n-1))}">← Previous</a>`:''}${n<pages?`<a href="${escape(href(n+1))}">Next →</a>`:''}</nav>`,path,origin,!!q||n>1);
 }
 if(path==='/flights/'){
  const q=(url.searchParams.get('q')??'').trim().toUpperCase();
  if(/^[A-Z0-9]{2,10}$/.test(q))return {status:303,location:`/flights/${q}/`};
  return page('Find a flight','Search by the aircraft’s tracking callsign.',`<form action="/flights/"><label for="flight-query">Callsign</label><div class="search"><input id="flight-query" name="q" maxlength="10" pattern="[A-Za-z0-9]{2,10}" required placeholder="THY111"><button>Find flight</button></div></form><p>A tracking callsign can differ from the flight number on a ticket. Current observations depend on receiver coverage. Past and scheduled flights may not be available.</p>`,path,origin);
 }
 const flightMatch=path.match(/^\/flights\/([a-z0-9]{2,10})\/?$/i);
 if(flightMatch){const code=flightMatch[1].toUpperCase();if(path!==`/flights/${code}/`)return {status:308,location:`/flights/${code}/`};return page(`${code} flight lookup`,'Look for the most recent available aircraft observation.',`<p><a class="cta" href="/?flight=${code}">Look up ${code} on the globe</a></p><p>No current position or route has been verified on this page. The globe will query the connected feeds; a callsign can be reused across dates.</p>`,path,origin,true);}
 if(legalPages[path]){const legal=legalPages[path];return page(legal.title,legal.description,legal.content,path,origin);}
 if(path==='/contact/')return page('Contact Skyward','Questions, feedback or help with your account?',`<p><a class="cta" href="mailto:${CONTACT_EMAIL}">Email ${CONTACT_EMAIL}</a></p><p>For a technical issue, include your browser, the airport or flight you were viewing, and what happened. Please do not send passwords, payment details or raw boarding-pass barcodes.</p>`,path,origin);
 if(path==='/explore/')return page('Explore the sky','Follow aircraft on an interactive 3D globe and explore airports around the world.',`<p><a class="cta" href="/">Open the flight observatory</a></p><div class="cards"><section><h2>Follow a flight</h2><p>Explore aircraft models, cockpit views and available route information.</p><a href="/flights/">Find a callsign →</a></section><section><h2>Explore an airport</h2><p>Find airports by city or code, then open their location on the globe.</p><a href="/airports/">Browse airports →</a></section><section><h2>Take the controls</h2><p>Premium flight simulation with Easy and Advanced controls.</p><a href="/premium/">Explore Premium →</a></section></div>`,path,origin);
 if(path==='/premium/')return page('Skyward Premium','More ways to follow, save and simulate your journeys.',`<ul><li>Private boarding-pass scanner: camera, photo and PDF</li><li>Manual private trips with name or display name, flight and seat</li><li>My next flight home, guided setup and calendar import/export</li><li>Personalized aviation feed from recent received observations</li><li>Premium usage dashboard and monthly allowance reset dates</li><li>Trimmed replays, camera sequences and titled portrait/landscape video export</li><li>Synced viewing setups and compact simulator progress</li><li>Personal flight passport, route globe and annual recap</li><li>Family flight groups and expiring private links</li><li>Cinematic replay with local highlight video export</li><li>Private watch-together rooms with shared globe cameras</li><li>Plane-spotter rules and saved airport live desks</li><li>Flight and airport simulators</li><li>Richer flight details where available, within account usage limits</li></ul><p>Expanded tracking and richer details depend on available coverage; Premium does not guarantee live aircraft everywhere. Flight-status monitoring uses synthetic checks by default; live checks require a configured provider and verified paid subscription. Verified inbound-flight evidence and notifications require connected data and delivery setup.</p><p>Public subscriptions are coming soon. Checkout defaults to test mode; your account identifies the active checkout mode. Airline passenger lists and actual onboard counts are unavailable. Private names and seats are entered or imported by the user.</p><p><a class="cta" href="/?premiumPreview=1">Try a fictional 3D preview</a> <a class="cta" href="/account/">Open your account</a></p>`,path,origin);
 if(path==='/about/')return page('About Skyward','A flight observatory for exploring aircraft, airports and the world.',`<h2>Observations and animation</h2><p>Tracking feeds provide received positions, not continuous coverage. Smooth motion between updates and animated arrivals are estimates or simulations. They are not evidence of a real landing, runway assignment or gate.</p><h2>Reference data</h2><p>Airport directory facts use <a href="https://ourairports.com/">OurAirports</a>. The globe’s About the data panel includes credits and licenses for maps, models and connected feeds.</p><h2>Private by default</h2><p>Guest watchlists stay on your device. Accounts can sync supported saved content. We do not provide passenger manifests.</p><p><a class="cta" href="/">Explore the globe</a></p>`,path,origin);
 return null;
}
