import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {syntheticCount,nearbyObserved,createSyntheticFleet,syntheticFrame,syntheticRoute,clearSyntheticTraffic} from '../src/lib/syntheticTraffic.ts';
import {appendTrail,hasPosition} from '../src/lib/aircraft.ts';import {LiveMotion} from '../src/lib/liveMotion.ts';import {fleetUri,fallbackFleetUri} from '../src/lib/flightPresentation.ts';
const home={...JSON.parse(readFileSync(new URL('../public/data/airports/TAS.json',import.meta.url))),elevationFt:1417};
test('sparse observations fill to twenty only below ten real aircraft',()=>{for(const [count,expected] of [[0,20],[1,19],[9,11],[10,0],[20,0]])assert.equal(syntheticCount(count),expected);const row={hex:'abc123',targetKind:'aircraft',lat:home.lat,lon:home.lon,observedAt:1000};assert.equal(nearbyObserved([row,{...row,simulation:{}},{...row,observedAt:-999999},{...row,lon:0}],home,25,2000),1);});
test('synthetic flights have separate identity, no observation timestamps and move through shared flight controller',()=>{clearSyntheticTraffic();const rows=createSyntheticFleet(home,new Map(),1000);assert.equal(rows.length,20);assert.equal(new Set(rows.map(a=>a.hex)).size,20);const phases=new Set(rows.map(a=>a.simulation.phase));assert.ok(phases.size>=4);for(const a of rows){assert.equal(a.observedAt,null);assert.ok(hasPosition(a));assert.deepEqual(appendTrail([],a),[]);assert.match(a.callsign,/^SKYTAS/);assert.ok(syntheticRoute(a).simulated);assert.match(fleetUri(a),/SKYWARD/);assert.match(fallbackFleetUri(a),/SKYWARD/);}const a=rows[0],motion=new LiveMotion(),x=motion.sample(a,[],1000),y=motion.sample(a,[],2000);assert.notEqual(x.lon,y.lon);assert.equal(x.simulated,true);assert.equal(x.gear,1);assert.equal(a.observedAt,null);assert.equal(createSyntheticFleet(home,new Map(),2000)[0].hex,a.hex);});
test('detailed Skyward models preserve source rig and resolve local buffers and tail logo',()=>{for(const id of ['a320','b738','b789']){const url=new URL(`../public/models/sourced/branded/${id}-SKYWARD-v1.gltf`,import.meta.url),g=JSON.parse(readFileSync(url));assert.ok(g.images.some(i=>i.uri?.includes('SKYWARD.png')));assert.ok(g.nodes.length>5);for(const b of g.buffers){assert.equal(readFileSync(new URL(b.uri,url)).length,b.byteLength);}assert.match(g.asset.extras.skyward,/licenses retained/);}});

test('fictional destinations require usable geometry, aircraft range and a compatible runway',()=>{clearSyntheticTraffic();const port=JSON.parse(readFileSync(new URL('../public/data/airports/IST.json',import.meta.url)));const rows=createSyntheticFleet(home,new Map([['IST',port]]),1000);for(const a of rows){assert.ok([a.simulation.from,a.simulation.to].includes('IST'));const frame=syntheticFrame(a,3601000);assert.ok(Number.isFinite(frame.lat)&&Number.isFinite(frame.altitude));assert.ok(frame.gear>=0&&frame.gear<=1);}clearSyntheticTraffic();const local=createSyntheticFleet(home,new Map(),1000);assert.ok(local.every(a=>a.simulation.from==='TAS'&&a.simulation.to==='TAS'));});
