"""Customer discovery, dashboard, replay, sharing and preview regression; fixture data only."""
import sys,time,json,urllib.parse
import regression as f
from playwright.sync_api import expect
base=f.rows()[0]
f.rows=lambda:[{**base,'observedAt':int(time.time()*1000)-1000,'lat':38.947,'lon':-77.55,'altitude':2200,'groundSpeed':150,'heading':90,'verticalRate':-700},{**base,'hex':'123abc','callsign':'GROUND1','observedAt':int(time.time()*1000)-1000,'ground':True,'lat':38.947,'lon':-77.46,'altitude':291,'groundSpeed':12}]
def run(page):
 errors=[];console=[];requests=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:console.append(m.text) if m.type=='error' else None);page.on('request',lambda r:requests.append(r.url));page.add_init_script(f.INIT)
 page.add_init_script("localStorage.setItem('skyward.watches.v1',JSON.stringify([{hex:'abcdef',callsign:'THY111',registration:'TC-TEST',aircraftType:'B738'}]));localStorage.setItem('skyward.alerts.enabled.v1','true');")
 def mock(r):
  if urllib.parse.urlparse(r.request.url).path=='/api/account':r.fulfill(json={'enabled':False,'billingReady':False,'mode':'test','user':None,'usage':None});return
  f.mock(r)
 page.route('**/api/**',mock);page.goto(f.URL+'/#airport=IAD',wait_until='domcontentloaded');page.get_by_role('button',name='View THY111',exact=True).wait_for();assert 'Skyward' in page.title()
 page.get_by_role('button',name='Watch something interesting',exact=True).click();flight=page.get_by_role('region',name='Passenger flight view');flight.wait_for();page.wait_for_timeout(2500);expect(flight).to_be_visible();assert page.evaluate("JSON.parse(localStorage.getItem('skyward.last-flight.v1')).hex")=='abcdef';print('PASS one-click discovery opens flight view',flush=True)
 page.get_by_role('button',name='Share view',exact=True).click();link=page.get_by_label('Shareable view link').input_value();assert 'scene=flight' in link and 'view=side' in link
 with page.expect_download() as download:page.get_by_role('button',name='Save map image',exact=True).click()
 assert download.value.suggested_filename.endswith('.png');download.value.save_as(str(f.ARTIFACTS/'scene-export.png'));page.get_by_role('button',name='Close share',exact=True).click();page.goto(link,wait_until='domcontentloaded');page.get_by_role('region',name='Passenger flight view').wait_for(timeout=30000);page.wait_for_timeout(1500);expect(page.get_by_role('region',name='Passenger flight view')).to_be_visible();print('PASS scene link restores flight viewpoint and image exports',flush=True)
 page.get_by_role('button',name='Close flight view',exact=True).click();page.get_by_role('button',name='My flights',exact=True).click();dashboard=page.get_by_role('region',name='My flights dashboard');expect(dashboard.get_by_role('button',name='Resume THY111')).to_be_visible();expect(dashboard.get_by_role('button',name='Watch flight')).to_be_visible();page.get_by_role('button',name='Save IAD as favorite').click();page.screenshot(path=str(f.ARTIFACTS/'dashboard-desktop.jpg'),type='jpeg',quality=65);dashboard.get_by_role('button',name='Resume THY111').click();page.get_by_role('region',name='Passenger flight view').wait_for();page.get_by_role('button',name='Close flight view',exact=True).click();print('PASS dashboard saved watch, airport favorite and resume',flush=True)
 page.get_by_role('button',name='Explore tools',exact=True).click();page.get_by_role('button',name='Activity',exact=True).click();page.locator('.airport-timeline>summary').click();page.get_by_role('button',name='Ground activity',exact=True).click();expect(page.locator('.airport-timeline')).to_contain_text('GROUND1');page.get_by_role('button',name='Close explore tools').click()
 alerts=page.locator('.watch-alerts');alerts.locator('summary').click();expect(alerts).to_contain_text('Destination alerts');page.context.grant_permissions(['notifications']);alerts.get_by_role('button',name='Enable browser notifications').click();expect(alerts.get_by_role('button',name='Disable browser notifications')).to_be_visible();alerts.get_by_role('button',name='Disable browser notifications').click();alerts.locator('summary').click();print('PASS ground timeline and notification opt-in controls',flush=True)
 page.get_by_role('button',name='Upgrade',exact=True).click();page.get_by_role('button',name='Preview premium features').click();preview=page.get_by_role('region',name='Premium feature preview');expect(preview).to_contain_text('not live flight data');expect(preview).to_contain_text('gate unavailable');page.screenshot(path=str(f.ARTIFACTS/'premium-desktop.jpg'),type='jpeg',quality=65);page.get_by_role('button',name='Close upgrade details').click()
 page.get_by_role('button',name='Record session',exact=True).click();now=int(time.time()*1000);record={'format':'skyward-session','version':1,'name':'Approach fixture','createdAt':now,'tracks':[{'identity':base,'points':[{'time':now-60000+i*30000,'lat':38.947,'lon':-77.60+i*.04,'altitude':2200-i*500,'ground':False,'groundSpeed':150} for i in range(3)]}]};page.get_by_label('Open saved session',exact=True).set_input_files({'name':'approach.json','mimeType':'application/json','buffer':json.dumps(record).encode()});page.get_by_role('button',name='Replay session on globe',exact=True).click();controls=page.get_by_role('region',name='Session replay controls');controls.get_by_role('button',name='Restart replay').click();page.get_by_label('Recorded aircraft',exact=True).select_option('abcdef');page.get_by_label('Replay camera',exact=True).select_option('bird');page.get_by_label('Session playback time',exact=True).fill(str(now-30000));page.wait_for_timeout(500);assert page.evaluate('__viewer.camera.pitch')<-.8;page.get_by_label('Replay camera',exact=True).select_option('side');page.wait_for_timeout(500);assert page.evaluate('__viewer.camera.pitch')>-.8;controls.get_by_role('button',name='Exit session replay').click();print('PASS replay scrub, restart and camera angles',flush=True)
 page.set_viewport_size({'width':390,'height':844});page.get_by_role('button',name='More',exact=True).click();page.get_by_role('button',name='Watch something interesting',exact=True).focus();page.keyboard.press('Enter');page.get_by_role('region',name='Passenger flight view').wait_for();page.get_by_role('button',name='Close flight view',exact=True).click();page.get_by_role('button',name='Explore tools',exact=True).click();page.get_by_role('navigation',name='Exploration tools').get_by_role('button',name='My flights',exact=True).click();expect(page.get_by_role('region',name='My flights dashboard')).to_be_visible();assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(f.ARTIFACTS/'dashboard-mobile.jpg'),type='jpeg',quality=65);page.keyboard.press('Escape');page.get_by_role('button',name='Upgrade',exact=True).click();preview_button=page.get_by_role('button',name='Preview premium features');preview_button.click() if preview_button.count() else None;assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(f.ARTIFACTS/'premium-mobile.jpg'),type='jpeg',quality=65);page.keyboard.press('Escape');assert not page.locator('dialog[open]').count();page.screenshot(path=str(f.ARTIFACTS/'home-mobile.jpg'),type='jpeg',quality=65);assert not errors,errors;assert not page.locator('vite-error-overlay,.cesium-widget-errorPanel').count();assert not [r for r in requests if '/api/premium/' in r or '/api/billing/' in r];print('PASS mobile keyboard/dialog/layout checks; no premium/billing requests or runtime errors',flush=True);print('CONSOLE',console,flush=True)
if __name__=='__main__':f.serve(run)
