import {specialFlightRoute} from './lib/specialFlightRoutes';
import {installSessionHealth} from './lib/sessionHealth';
import './lib/installPrompt';
import {lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {loadGlobeEngine} from './lib/loadGlobeEngine';
import {ErrorBoundary} from './components/ErrorBoundary';
import {ErrorScreen,LoadingScreen} from './components/SystemState';
import './styles.css';
const App=lazy(async()=>{await loadGlobeEngine();return import('./App');});
const AirframePages=lazy(()=>import('./components/AirframePages'));
const AccountPage=lazy(()=>import('./components/AccountPage').then(m=>({default:m.AccountPage})));
const FlightSimulator=lazy(async()=>{await loadGlobeEngine();const m=await import('./components/FlightSimulator');return {default:m.FlightSimulator};});
installSessionHealth();
const path=location.pathname,airframes=/^\/(?:collections(?:\/|$)|aircraft(?:\/|$)|notable(?:\/|$)|notable-aircraft(?:\/|$)|following(?:\/|$)|admin\/notable-aircraft(?:\/|$))/.test(location.pathname),account=path==='/account/'||path==='/account',simulator=path==='/flight-simulator/'||path==='/flight-simulator',globe=!!specialFlightRoute(path)||['/','/watch','/watch/','/watch/index.html','/index.html'].includes(path)||/^\/(?:airports\/[a-z0-9-]{3,12}|flights\/[a-z0-9]{2,10}(?:\/\d{4}-\d{2}-\d{2})?)\/?$/i.test(path);
createRoot(document.getElementById('root')!).render(<ErrorBoundary><Suspense fallback={<LoadingScreen label={airframes?'Loading aircraft directory…':account?'Loading your account…':simulator?'Loading flight simulator…':'Loading the globe and flight controls…'}/>}>{airframes?<AirframePages/>:account?<AccountPage/>:simulator?<FlightSimulator/>:globe?<App/>:<ErrorScreen status={path==='/500'||path==='/500/'?500:404}/>}</Suspense></ErrorBoundary>);
