import {installSessionHealth} from './lib/sessionHealth';
import './lib/installPrompt';
import {lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {loadGlobeEngine} from './lib/loadGlobeEngine';
import {ErrorBoundary} from './components/ErrorBoundary';
import {ErrorScreen,LoadingScreen} from './components/SystemState';
import './styles.css';
const App=lazy(async()=>{await loadGlobeEngine();return import('./App');});
const AccountPage=lazy(()=>import('./components/AccountPage').then(m=>({default:m.AccountPage})));
const FlightSimulator=lazy(async()=>{await loadGlobeEngine();const m=await import('./components/FlightSimulator');return {default:m.FlightSimulator};});
installSessionHealth();
const path=location.pathname,account=path==='/account/'||path==='/account',simulator=path==='/flight-simulator/'||path==='/flight-simulator',globe=['/','/watch','/watch/','/watch/index.html','/index.html'].includes(path);
createRoot(document.getElementById('root')!).render(<ErrorBoundary><Suspense fallback={<LoadingScreen label={account?'Loading your account…':simulator?'Loading flight simulator…':'Loading the globe and flight controls…'}/>}>{account?<AccountPage/>:simulator?<FlightSimulator/>:globe?<App/>:<ErrorScreen status={path==='/500'||path==='/500/'?500:404}/>}</Suspense></ErrorBoundary>);
