import {useEffect,useRef,useState} from 'react';
import {Compass,X,ExternalLink} from 'lucide-react';
export function AboutData({ close }: { close: () => void }) {
  const [feedCredits,setFeedCredits]=useState<{id:string;name:string;url:string}[]>([]);
  useEffect(()=>{const controller=new AbortController();void fetch('/api/feed-sources',{signal:controller.signal}).then(r=>r.ok?r.json():null).then(d=>{if(!controller.signal.aborted&&Array.isArray(d?.sources))setFeedCredits(d.sources.filter((p:{id:string;url:string})=>p.id==='flyitaly'&&p.url==='https://flyitalyadsb.com/'));}).catch(()=>{});return()=>controller.abort();},[]);

  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog className="data-dialog" ref={dialog} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }} aria-labelledby="about-heading"><div className="dialog-heading"><Compass size={25}/><button className="icon-button" onClick={close} aria-label="Close data information"><X size={20}/></button></div><h2 id="about-heading">A clear view of the data.</h2><p>Explore reported aircraft positions and mapped airport facilities. Live observations, estimated routes, and historical map imagery each have different limits. Skyward is for exploration, not navigation or operational decisions.</p><dl>
    <dt>Live, with honest gaps</dt><dd>Positions come from the credited volunteer receiver networks, refreshed about every 10 seconds for the selected flight, 25 seconds for the airport and 35 seconds for the camera, with backoff after selected-flight errors. Map traffic follows the camera independently, using up to five overlapping areas of at most 250 nautical miles each. Wide views show sampled regional coverage, not every aircraft on Earth. Failed areas are explicit; retained fixes keep their original timestamps. We show the time of the position fix, not just the time we received it. Amber markers are older than 30 seconds; after two minutes we show a signal gap. Ocean and surface coverage may be incomplete.</dd>
    <dt>An observation is not an itinerary</dt><dd>Being near Dulles does not mean a flight is landing there. A separate callsign lookup shows estimated origin/destination from ADSB.lol / Virtual Radar Server standing data when available. It is not a confirmed flight plan; mismatches and missing routes stay explicit. No confirmed ETA or assigned gate is supplied. Callsigns are ATC identifiers, which may differ from your ticket's flight number.</dd>
    <dt>Runways and airport models</dt><dd>The worldwide directory includes OurAirports large airports with scheduled service. Runways use available OurAirports endpoints, with the existing FAA source retained for Dulles. Selected airports also include OpenStreetMap facilities. Coverage and snapshot dates appear in each airport’s details. Mapped gates/buildings may be incomplete. Runway alignment is only a geometric inference—not a confirmed landing or clearance. Building heights and aircraft profiles are illustrative, not exact replicas. Flight view uses aircraft-specific community models from the FlightGear, Flightradar24 and FlightAirMap collections where available, with twelve compatible full-aircraft community liveries and airline tail branding for other supported operators. These are not manufacturer CAD or registration-specific liveries. Family matches and approximate procedural fallbacks are labeled. Airline logos identify the operator from the callsign prefix. Full liveries may depict historical paint and a different registration. Tail branding is illustrative when a compatible full livery is unavailable. Source aircraft geometry is preserved; thin tail overlays follow the existing fin surfaces. Axes and origin are aligned for the map. Model credits, per-model GPLv2/GPLv3 licenses and corresponding editable sources are included locally. Major-city labels use Natural Earth reference data. Airborne positions use short estimates from the last known speed and heading. Prediction confidence decreases after 30 seconds for low or descending flights and two minutes in cruise. Display motion can continue through an outage; it does not create new observations. For an actively watched arrival near a mapped runway, Flight view can take over an explicitly labeled arrival animation: approach, gear, touchdown, rollout, taxi and parking. Late observations do not rewind this animation. Return to live tracking or close Flight view to release it. Runway and stand choices are unconfirmed; missing taxi or stand coverage uses an illustrative layout. Other traffic continues following observations with smoothed position and altitude corrections. Reported metrics and recorded tracks retain their original observations and timestamps. Takeoff and landing demos are explicitly labeled simulations, separate from observations. Rigged fallback models animate illustrative gear and wheels; unrigged sourced models keep their source pose. Day and night follow the current UTC sun position across the globe and flight views. Night-side surface detail is brightened for readability. City lights use the historical NASA Black Marble 2016 composite, not a live feed. Aircraft navigation lights and blinking strobes/beacons are illustrative; actual switch states are unavailable. Reduced motion disables flashing. High-detail shadows are available in Layers. Altitude is the reported barometric value.</dd>
    <dt>Your trail, your device</dt><dd>We collect a bounded trail during this session. Replay steps through observed fixes; gaps over two minutes are left disconnected. Aircraft never extrapolate beyond received fixes. Altitude and reported ground-speed charts use those same fixes; missing measurements stay missing. Guest watchlists stay in this browser. Signed-in watchlists sync to your account; Premium can also save viewing setups and recordings. You can download your observed trail. Replay freezes the selected session trail while live observations continue. Whole viewing sessions can also be recorded, saved to a local file and reopened in a separate replay view. Recording is opt-in and bounded to one hour, 1,000 aircraft and 100,000 fixes. Unsaved recordings are lost when this page reloads. Local watch alerts are opt-in and work only while this page is visible.</dd>
    <dt>Offline and device settings</dt><dd>Explore tools can retain visited local app and map assets, bounded to 100 assets and 40 MB. Live traffic, satellite and terrain tiles, aircraft models and source archives are excluded. Offline viewing switches to Atlas; only previously loaded assets are available. Clear or disable this cache in Device &amp; offline. Optional automatic graphics reduction changes this session only and never raises your saved quality setting.</dd><dt>Satellite imagery</dt><dd>World Imagery is provided by Esri and the contributors credited on the map. Photography dates and resolution vary by location; aircraft visible in photography are not live traffic. The atlas remains available if imagery cannot load. The flat globe uses an ellipsoid. Optional Open terrain uses approximate Mapzen elevation tiles, not surveyed airport elevations.</dd><dt>Community infrastructure</dt><dd>Flight observations depend on ADSB.lol and volunteer receivers. Availability is not guaranteed. Requests are shared and cached by the server; original observation timestamps remain visible during outages.</dd>
  </dl><div className="data-links">{feedCredits.map(p=><a key={p.id} href={p.url} target="_blank" rel="noreferrer">{p.name} · CC BY-SA 4.0 aircraft observations</a>)}<a href={`${import.meta.env.BASE_URL}models/sourced/UPSTREAM-CREDITS.md`} target="_blank" rel="noreferrer">Aircraft model credits</a><a href={`${import.meta.env.BASE_URL}models/sourced/manifest.json`} target="_blank" rel="noreferrer">Editable model sources</a><a href="https://www.adsb.lol/docs/open-data/api/" target="_blank" rel="noreferrer">ADSB.lol · ODbL <ExternalLink size={12}/></a><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap <ExternalLink size={12}/></a><a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth <ExternalLink size={12}/></a><a href="https://ourairports.com/data/" target="_blank" rel="noreferrer">OurAirports <ExternalLink size={12}/></a></div><button className="primary-button" onClick={close}>Back to the sky</button></dialog>;
}
