import {lazy,Suspense} from 'react';
const BoardingPasses=lazy(()=>import('./BoardingPasses').then(m=>({default:m.BoardingPasses})));
import {AccountHome} from './AccountHome';
import {JourneyCalendar} from './JourneyCalendar';
import {journeyCalendar} from '../lib/journeyCalendar';
import {careerProgress} from '../lib/accountStoragePolicy';
import {PremiumWorkspace} from './PremiumWorkspace';
import {airportReplay,type AirportReplayFilter} from '../lib/airportReplay';
import {useCallback,useEffect,useState} from 'react';
import {accountRequest,type Account,type Journey} from '../lib/membership';
import {captureViewSettings,deleteAccountItem,getAccountItem,listAccountItems,restoreViewSettings,saveAccountItem,watchlistChanged,type LibraryItem,type LibraryKind} from '../lib/accountLibrary';
import {localWatches} from '../lib/useAccountWatches';
import {parseRecording,type Recording} from '../lib/sessionRecording';
import {downloadText,flightCardSVG} from '../lib/flightCard';
import {AIRPORTS} from '../lib/airportCatalog';
import {distanceNm} from '../lib/experience';
type Trip=Journey&{from?:string;to?:string;details?:Details|null};
type Details={mode:string;message?:string;checkedAt?:number;fetchedAt?:number;flight?:{callsign:string;status?:string;departure?:Stop;arrival?:Stop}|null};
type Stop={airport?:string|null;terminal?:string|null;gate?:string|null;scheduledAt?:number|null;estimatedAt?:number|null;actualAt?:number|null};
type LogEntry={date:string;from:string;to:string;callsign:string;aircraftType:string;registration:string;durationMinutes:number;notes:string};
type Dashboard={journeys:Trip[];alerts:{id:number;message:string;created:number;read:boolean}[];counts:{kind:string;count:number}[]};
const tabs=['Home','Travel','Boarding passes','Watchlist','Alerts','Viewing setups','Replays','Logbook','Simulator','Premium tools'] as const;
type Tab=typeof tabs[number];
const kindFor:Partial<Record<Tab,LibraryKind>>={Watchlist:'watchlist','Viewing setups':'views',Replays:'recordings',Logbook:'logbook',Simulator:'simulator'};
const utc=(n?:number|null)=>n?new Date(n).toLocaleString(undefined,{timeZone:'UTC'})+' UTC':'Not supplied';
function FlightDetails({data}:{data:Details}){
 return <section className="account-flight-details" aria-label="Flight detail result"><h4>{data.mode==='demo'?'Synthetic example · not your flight':data.flight?'Verified flight details':'No matching flight details'}</h4><p>{data.message}</p><strong>{data.flight?.callsign} · {data.flight?.status??'Status unavailable'}</strong><div className="account-stops">{(['departure','arrival'] as const).map(side=>{const s=data.flight?.[side];return <div key={side}><h5>{side==='departure'?'Departure':'Arrival'} · {s?.airport??'Unknown'}</h5><dl><dt>Scheduled</dt><dd>{utc(s?.scheduledAt)}</dd><dt>Estimated</dt><dd>{utc(s?.estimatedAt)}</dd><dt>Actual</dt><dd>{utc(s?.actualAt)}</dd><dt>Terminal / gate</dt><dd>{s?.terminal??'—'} / {s?.gate??'—'}</dd></dl></div>;})}</div><small>Checked {utc(data.checkedAt??data.fetchedAt)}</small></section>;
}
export function AccountWorkspace({account,openJourney}:{account:Account;openJourney:(hex:string)=>Promise<void>}){
 const [tab,setTab]=useState<Tab>(new URLSearchParams(location.search).has('boardingShare')?'Boarding passes':'Home'),[dashboard,setDashboard]=useState<Dashboard>({journeys:[],alerts:[],counts:[]}),[items,setItems]=useState<LibraryItem<any>[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[name,setName]=useState(''),[detail,setDetail]=useState<Details|null>(null),[range,setRange]=useState('upcoming');
 const [replayAirport,setReplayAirport]=useState('IAD'),[replayRadius,setReplayRadius]=useState(25),[replayFilter,setReplayFilter]=useState<AirportReplayFilter>('all');
 const paid=!!account.user?.premium,kind=kindFor[tab];
 const refresh=useCallback(async()=>{const d=await accountRequest<Dashboard>('/api/account/dashboard');setDashboard(d);if(kind&&(paid||kind==='watchlist'))setItems((await listAccountItems(kind)).items);else setItems([]);},[kind,paid]);
 useEffect(()=>{let alive=true;setItems([]);setMessage('');setDetail(null);void (async()=>{try{const d=await accountRequest<Dashboard>('/api/account/dashboard');if(!alive)return;setDashboard(d);if(kind&&(paid||kind==='watchlist')){const r=await listAccountItems(kind);if(alive)setItems(r.items);}}catch(e){if(alive)setMessage(e instanceof Error?e.message:'Account unavailable.');}})();return()=>{alive=false;};},[kind,paid]);
 const run=async(action:()=>Promise<unknown>,success='Saved to your account.')=>{if(busy)return;setBusy(true);setMessage('');try{await action();await refresh();setMessage(success);}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}};
 const remove=(row:LibraryItem)=>void run(()=>deleteAccountItem(kind!,row),'Removed from your account.');
 const upload=async(file:File,collection:'recordings'|'simulator')=>{const max=collection==='simulator'?16:2;if(file.size>max*1024*1024)throw Error(`Choose a file up to ${max} MB.`);const raw=JSON.parse(await file.text());if(collection==='recordings')throw Error('Keep recordings in your browser or export a file.');await saveAccountItem(collection,crypto.randomUUID(),careerProgress(raw));};
 const today=new Date().toISOString().slice(0,10),trips=dashboard.journeys.filter(j=>range==='all'||(range==='upcoming'?j.date>=today:j.date<today)).sort((a,b)=>a.date.localeCompare(b.date));
 const logs=tab==='Logbook'?items.map(i=>i.value as LogEntry):[],visited=new Set(logs.flatMap(l=>[l.from,l.to])),km=logs.reduce((sum,l)=>{const a=AIRPORTS[l.from],b=AIRPORTS[l.to];return sum+(a&&b?distanceNm(a.lat,a.lon,b.lat,b.lon)*1.852:0);},0);
 return <section className="account-workspace" aria-label="Account dashboard">
 <nav className="account-tabs" aria-label="Account sections">{tabs.map(t=><button key={t} disabled={busy} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}{t==='Alerts'&&dashboard.alerts.some(a=>!a.read)?' •':''}</button>)}</nav>
 {message&&<p role="status" className="account-notice">{message}</p>}
 {kind&&kind!=='watchlist'&&!paid?<p className="account-lock">Premium includes {tab.toLowerCase()}. Sign in with an active test subscription to try it. No real payment is taken.</p>:<>
 {tab==='Boarding passes'&&<Suspense fallback={<p>Loading private trips…</p>}><BoardingPasses paid={paid} openJourney={openJourney}/></Suspense>}
 {tab==='Home'&&<AccountHome account={account} dashboard={dashboard} openJourney={openJourney} navigate={setTab}/>}
 {tab==='Premium tools'&&<PremiumWorkspace paid={paid}/>}
 {tab==='Travel'&&<><div className="account-section-heading"><h4>Your travel dashboard</h4><button disabled={busy} onClick={()=>void run(refresh,'Refreshed.')}>Refresh dashboard</button></div><label>Journeys<select value={range} onChange={e=>setRange(e.target.value)}><option value="upcoming">Today &amp; upcoming</option><option value="past">Past dates</option><option value="all">All saved journeys</option></select></label><p>Dates use UTC. Saved dates and routes are not booking confirmation. “Find aircraft” opens its current position, which may be a different flight.</p>
 <JourneyCalendar paid={paid} refresh={refresh}/><details><summary>Add a journey</summary><form className="account-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);void run(async()=>{await accountRequest('/api/journeys',{callsign:d.get('callsign'),hex:d.get('hex'),date:d.get('date'),from:d.get('from'),to:d.get('to'),alerts:paid});form.reset();});}}>
 <label>Flight callsign<input name="callsign" required maxLength={10} placeholder="THY111"/></label><label>Aircraft hex identifier (optional)<input name="hex" pattern="[a-fA-F0-9]{6}" maxLength={6} placeholder="abcdef"/></label><label>Departure date (UTC)<input name="date" type="date" required defaultValue={today}/></label><label>From (optional)<input name="from" list="account-airports" maxLength={4}/></label><label>To (optional)<input name="to" list="account-airports" maxLength={4}/></label><button disabled={busy||!paid}>Save journey · Premium</button></form></details>
 {!trips.length&&<p>No journeys in this date range. Save a selected flight or add one above.</p>}<ul className="account-cards">{trips.map(j=><li key={j.key}><h4>{j.callsign} <span>{j.from||'Origin unknown'} → {j.to||'Destination unknown'}</span></h4><p>{j.date} · {j.details?.mode==='live'?j.details.flight?.status??'Status unknown':'Flight status not verified'}</p><div className="membership-actions"><button disabled={busy||!j.hex} onClick={()=>void openJourney(j.hex)}>Find aircraft</button><button disabled={busy||!paid} onClick={()=>void run(async()=>setDetail(await accountRequest<Details>('/api/premium/details',{key:j.key})),'Flight check complete. See the result below.')}>Check flight details</button><button disabled={busy||!paid} onClick={()=>void run(()=>accountRequest('/api/journeys',{...j,alerts:!j.alerts}))}>Alerts {j.alerts?'on':'off'}</button><button onClick={()=>downloadText(`${j.callsign}.ics`,journeyCalendar(j),'text/calendar')}>Add to calendar</button><button disabled={!paid} onClick={()=>downloadText(`skyward-${j.callsign}-${j.date}.svg`,flightCardSVG(j,j.details?.mode==='live'?j.details.flight?.status??'Status unknown':undefined),'image/svg+xml')}>Save flight card</button><button disabled={busy} onClick={()=>void run(()=>accountRequest('/api/journeys',{...j,remove:true}),'Journey removed.')}>Remove journey</button></div>{j.details?.mode==='live'&&<FlightDetails data={j.details}/>}</li>)}</ul>{detail&&<FlightDetails data={detail}/>}</>}
 {tab==='Watchlist'&&<><h4>Synced aircraft watchlist</h4><p>Premium syncs watches across devices. Free watches stay in this browser. Existing account watches can still be viewed and removed. Aircraft identities can fly different routes over time.</p><button disabled={busy||!paid} onClick={()=>void run(async()=>{for(const w of localWatches())await saveAccountItem('watchlist',w.hex,w);watchlistChanged();},'Browser watchlist imported.')}>Import this browser’s watchlist</button><button disabled={busy} onClick={()=>void run(refresh,'Watchlist refreshed.')}>Refresh watchlist</button><ul className="account-cards">{items.map(i=><li key={i.key}><strong>{i.value.callsign||i.value.registration||i.key}</strong> · {i.value.aircraftType}<div className="membership-actions"><button onClick={()=>void openJourney(i.key)}>Find aircraft</button><button disabled={busy} onClick={()=>void run(async()=>{await deleteAccountItem('watchlist',i);watchlistChanged();},'Removed.')}>Remove watch</button></div></li>)}</ul>{!items.length&&<p>No account watches yet. Star an aircraft or import your browser list.</p>}</>}
 {tab==='Alerts'&&<><h4>Flight-change inbox</h4><p>Departure, arrival, cancellation, gate and terminal changes, and delays of five minutes or more. Only verified checks create alerts. Background test monitoring and push settings are in Premium tools → Monitoring. Real flight-change delivery requires a verified live source; synthetic checks never generate alerts.</p><button disabled={busy||!dashboard.alerts.length} onClick={()=>void run(()=>accountRequest('/api/account/alerts',{throughId:Math.max(...dashboard.alerts.map(a=>a.id))}),'Marked as read.')}>Mark all read</button><button disabled={busy} onClick={()=>void run(refresh,'Inbox refreshed.')}>Refresh inbox</button><ul className="account-cards">{dashboard.alerts.map(a=><li key={a.id}><strong>{a.read?'':'New · '}{a.message}</strong><small>{utc(a.created)}</small></li>)}</ul>{!dashboard.alerts.length&&<p>No verified alerts yet. Test flight details never generate alerts for your real journeys.</p>}<details><summary>Preview alert types (synthetic)</summary><ul><li>DEMO101 · Departure reported</li><li>DEMO101 · Arrival gate changed: A2 → A8</li><li>DEMO101 · Arrival estimate delayed by 15 minutes</li><li>DEMO101 · Flight cancelled</li></ul></details></>}
 {tab==='Viewing setups'&&<><h4>Your favourite viewing setups</h4><p>Save map settings, flight-camera preferences, camera bookmarks, favourite airports and cabin audio. Up to 10 setups, 16 KB each. Restoring reloads this page; save any active recording first.</p><form className="account-form" onSubmit={e=>{e.preventDefault();void run(()=>saveAccountItem('views',crypto.randomUUID(),{name,settings:captureViewSettings()}));setName('');}}><label>Setup name<input required value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button disabled={busy||!name.trim()}>Save current setup</button></form><ul className="account-cards">{items.map(i=><li key={i.key}><strong>{i.value.name}</strong><div className="membership-actions"><button disabled={busy} onClick={()=>void run(async()=>restoreViewSettings(i.value.settings))}>Restore &amp; reload</button><button disabled={busy} onClick={()=>void run(()=>saveAccountItem('views',i.key,{name:i.value.name,settings:captureViewSettings()},i.revision))}>Update from this device</button><button disabled={busy} onClick={()=>remove(i)}>Delete setup</button></div></li>)}</ul></>}
 {tab==='Replays'&&<><h4>Recordings &amp; legacy cloud copies</h4><p>New recordings stay in this browser: use Explore tools → Sessions to record, import, replay and export. Existing cloud copies below remain available to download, replay or delete.</p><div className="account-form"><label>Replay airport<input list="account-airports" maxLength={4} value={replayAirport} onChange={e=>setReplayAirport(e.target.value.toUpperCase())}/></label><label>Replay radius<select value={replayRadius} onChange={e=>setReplayRadius(Number(e.target.value))}>{[5,10,25,50].map(n=><option key={n} value={n}>{n} nm</option>)}</select></label><label>Airport traffic filter<select value={replayFilter} onChange={e=>setReplayFilter(e.target.value as AirportReplayFilter)}><option value="all">All recorded traffic</option><option value="approaching">Approaching (inferred)</option><option value="departing">Moving away (inferred)</option><option value="ground">Reported ground</option></select></label></div><ul className="account-cards">{items.map(i=><li key={i.key}><strong>{i.name}</strong><small>{utc(i.updated)} · {Math.round((i.bytes??0)/1024)} KB</small><div className="membership-actions"><button disabled={busy} onClick={()=>void run(async()=>{const r=await getAccountItem<Recording>('recordings',i.key);window.dispatchEvent(new CustomEvent('skyward-cloud-replay',{detail:parseRecording(r.value)}));document.querySelector<HTMLDialogElement>('.upgrade-dialog')?.close();},'Replay opened.')}>Replay recording</button><button disabled={busy} onClick={()=>void run(async()=>{const r=await getAccountItem<Recording>('recordings',i.key),filtered=airportReplay(parseRecording(r.value),replayAirport,replayRadius,replayFilter);if(!filtered.tracks.length)throw Error('No recorded aircraft match this airport filter.');window.dispatchEvent(new CustomEvent('skyward-cloud-replay',{detail:filtered}));document.querySelector<HTMLDialogElement>('.upgrade-dialog')?.close();},'Airport replay opened.')}>Replay airport traffic</button><button disabled={busy} onClick={()=>void run(async()=>{const r=await getAccountItem('recordings',i.key);downloadText('skyward-recording.json',JSON.stringify(r.value));},'Downloaded.')}>Download recording</button><button disabled={busy} onClick={()=>remove(i)}>Delete recording</button></div></li>)}</ul>{!items.length&&<p>No legacy cloud recordings.</p>}</>}
 {tab==='Logbook'&&<><h4>Personal flight logbook</h4><p>See your globe, aircraft collection and annual recap in Premium tools → Passport.</p><p>Manually recorded trips, not verified travel history. Up to 100 entries.</p><div className="logbook-summary"><strong>{logs.length} {logs.length===1?'flight':'flights'}</strong><strong>{visited.size} airports</strong><strong>{new Set(logs.map(l=>l.aircraftType).filter(Boolean)).size} aircraft types</strong><strong>{Math.round(km).toLocaleString()} km</strong></div><small>Distance is the great-circle distance between airport centres, not actual flown distance.</small><form className="account-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);void run(async()=>{await saveAccountItem('logbook',crypto.randomUUID(),{date:d.get('date'),from:d.get('from'),to:d.get('to'),callsign:d.get('callsign'),aircraftType:d.get('aircraftType'),registration:d.get('registration'),durationMinutes:Number(d.get('duration')),notes:d.get('notes'),experience:d.get('experience')});form.reset();});}}>
 <label>Experience<select aria-label="Experience" name="experience"><option value="flown">I flew this flight</option><option value="watched">I watched this flight</option></select></label><label>Date<input name="date" type="date" required defaultValue={today}/></label><label>From<input name="from" list="account-airports" maxLength={4} required/></label><label>To<input name="to" list="account-airports" maxLength={4} required/></label><label>Flight<input name="callsign" maxLength={16}/></label><label>Aircraft type<input name="aircraftType" placeholder="B738" maxLength={20}/></label><label>Registration<input name="registration" maxLength={32}/></label><label>Duration (minutes)<input name="duration" type="number" min="0" max="1500" defaultValue="0"/></label><label>Notes<textarea name="notes" maxLength={500}/></label><button disabled={busy}>Add to logbook</button></form><button disabled={!items.length} onClick={()=>downloadText('skyward-logbook.json',JSON.stringify(logs,null,2))}>Export logbook</button><ul className="account-cards">{items.map(i=><li key={i.key}><strong>{i.value.from} → {i.value.to}</strong><p>{i.value.date} · {i.value.callsign||'Flight not entered'} · {i.value.aircraftType||'Type not entered'} · {i.value.durationMinutes} min</p><p>{i.value.notes}</p><button disabled={busy} onClick={()=>remove(i)}>Delete logbook entry</button></li>)}</ul></>}
 {tab==='Simulator'&&<><h4>Airport simulator &amp; saved progress</h4><p>Play the starter career, Dulles operations and sandbox scenarios. Compact progress summaries travel with your account (5 slots, 4 KB each). Full career backups stay on your device; export a backup to resume the exact game elsewhere. Existing full cloud saves remain downloadable.</p><div className="membership-actions"><a className="primary-button" href="/airport-simulation/">Open airport simulator</a><a className="primary-button" href="/flight-simulator/">Fly an aircraft</a></div><p>Flight simulator: choose Easy or Advanced, fly between mapped airports, and save results in Premium tools → Career.</p><label>Save a progress summary from a backup<input disabled={busy} type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(()=>upload(file,'simulator'));}}/></label><ul className="account-cards">{items.map(i=><li key={i.key}><strong>{i.name}</strong><small>{utc(i.updated)}</small><div className="membership-actions">{i.value?.kind==='career-progress'?<span>Day {i.value.day} · {i.value.airport_name} · progress summary, not a resumable backup</span>:<a href={`/airport-simulation/?save=${encodeURIComponent(i.key)}`}>Resume legacy career</a>}<button disabled={busy} onClick={()=>void run(async()=>downloadText('skyward-career.json',JSON.stringify((await getAccountItem('simulator',i.key)).value)),'Downloaded.')}>{i.value?.kind==='career-progress'?'Download summary':'Download backup'}</button><button disabled={busy} onClick={()=>remove(i)}>Delete cloud save</button></div></li>)}</ul></>}
 </>}
 <datalist id="account-airports">{Object.entries(AIRPORTS).map(([id,a])=><option key={id} value={id}>{a.city} · {a.name}</option>)}</datalist>
 </section>;
}
