import {useCallback,useEffect,useState} from 'react';
import {accountRequest,type Account} from '../lib/membership';
import {PremiumPreview} from './PremiumPreview';
type Trip={key:string;callsign:string;hex:string;date:string;from?:string;to?:string;details?:any};
type Home={preferences:{intent:string;airports:string[];types:string[];onboarded:boolean};family:{key:string;value:{label:string;journeyKey:string}}[];feed:{hex:string;callsign:string;aircraftType:string;observedAt:number;near:string[];favorite:boolean}[];checkedAt:number;usage:{monitors:number;monitorLimit:number;backgroundChecks:number;backgroundLimit:number;spotterRules:number;spotterLimit:number;journeys:number;journeyLimit:number;resetAt:number}};
export function AccountHome({account,dashboard,openJourney,navigate}:{account:Account;dashboard:{journeys:Trip[];counts:{kind:string;count:number}[]};openJourney:(hex:string)=>Promise<void>;navigate:(tab:'Travel'|'Premium tools'|'Watchlist')=>void}){
 const [home,setHome]=useState<Home|null>(null),[message,setMessage]=useState(''),[intent,setIntent]=useState('trip'),[airports,setAirports]=useState(''),[types,setTypes]=useState(''),[busy,setBusy]=useState(false),[usage,setUsage]=useState(account.usage);
 const paid=!!account.user?.premium,load=useCallback(async()=>{if(!paid)return;const data=await accountRequest<Home>('/api/premium/home');setUsage((await accountRequest<Account>('/api/account')).usage);setHome(data);setIntent(data.preferences.intent);setAirports(data.preferences.airports.join(', '));setTypes(data.preferences.types.join(', '));},[paid]);
 useEffect(()=>{let alive=true;if(paid)void Promise.all([accountRequest<Home>('/api/premium/home'),accountRequest<Account>('/api/account')]).then(([data,current])=>{if(alive){setUsage(current.usage);}if(alive){setHome(data);setIntent(data.preferences.intent);setAirports(data.preferences.airports.join(', '));setTypes(data.preferences.types.join(', '));}}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[paid]);
 const today=new Date().toISOString().slice(0,10),next=dashboard.journeys.filter(j=>j.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0];
 const watch=(j:Trip)=>void openJourney(j.details?.mode==='live'?j.details.flight?.hex||j.hex:j.hex).catch(e=>setMessage(e.message));
 return <section className="account-home"><div className="account-section-heading"><h3>My next flight</h3><button disabled={busy||!paid} onClick={()=>void load().catch(e=>setMessage(e.message))}>Refresh home</button></div>
 {next?<article className="next-flight"><span>{next.date} · departure date UTC</span><h2>{next.from||'Origin unknown'} → {next.to||'Destination unknown'}</h2><strong>{next.callsign}</strong><p>{next.details?.mode==='live'?next.details.flight?.status||'Status unavailable':'Awaiting a verified flight check'}</p>{next.details?.mode==='live'&&<small>Checked {new Date(next.details.fetchedAt).toLocaleString()}</small>}<div className="membership-actions"><button disabled={!next.hex&&!next.details?.flight?.hex} onClick={()=>watch(next)}>Watch aircraft in 3D</button><button onClick={()=>navigate('Travel')}>Manage journey</button></div><small>Aircraft view uses its latest received position; confirm that it is still operating this journey.</small></article>:<article className="next-flight"><h4>Your next journey starts here</h4><p>Add a flight and departure date to keep its status, route and watch link together.</p><button onClick={()=>navigate('Travel')}>Add my next flight</button></article>}
 <details open={!home?.preferences.onboarded}><summary>Make Skyward yours</summary><p>Choose what you want to do first.</p><div className="account-intents">{[['trip','Track my trip'],['family','Watch family arrive'],['explore','Explore aviation']].map(([key,label])=><button key={key} aria-pressed={intent===key} onClick={()=>setIntent(key)}>{label}</button>)}</div><p>{intent==='trip'?'Save a flight callsign and UTC date in Travel. You can also import a calendar.':intent==='family'?'Save their journey in Travel, then add a private label in Premium tools → Family.':'Choose airports and aircraft types below to find interesting received aircraft.'}</p><form className="account-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await accountRequest('/api/premium/preferences',{intent,airports:airports.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean),types:types.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean)});await load();setMessage('Preferences saved across your devices.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label>Favourite airports (comma separated)<input value={airports} maxLength={70} placeholder="IST, IAD" onChange={e=>setAirports(e.target.value)}/></label><label>Favourite aircraft types (comma separated)<input value={types} maxLength={90} placeholder="A359, B789" onChange={e=>setTypes(e.target.value)}/></label><button disabled={!paid||busy}>Save preferences · Premium</button><button type="button" onClick={()=>navigate(intent==='explore'?'Watchlist':'Travel')}>Continue to {intent==='explore'?'watchlist':'journeys'}</button></form></details>
 {!!home?.family.length&&<section><h4>Family flights</h4><ul className="account-cards">{home.family.map(f=>{const j=dashboard.journeys.find(j=>j.key===f.value.journeyKey);return <li key={f.key}><strong>{f.value.label}</strong><p>{j?`${j.callsign} · ${j.from||'?'} → ${j.to||'?'} · ${j.date}`:'Journey removed'}</p>{j&&<button disabled={!j.hex&&!j.details?.flight?.hex} onClick={()=>watch(j)}>Watch aircraft</button>}</li>;})}</ul></section>}
 <section><h4>For your aviation interests</h4><p>Recent aircraft already received near your saved airports (50 nm), or matching favourite types. No additional paid tracking requests. Empty results do not mean empty airspace.</p><ul className="account-cards">{home?.feed.map(a=><li key={a.hex}><strong>{a.callsign||a.hex} · {a.aircraftType||'Type unknown'}</strong><p>{a.near.length?'Near '+a.near.join(', '):'Favourite aircraft type'} · observed {new Date(a.observedAt).toLocaleTimeString()}</p><button onClick={()=>void openJourney(a.hex).catch(e=>setMessage(e.message))}>Watch in 3D</button></li>)}</ul>{!home?.feed.length&&<p>No recent matching observations. Save your interests, explore that area, then refresh.</p>}</section>
 {home&&<section aria-label="Premium usage"><h4>Your Premium allowance</h4><div className="account-usage-grid">{[[usage?.requests||0,usage?.limit||0,'Detail requests'],[home.usage.backgroundChecks,home.usage.backgroundLimit,'Background check attempts'],[home.usage.monitors,home.usage.monitorLimit,'Active monitors'],[home.usage.spotterRules,home.usage.spotterLimit,'Spotter rules'],[home.usage.journeys,home.usage.journeyLimit,'Saved journeys']].map(([used,limit,label])=><div key={label}><strong>{used} / {limit}</strong><span>{label}</span></div>)}</div><p>Monthly counters reset {new Date(home.usage.resetAt).toLocaleDateString(undefined,{timeZone:'UTC'})} at 00:00 UTC. Saved items do not reset. Background checks also consume detail allowance when a provider request is made.</p><p>{dashboard.counts.map(c=>`${c.count} ${c.kind}`).join(' · ')||'No library items yet.'} · Recordings and video exports stay on your device.</p><small>{account.mode==='test'?'Test mode: no live paid requests or charges.':'Live details remain subject to coverage and shared service limits.'}</small><button onClick={()=>navigate('Premium tools')}>Manage monitoring and alerts</button></section>}
 {!paid&&<PremiumPreview/>}{message&&<p role="status">{message}</p>}
 </section>;
}
