import {useState} from 'react';
import {validateCatalog,validateCatalogTransition,type Catalog,type Evidence,type Identity} from '../lib/airframeCatalog';
type Kind='aircraft'|'entities'|'associations';
const blankEvidence:Evidence={sourceUrl:'',sourceName:'',verifiedAt:new Date().toISOString().slice(0,10),confidence:'LOW'};
function EvidenceFields({prefix,value=blankEvidence}:{prefix:string;value?:Evidence}){return <fieldset><legend>Source evidence</legend><label>Source name<input name={prefix+'Name'} defaultValue={value.sourceName} required maxLength={160}/></label><label>Source URL<input type="url" name={prefix+'Url'} defaultValue={value.sourceUrl} required pattern="https://.*" maxLength={999}/></label><label>Verified date<input type="date" name={prefix+'Date'} defaultValue={value.verifiedAt} required/></label><label>Confidence<select aria-label="Confidence" name={prefix+'Confidence'} defaultValue={value.confidence}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label></fieldset>;}
function History({name,initial}:{name:string;initial:Identity[]}){const [rows,setRows]=useState(initial);return <fieldset><legend>{name==='reg'?'Registration history':'ICAO address history'}</legend><input type="hidden" name={name+'Count'} value={rows.length}/>{rows.map((r,i)=><details key={i} open><summary>{r.value||'New identifier'}</summary><label>{name==='reg'?'Registration':'ICAO hex'}<input name={`${name}${i}Value`} defaultValue={r.value} required maxLength={12}/></label><label>Valid from (blank if unknown)<input type="date" name={`${name}${i}From`} defaultValue={r.validFrom??''}/></label><label>Valid to, exclusive (blank if unknown)<input type="date" name={`${name}${i}To`} defaultValue={r.validTo??''}/></label><EvidenceFields prefix={`${name}${i}`} value={r}/></details>)}<button type="button" disabled={rows.length>=30} onClick={()=>setRows([...rows,{...blankEvidence,value:'',validFrom:null,validTo:null}])}>Add {name==='reg'?'registration':'ICAO identity'}</button></fieldset>;}
export default function AirframeEditor({catalog,onSave}:{catalog:Catalog;onSave:(c:Catalog)=>void}){
 const [kind,setKind]=useState<Kind>('aircraft'),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);const current=catalog[kind].find(r=>r.id===selected);
 const aircraft=kind==='aircraft'?catalog.aircraft.find(a=>a.id===selected):undefined,entity=kind==='entities'?catalog.entities.find(e=>e.id===selected):undefined,association=kind==='associations'?catalog.associations.find(a=>a.id===selected):undefined;
 return <section className="airframe-card"><h2>Catalog editor</h2><div className="airframe-actions">{(['aircraft','entities','associations'] as Kind[]).map(k=><button type="button" key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setSelected('');setMessage('');}}>{k==='aircraft'?'Aircraft':k==='entities'?'Entities':'Associations'}</button>)}</div><label>Record<select aria-label="Record" value={selected} onChange={e=>{setSelected(e.target.value);setMessage('');}}><option value="">Create new record</option>{catalog[kind].map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label>
 <form key={kind+selected+revision} onSubmit={e=>{e.preventDefault();try{const d=new FormData(e.currentTarget),v=(k:string)=>String(d.get(k)??'').trim(),ev=(p:string):Evidence=>({sourceName:v(p+'Name'),sourceUrl:v(p+'Url'),verifiedAt:v(p+'Date'),confidence:v(p+'Confidence') as Evidence['confidence']}),history=(p:string,prior:Identity[])=>Array.from({length:Number(v(p+'Count'))},(_,i)=>({...prior[i],...ev(p+i),value:p==='reg'?v(p+i+'Value').toUpperCase():v(p+i+'Value').toLowerCase(),validFrom:v(p+i+'From')||null,validTo:v(p+i+'To')||null}));
 let record:Record<string,unknown>={...current,id:v('id')};
 if(kind==='aircraft')record={...record,manufacturer:v('manufacturer'),model:v('model'),category:v('category'),variant:v('variant')||undefined,serialNumber:v('serialNumber')||undefined,serialSeries:v('serialSeries')||undefined,operator:v('operator')||undefined,yearBuilt:v('yearBuilt')?Number(v('yearBuilt')):undefined,retired:d.has('retired'),sources:[ev('source'),...(aircraft?.sources.slice(1)??[])],registrations:history('reg',aircraft?.registrations??[]),icaoIdentities:history('hex',aircraft?.icaoIdentities??[])};
 if(kind==='entities')record={...record,slug:v('slug'),displayName:v('displayName'),description:v('description'),entityType:v('entityType'),archived:d.has('archived')};
 if(kind==='associations')record={...record,...ev('source'),aircraftId:v('aircraftId'),entityId:v('entityId'),associationType:v('associationType'),validFrom:v('from')||null,validTo:v('to')||null,reviewed:d.has('reviewed'),archived:d.has('archived'),notes:v('notes')||undefined,context:v('context')||undefined};
 if(!selected&&catalog[kind].some(r=>r.id===record.id))throw Error('That ID already exists. Select it to edit.');const next=validateCatalog({...catalog,[kind]:[...catalog[kind].filter(r=>r.id!==selected),record]});validateCatalogTransition(catalog,next);onSave(next);setSelected(record.id as string);setRevision(n=>n+1);setMessage('Saved to local draft. Export and publish after source review.');}catch(err){setMessage(err instanceof Error?err.message:'Invalid record.');}}}>
 <label>Permanent record ID<input name="id" required pattern="[a-z][a-z0-9-]{1,63}" maxLength={64} defaultValue={current?.id} readOnly={!!current}/></label>
 {kind==='aircraft'&&<><div className="airframe-editor-grid">{(['manufacturer','model','variant','category','serialNumber','serialSeries','operator','yearBuilt'] as const).map(k=><label key={k}>{({manufacturer:'Manufacturer',model:'Model',variant:'Variant',category:'Category',serialNumber:'Serial number',serialSeries:'Serial series',operator:'Operator',yearBuilt:'Year built'})[k]}<input name={k} required={['manufacturer','model','category'].includes(k)} defaultValue={aircraft?.[k]} maxLength={160} type={k==='yearBuilt'?'number':'text'}/></label>)}</div><label className="airframe-check"><input type="checkbox" name="retired" defaultChecked={aircraft?.retired}/>Retired aircraft</label><EvidenceFields prefix="source" value={aircraft?.sources[0]}/><History name="reg" initial={aircraft?.registrations??[]}/><History name="hex" initial={aircraft?.icaoIdentities??[]}/></>}
 {kind==='entities'&&<><label>Display name<input name="displayName" required defaultValue={entity?.displayName} maxLength={160}/></label><label>URL slug<input name="slug" required defaultValue={entity?.slug} pattern="[a-z][a-z0-9-]{1,63}"/></label><label>Entity type<select name="entityType" defaultValue={entity?.entityType??'ORGANIZATION'}>{['ORGANIZATION','COMPANY','SPORTS_TEAM','HISTORIC','OTHER','PERSON'].map(t=><option key={t}>{t}</option>)}</select></label><p>Person entities are retained internally only and cannot publish live tracking associations.</p><label>Description<textarea name="description" required maxLength={1000} defaultValue={entity?.description}/></label><label className="airframe-check"><input type="checkbox" name="archived" defaultChecked={entity?.archived}/>Archive entity</label></>}
 {kind==='associations'&&<><label>Aircraft<select aria-label="Aircraft" name="aircraftId" required defaultValue={association?.aircraftId??''}><option value="">Choose aircraft</option>{catalog.aircraft.filter(a=>!a.mergedInto).map(a=><option key={a.id}>{a.id}</option>)}</select></label><label>Entity<select aria-label="Entity" name="entityId" required defaultValue={association?.entityId??''}><option value="">Choose entity</option>{catalog.entities.map(a=><option key={a.id}>{a.id}</option>)}</select></label><label>Association type<select name="associationType" defaultValue={association?.associationType??'PUBLICLY_ASSOCIATED'}>{['REGISTERED_OWNER','OPERATOR','PUBLICLY_ASSOCIATED','FORMERLY_ASSOCIATED','TEAM_AIRCRAFT','CORPORATE_AIRCRAFT'].map(t=><option key={t}>{t}</option>)}</select></label><label>Valid from<input type="date" name="from" defaultValue={association?.validFrom??''}/></label><label>Valid to<input type="date" name="to" defaultValue={association?.validTo??''}/></label><EvidenceFields prefix="source" value={association}/><label className="airframe-check"><input type="checkbox" name="reviewed" defaultChecked={association?.reviewed}/>I checked the source and it supports this association</label><label className="airframe-check"><input type="checkbox" name="archived" defaultChecked={association?.archived}/>Withdraw association</label><label>Public association context<textarea name="context" maxLength={500} defaultValue={association?.context}/></label><label>Internal notes<textarea name="notes" maxLength={1000} defaultValue={association?.notes}/></label></>}
 <button type="submit">Save record to draft</button></form><p role="status">{message}</p></section>;
}
