import {useMemo,useState} from 'react';
import {airportTimeline,airportGroundActivity} from '../lib/airportTimeline';
import type {Aircraft,TrailPoint} from '../types';
export function AirportTimeline({rows,histories,center,now,select}:{rows:Aircraft[];histories:Map<string,TrailPoint[]>;center:{lat:number;lon:number};now:number;select:(a:Aircraft)=>void}){
 const [filter,setFilter]=useState<'all'|'arrival'|'departure'|'ground'>('all');
 const ground=airportGroundActivity(rows,center,now);
 const timeBucket=Math.floor(now/10000);
 const events=useMemo(()=>airportTimeline(rows,histories,center,now),[rows,histories,center,timeBucket]),shown=events.filter(e=>filter==='all'||e.kind===filter);
 return <details className="identity-details airport-timeline"><summary>Observed activity timeline · {events.length} transitions</summary><p>Last 30 minutes received in this session. Each transition needs two ground and two airborne fixes near this airport. These support a likely arrival or departure, not an airport-confirmed event. Times show the interval between reported fixes.</p><div className="traffic-filter" aria-label="Timeline filter">{(['all','arrival','departure','ground'] as const).map(k=><button key={k} aria-pressed={filter===k} onClick={()=>setFilter(k)}>{k==='all'?'All transitions':k==='arrival'?'Likely arrivals':k==='departure'?'Likely departures':'Ground activity'}</button>)}</div><ol>{shown.map(e=><li key={e.id}><button onClick={()=>select(e.aircraft)}><strong>{e.label}</strong><span>{e.kind==='arrival'?'Airborne → ground':'Ground → airborne'}</span><time dateTime={new Date(e.time).toISOString()}>{new Date(e.fromTime).toISOString().slice(11,19)}–{new Date(e.time).toISOString().slice(11,19)} UTC</time></button></li>)}</ol>{(filter==='all'||filter==='ground')&&<><h4>Latest reported ground activity</h4><ul>{ground.map(a=><li key={a.hex}><button onClick={()=>select(a)}>{a.callsign||a.hex} · {a.groundSpeed===null?'Speed unavailable':`${Math.round(a.groundSpeed)} kt reported`} · {new Date(a.observedAt!).toISOString().slice(11,19)} UTC</button></li>)}</ul>{!ground.length&&<p>No recent ground fixes received near this airport. Gate occupancy is not inferred.</p>}</>}{!shown.length&&filter!=='ground'&&<p>No supported transitions yet. Keep this airport open to collect observations. Missing coverage does not mean no flights occurred.</p>}</details>;
}
