import {readMusicPreferences} from '../lib/musicPreferences';
import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import {onAudioMix,speechFocusActive} from '../lib/audioMix';
type Track={id:string;title:string;url:string};
export function AurowallPlayer({suspended=false}:{suspended?:boolean}){
 const [saved]=useState(readMusicPreferences),[favorites,setFavorites]=useState(saved.favorites),[favoritesOnly,setFavoritesOnly]=useState(false);
 const audio=useRef<HTMLAudioElement>(null),[tracks,setTracks]=useState<Track[]>([]),[selected,setSelected]=useState(saved.selected),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[loaded,setLoaded]=useState(false),[playing,setPlaying]=useState(false),[volume,setVolume]=useState(saved.volume),[loop,setLoop]=useState(saved.loop),[open,setOpen]=useState(false);
 const request=useRef<AbortController|null>(null),mounted=useRef(true),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{mounted.current=true;const el=audio.current;return()=>{mounted.current=false;request.current?.abort();if(el){el.pause();el.removeAttribute('src');el.load();}};},[]);
 useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 const load=async()=>{if(request.current)return;const controller=new AbortController();request.current=controller;setLoading(true);setStatus('');try{const r=await fetch('/api/aurowall',{signal:controller.signal});if(!r.ok)throw Error();const d=await r.json();if(!mounted.current)return;const list=(Array.isArray(d.tracks)?d.tracks:[]).filter((t:Track)=>typeof t.id==='string'&&!/(?:^|\/)(?:prayer|quran)(?:\/|\.|$)/i.test(t.id)&&typeof t.title==='string'&&typeof t.url==='string'&&t.url.startsWith('https://'));setTracks(list);setLoaded(true);if(!list.length)setStatus('The music library is not available yet.');else if(d.stale)setStatus('Showing the last available music library.');else if(d.truncated)setStatus('Showing the first available collections.');}catch{if(mounted.current&&!controller.signal.aborted)setStatus('Could not load music. Try again.');}finally{request.current=null;if(mounted.current)setLoading(false);}};
 useEffect(()=>{const update=()=>{if(audio.current){audio.current.volume=volume*(speechFocusActive()?.28:1);}};update();return onAudioMix(update);},[volume]);
 useEffect(()=>{const pause=()=>{if(document.hidden||suspended)audio.current?.pause();};pause();document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[suspended]);
 useEffect(()=>{try{localStorage.setItem('skyward.music.v1',JSON.stringify({selected,volume,loop,favorites}));}catch{}},[selected,volume,loop,favorites]);
 const visibleTracks=tracks.filter(t=>!favoritesOnly||favorites.includes(t.id)).sort((a,b)=>Number(favorites.includes(b.id))-Number(favorites.includes(a.id))||a.title.localeCompare(b.title));
 const track=tracks.find(t=>t.id===selected);
 const controls=<section className="aurowall-player"><h2>Music & sounds</h2><a href="https://aurowall.com" target="_blank" rel="noopener noreferrer">Music & sounds by Aurowall ↗</a>{loading?<p role="status">Loading music library…</p>:<><label className="aurowall-loop"><input type="checkbox" checked={favoritesOnly} onChange={e=>setFavoritesOnly(e.target.checked)}/>Favorites only</label>{favoritesOnly&&!visibleTracks.length&&<p>No favorites yet. Turn off this filter and favorite a track.</p>}<label>Choose music or a sound<select aria-label="Aurowall music or sound" value={selected} onChange={e=>{audio.current?.pause();setSelected(e.target.value);setStatus('');}}><option value="">Select a track</option>{track&&favoritesOnly&&!favorites.includes(track.id)&&<option value={track.id}>{track.title} · selected</option>}{visibleTracks.map(t=><option key={t.id} value={t.id}>{favorites.includes(t.id)?'★ ':''}{t.title}</option>)}</select></label><p className="music-now-playing" aria-live="polite">{track?`${playing?'Playing':'Selected'} · ${track.title}`:'Choose a track to start listening.'}</p><div className="flight-buttons"><button aria-label="Favorite selected track" aria-pressed={!!track&&favorites.includes(track.id)} disabled={!track||(!favorites.includes(track.id)&&favorites.length>=100)} onClick={()=>{if(track)setFavorites(rows=>rows.includes(track.id)?rows.filter(id=>id!==track.id):[...rows,track.id]);}}>{track&&favorites.includes(track.id)?'★ Favorited':'☆ Favorite'}</button><button disabled={!track||suspended} onClick={()=>{const el=audio.current;if(!el)return;if(!el.paused){el.pause();return;}setStatus('');void el.play().catch(()=>{if(mounted.current)setStatus('Audio could not play. Press Play to retry or choose another track.');});}}>{playing?'Pause music':'Play music'}</button><button disabled={loading} onClick={()=>void load()}>Reload library</button></div><label>Music volume<input aria-label="Aurowall music volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><label className="aurowall-loop"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/>Loop track</label></>}{status&&<p role="status">{status}</p>}</section>;
 return <><audio ref={audio} src={track?.url} preload="none" loop={loop} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setStatus('This track is unavailable. Choose another or retry.');}}/><button className="music-launcher" aria-label="Music" aria-haspopup="dialog" aria-expanded={open} onClick={()=>{setOpen(true);if(!loaded&&!loading)void load();}}><span aria-hidden="true">♫</span> Music{playing?' •':''}</button>{playing&&<button className="music-pause" aria-label="Pause music playback" title={`Pause ${track?.title??'music'}`} onClick={()=>audio.current?.pause()}>Ⅱ <span>{track?.title}</span></button>}{open&&createPortal(<dialog ref={dialog} className="data-dialog aurowall-dialog" aria-label="Music and sounds" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}>{controls}<button className="aurowall-close" onClick={()=>setOpen(false)}>Close music</button></dialog>,document.body)}</>;
}
