import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import {onAudioMix,speechFocusActive} from '../lib/audioMix';
type Track={id:string;title:string;url:string};
export function AurowallPlayer({suspended,cockpit=false}:{suspended:boolean;cockpit?:boolean}){
 const audio=useRef<HTMLAudioElement>(null),[tracks,setTracks]=useState<Track[]>([]),[selected,setSelected]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[loaded,setLoaded]=useState(false),[playing,setPlaying]=useState(false),[volume,setVolume]=useState(.4),[loop,setLoop]=useState(true),[host,setHost]=useState<Element|null>(null);
 const request=useRef<AbortController|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;const el=audio.current;return()=>{mounted.current=false;request.current?.abort();if(el){el.pause();el.removeAttribute('src');el.load();}};},[]);
 useEffect(()=>setHost(cockpit?document.querySelector('.cockpit-mode'):null),[cockpit]);
 const load=async()=>{if(request.current)return;const controller=new AbortController();request.current=controller;setLoading(true);setStatus('');try{const r=await fetch('/api/aurowall',{signal:controller.signal});if(!r.ok)throw Error();const d=await r.json();if(!mounted.current)return;const list=(Array.isArray(d.tracks)?d.tracks:[]).filter((t:Track)=>typeof t.id==='string'&&typeof t.title==='string'&&typeof t.url==='string'&&t.url.startsWith('https://'));setTracks(list);setLoaded(true);if(!list.length)setStatus('The music library is not available yet.');else if(d.stale)setStatus('Showing the last available music library.');else if(d.truncated)setStatus('Showing the first available collections.');}catch{if(mounted.current&&!controller.signal.aborted)setStatus('Could not load music. Try again.');}finally{request.current=null;if(mounted.current)setLoading(false);}};
 useEffect(()=>{const update=()=>{if(audio.current){audio.current.volume=volume*(speechFocusActive()?.28:1);}};update();return onAudioMix(update);},[volume]);
 useEffect(()=>{const pause=()=>{if(document.hidden||suspended)audio.current?.pause();};pause();document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[suspended]);
 const track=tracks.find(t=>t.id===selected);
 const controls=<details className="aurowall-player" onToggle={e=>{if(e.currentTarget.open&&!loaded&&!loading)void load();}}><summary>Music & sounds · Aurowall{playing?' · Playing':''}</summary><a href="https://aurowall.com" target="_blank" rel="noopener noreferrer">Music & sounds by Aurowall ↗</a>{loading?<p role="status">Loading music library…</p>:<><label>Choose music or a sound<select aria-label="Aurowall music or sound" value={selected} onChange={e=>{audio.current?.pause();setSelected(e.target.value);setStatus('');}}><option value="">Select a track</option>{tracks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><div className="flight-buttons"><button disabled={!track||suspended} onClick={()=>{const el=audio.current;if(!el)return;if(!el.paused){el.pause();return;}setStatus('');void el.play().catch(()=>{if(mounted.current)setStatus('Audio could not play. Press Play to retry or choose another track.');});}}>{playing?'Pause music':'Play music'}</button><button disabled={loading} onClick={()=>void load()}>Reload library</button></div><label>Music volume<input aria-label="Aurowall music volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><label className="aurowall-loop"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/>Loop track</label></>}{status&&<p role="status">{status}</p>}</details>;
 return <><audio ref={audio} src={track?.url} preload="none" loop={loop} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setStatus('This track is unavailable. Choose another or retry.');}}/>{cockpit&&host?createPortal(controls,host):controls}</>;
}
