import {travelMetric} from '../lib/travelMetrics';
import {TravelerSharing} from './TravelerSharing';
import {useEffect,useRef,useState} from 'react';
import {accountRequest} from '../lib/membership';
import {listAccountItems,saveAccountItem,deleteAccountItem,type LibraryItem} from '../lib/accountLibrary';
import {boardingDate,type BoardingPassDraft} from '../lib/boardingPass';
type Pass=Omit<BoardingPassDraft,'dayOfYear'>;
type Journey={key:string;callsign:string;date:string;hex:string;from?:string;to?:string};
const empty=():Pass=>({displayName:'',flight:'',from:'',to:'',seat:'',date:new Date().toISOString().slice(0,10),callsign:'',journeyKey:''});
export function BoardingPasses({paid,openJourney}:{paid:boolean;openJourney:(hex:string)=>Promise<void>}){
 const [selectedJourney,setSelectedJourney]=useState('');
 const [items,setItems]=useState<LibraryItem<Pass>[]>([]),[journeys,setJourneys]=useState<Journey[]>([]),[drafts,setDrafts]=useState<BoardingPassDraft[]>([]),[value,setValue]=useState<Pass>(empty),[editing,setEditing]=useState<LibraryItem<Pass>|null>(null),[year,setYear]=useState(new Date().getUTCFullYear()),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[confirmed,setConfirmed]=useState(false),[scanned,setScanned]=useState(false);
 const video=useRef<HTMLVideoElement>(null),controls=useRef<{stop:()=>void}|null>(null),abort=useRef<AbortController|null>(null),alive=useRef(true),pending=useRef(false),cameraGeneration=useRef(0);
 function stopCamera(){cameraGeneration.current++;controls.current?.stop();controls.current=null;setCamera(false);}
 useEffect(()=>{travelMetric('trip_start');alive.current=true;return()=>{alive.current=false;cameraGeneration.current++;controls.current?.stop();abort.current?.abort();};},[]);
 useEffect(()=>{if(!camera)return;const hidden=()=>{if(document.hidden)stopCamera();};document.addEventListener('visibilitychange',hidden);const timer=setTimeout(()=>{stopCamera();setMessage('Camera stopped after one minute. Try a close-up photo or manual entry.');},60000);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',hidden);};},[camera]);
 async function load(){const [p,j]=await Promise.all([listAccountItems<Pass>('boardingpasses'),accountRequest<{journeys:Journey[]}>('/api/journeys')]);if(alive.current){setItems(p.items);setJourneys(j.journeys);}}
 useEffect(()=>{void load().catch(e=>{if(alive.current)setMessage(e.message);});},[paid]);
 function accept(rows:BoardingPassDraft[]){if(!alive.current)return;stopCamera();setDrafts(rows);setValue(rows[0]);setEditing(null);setScanned(true);setConfirmed(false);setMessage(`${rows.length} flight leg${rows.length===1?'':'s'} read locally. Confirm the year, UTC departure date, flight and seat before saving.`);}
 async function scan(files:File[]){if(!paid||pending.current)return;pending.current=true;stopCamera();setBusy(true);setMessage('Reading barcode on this device…');const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),45000);try{const {scanBoardingFile}=await import('../lib/boardingScanner'),rows:BoardingPassDraft[]=[];for(const file of files.slice(0,5)){rows.push(...await scanBoardingFile(file,year,controller.signal));}if(!controller.signal.aborted)accept(rows);}catch(e){if(alive.current)setMessage((e as Error).message);}finally{clearTimeout(timeout);pending.current=false;abort.current=null;if(alive.current)setBusy(false);}}
 // Shared files are handed off by the installed app's service worker in memory, never uploaded.
 useEffect(()=>{const token=new URLSearchParams(location.search).get('boardingShare');if(!paid||!token||!navigator.serviceWorker?.controller)return;const channel=new MessageChannel();channel.port1.onmessage=e=>{channel.port1.close();const files=e.data?.files;if(Array.isArray(files)&&files.length)void scan(files);else setMessage('Shared file expired. Choose the image or PDF again.');const url=new URL(location.href);url.searchParams.delete('boardingShare');history.replaceState(history.state,'',url);};navigator.serviceWorker.controller.postMessage({kind:'CLAIM_BOARDING_SHARE',token},[channel.port2]);return()=>channel.port1.close();},[paid]);
 async function startCamera(){if(!paid||busy||camera)return;setCamera(true);setMessage('Allow camera access and hold the barcode steady.');const generation=++cameraGeneration.current;try{const {startBoardingCamera}=await import('../lib/boardingScanner');if(!alive.current||generation!==cameraGeneration.current)return;const c=await startBoardingCamera(video.current!,year,rows=>{if(alive.current&&generation===cameraGeneration.current)accept(rows);});if(!alive.current||generation!==cameraGeneration.current)c.stop();else controls.current=c;}catch{if(alive.current&&generation===cameraGeneration.current){stopCamera();setMessage('Camera unavailable or permission denied. Upload a boarding-pass image/PDF or enter it manually.');}}}
 const change=(key:keyof Pass,v:string)=>{setValue(old=>({...old,[key]:v}));setConfirmed(false);};
 async function save(){setBusy(true);try{
  // Create/link tracking in this same reviewed flow; never derive an ICAO callsign from a ticket number.
  const linked=journeys.find(j=>j.key===value.journeyKey&&j.date===value.date&&j.from===value.from&&j.to===value.to&&j.callsign===value.callsign);
  let journeyKey=linked?.key||'';
  if(!journeyKey&&value.callsign){await accountRequest('/api/journeys',{callsign:value.callsign,date:value.date,hex:'',from:value.from,to:value.to,alerts:false});journeyKey=`${value.callsign}:unassigned:${value.date}`;}
  await saveAccountItem('boardingpasses',editing?.key||crypto.randomUUID(),{displayName:value.displayName,flight:value.flight,date:value.date,from:value.from,to:value.to,seat:value.seat,callsign:value.callsign,journeyKey},editing?.revision||0);
  travelMetric('trip_saved');await load();setSelectedJourney(journeyKey);const rest=drafts.slice(1);setDrafts(rest);setEditing(null);setValue(rest[0]||empty());setScanned(!!rest.length);setConfirmed(false);
  setMessage(rest.length?'Saved. Review the next flight leg.':journeyKey?'Trip saved privately and tracking linked. Choose your window and who can follow below.':'Trip saved privately. Add a confirmed tracking callsign when ready to follow or share.');
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}

 const matching=journeys.filter(j=>j.date===value.date&&(!j.from||j.from===value.from)&&(!j.to||j.to===value.to));
 return <section className="boarding-passes" aria-label="Boarding passes"><h3>My trips &amp; boarding passes</h3><p>Scan a pass you control or add your own flight details. Only the reviewed display name, flight, airports, date, seat and optional journey link are saved. Scanned names become initials; booking references and original files are discarded.</p>{!paid?<p className="account-lock">Boarding-pass scanning and private trip saving are included with Premium.</p>:<>
 <div className="membership-actions"><button disabled={busy||camera} onClick={()=>void startCamera()}>Scan with camera</button><button disabled={busy} onClick={()=>{stopCamera();setValue(empty());setEditing(null);setDrafts([]);setScanned(false);setConfirmed(false);}}>Add manually</button></div>
 <button disabled={busy} onClick={async()=>{try{if(!navigator.serviceWorker)throw Error('File sharing is not supported here. Use Import instead.');await navigator.serviceWorker.register('/offline-worker.js',{scope:'/'});await navigator.serviceWorker.ready;setMessage('Share support is ready. Install Skyward using your browser menu; supported browsers can then share a boarding-pass image or PDF to Skyward. Otherwise use Import.');}catch(e){setMessage((e as Error).message);}}}>Enable Share to Skyward</button><label>Flight year for scans<input aria-label="Flight year for scans" type="number" min="2000" max="2100" value={year} disabled={busy||camera} onChange={e=>{const y=Number(e.target.value);setYear(y);if(drafts.length){try{const next=drafts.map(d=>({...d,date:boardingDate(d.dayOfYear,y)}));setDrafts(next);setValue(next[0]);setConfirmed(false);}catch(e){setMessage((e as Error).message);}}}}/></label><small>Boarding barcodes usually encode a day of year, not the flight year. Confirm the date below.</small>
 <label>Import boarding-pass photo or PDF<input aria-label="Import boarding pass" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" disabled={busy||camera} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void scan([f]);}}/></label><p>PNG, JPEG, WebP or PDF · up to 10 MB and 10 PDF pages. Camera requires HTTPS or localhost. Installed browsers with file sharing can use “Share → Skyward”; otherwise use Import. No automatic access to Apple or Google Wallet.</p>
 <video ref={video} hidden={!camera} muted playsInline aria-label="Boarding-pass camera"/>{camera&&<button onClick={stopCamera}>Stop camera</button>}{busy&&abort.current&&<button onClick={()=>abort.current?.abort()}>Cancel scan</button>}
 <form className="account-form boarding-pass-form" onSubmit={e=>{e.preventDefault();void save();}}><h4>{editing?'Edit saved trip':scanned?'Review scanned trip':'Enter your trip'}</h4><label>Name or display name<input required maxLength={40} autoComplete="off" value={value.displayName} onChange={e=>change('displayName',e.target.value)} placeholder="S.S. or Serhan"/></label><label>Flight number<input required maxLength={10} value={value.flight} onChange={e=>change('flight',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="TK008"/></label><label>Departure date (UTC; confirm after scan)<input required type="date" value={value.date} onChange={e=>change('date',e.target.value)}/></label>{(['from','to'] as const).map(k=><label key={k}>{k==='from'?'Origin airport':'Destination airport'}<input required pattern="[A-Z]{3}" maxLength={3} list="account-airports" value={value[k]} onChange={e=>change(k,e.target.value.toUpperCase())} placeholder={k==='from'?'IAD':'IST'}/></label>)}<label>Seat (optional)<input maxLength={6} value={value.seat} onChange={e=>change('seat',e.target.value.toUpperCase())} placeholder="14A"/></label><label>Tracking callsign (optional)<input maxLength={10} value={value.callsign} onChange={e=>change('callsign',e.target.value.toUpperCase())} placeholder="THY8"/></label><small>Adding a confirmed callsign links tracking when you save—no separate setup step. Ticket flight numbers and tracking callsigns can differ. Link an existing journey or enter a confirmed ICAO callsign; we do not guess the aircraft.</small><label>Link a saved journey<select aria-label="Link a saved journey" value={value.journeyKey} onChange={e=>{const j=journeys.find(j=>j.key===e.target.value);setValue({...value,journeyKey:j?.key||'',callsign:j?.callsign||value.callsign});setConfirmed(false);}}><option value="">No linked journey</option>{matching.map(j=><option key={j.key} value={j.key}>{j.callsign} · {j.date} · {j.from||'?'} → {j.to||'?'}</option>)}</select></label><label className="boarding-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>I checked these details and want to save them to my private account.</label><button disabled={busy||!confirmed}>{editing?'Update trip':'Save reviewed trip'}</button><button type="button" disabled={busy} onClick={()=>{setDrafts([]);setValue(empty());setEditing(null);setScanned(false);setConfirmed(false);setMessage('Unsaved details discarded.');}}>Discard</button></form>
 </>}<ul className="account-cards">{items.map(item=>{const p=item.value,j=journeys.find(j=>j.key===p.journeyKey);return <li key={item.key}><h4>{p.displayName} — {p.flight}</h4><p>{p.from} → {p.to} · {p.date} · {p.seat?'Seat '+p.seat:'Seat not entered'}</p><small>User-provided trip · not verified boarding or a live passenger manifest</small><div className="membership-actions"><button disabled={busy||!paid} onClick={()=>{setValue(p);setEditing(item);setDrafts([]);setScanned(false);setConfirmed(false);}}>Edit trip</button><button disabled={!j?.hex} onClick={()=>void openJourney(j!.hex).catch(e=>setMessage(e.message))}>Watch linked aircraft</button>{!j&&p.callsign&&<button disabled={busy||!paid} onClick={async()=>{setBusy(true);try{await accountRequest('/api/journeys',{callsign:p.callsign,date:p.date,hex:'',from:p.from,to:p.to,alerts:false});const key=`${p.callsign}:unassigned:${p.date}`;await saveAccountItem('boardingpasses',item.key,{...p,journeyKey:key},item.revision);await load();setMessage('Journey saved and linked. A verified aircraft assignment is still needed before watching.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Create tracking journey</button>}<button disabled={busy} onClick={async()=>{setBusy(true);try{await deleteAccountItem('boardingpasses',item);await load();setMessage('Private trip deleted.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Delete trip</button></div></li>;})}</ul><p>Up to 50 saved trips. Your saved display name and seat stay private. Public journey sharing is a separate, optional step below.</p>
 <TravelerSharing paid={paid} journeys={journeys} selectedJourney={selectedJourney}/>
 {message&&<p role="status">{message}</p>}</section>;
}
