import {useState,useEffect,useRef} from 'react';
import type * as Cesium from 'cesium';
import type {MapPreferences} from '../lib/mapPreferences';
import type {RecoveryPose} from './Globe';
interface Bookmark {id:string;name:string;pose:RecoveryPose;mode:'3D'|'2D';layers:Pick<MapPreferences,'basemap'|'labels'|'structures'|'grid'|'terrain'> & {cityBuildings?:boolean;waterMotion?:boolean};}
const key='skyward.camera-bookmarks.v1';
function read():Bookmark[]{try{const rows=JSON.parse(localStorage.getItem(key)??'[]');return Array.isArray(rows)?rows.filter(b=>b&&typeof b.id==='string'&&typeof b.name==='string'&&b.pose&&['lon','lat','height','heading','pitch','roll'].every(k=>Number.isFinite(b.pose[k]))&&Math.abs(b.pose.lon)<=180&&Math.abs(b.pose.lat)<=90&&b.pose.height>0&&b.pose.height<=100000000&&(b.mode==='3D'||b.mode==='2D')&&b.layers&&['atlas','satellite'].includes(b.layers.basemap)&&['labels','structures','grid','terrain'].every(k=>typeof b.layers[k]==='boolean')).slice(0,20):[];}catch{return [];}}
export function CameraBookmarks({viewer,mode,preferences,restore}:{viewer:Cesium.Viewer|null;mode:'3D'|'2D';preferences:MapPreferences;restore:(b:Bookmark)=>void}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState(read),[name,setName]=useState(''),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 const save=(next:Bookmark[])=>{try{localStorage.setItem(key,JSON.stringify(next));setRows(next);setError('');}catch{setError('Browser storage unavailable. Viewpoint was not saved.');}};
 return <div className="camera-bookmarks"><div className="map-tool-row"><button aria-describedby="map-viewpoints-help" aria-expanded={open} onClick={()=>setOpen(!open)}>Viewpoints</button><small id="map-viewpoints-help">Save and return to favorite camera views.</small></div>{open&&<dialog ref={dialog} className="data-dialog utility-dialog" aria-label="Camera bookmarks" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><h3>Camera bookmarks</h3><p>Save position, zoom, orientation and map layers in this browser.</p><form onSubmit={e=>{e.preventDefault();if(!viewer||viewer.isDestroyed()||!name.trim()||rows.length>=20)return;const C=window.Cesium,p=viewer.camera.positionCartographic;save([...rows,{id:crypto.randomUUID(),name:name.trim(),mode,pose:{lon:C.Math.toDegrees(p.longitude),lat:C.Math.toDegrees(p.latitude),height:p.height,heading:viewer.camera.heading,pitch:viewer.camera.pitch,roll:viewer.camera.roll},layers:{basemap:preferences.basemap,labels:preferences.labels,structures:preferences.structures,grid:preferences.grid,terrain:preferences.terrain,cityBuildings:preferences.cityBuildings,waterMotion:preferences.waterMotion}}]);setName('');}}><input aria-label="Viewpoint name" placeholder="Name this view" maxLength={60} value={name} onChange={e=>setName(e.target.value)}/><button disabled={!viewer||!name.trim()||rows.length>=20}>Save viewpoint</button></form>{error&&<p role="alert">{error}</p>}<ul>{rows.map(b=><li key={b.id}><button onClick={()=>{restore(b);setOpen(false);}}>{b.name} · {b.mode}</button><button aria-label={`Delete viewpoint ${b.name}`} onClick={()=>save(rows.filter(r=>r.id!==b.id))}>×</button></li>)}</ul>{!rows.length&&<p>No saved viewpoints.</p>}<button onClick={()=>setOpen(false)}>Close viewpoints</button></dialog>}</div>;
}
