import {useEffect,useRef,useState} from 'react';
import {createCockpitSound} from '../lib/cockpitAudio';
function preferences(){try{const p=JSON.parse(localStorage.getItem('skyward.cockpit-audio.v1')??'null');return {enabled:p?.enabled!==false,volume:typeof p?.volume==='number'&&Number.isFinite(p.volume)?Math.max(0,Math.min(1,p.volume)):.3};}catch{return {enabled:true,volume:.3};}}
export function CockpitAudio({aircraftType,speed,throttle,suspended}:{aircraftType:string;speed:number|null;throttle:number|null;suspended:boolean}){
 const [settings,setSettings]=useState(preferences),[blocked,setBlocked]=useState(false),sound=useRef<ReturnType<typeof createCockpitSound>|null>(null);
 const state=useRef({settings,suspended});state.current={settings,suspended};
 useEffect(()=>{const audio=createCockpitSound(aircraftType);sound.current=audio;let active=true;const start=()=>{if(!state.current.settings.enabled||state.current.suspended||document.hidden)return;void audio.start().then(()=>{if(active)setBlocked(false);}).catch(()=>{if(active)setBlocked(true);});};const visibility=()=>{if(document.hidden)audio.pause();else start();};document.addEventListener('pointerdown',start);document.addEventListener('keydown',start);document.addEventListener('visibilitychange',visibility);start();return()=>{active=false;document.removeEventListener('pointerdown',start);document.removeEventListener('keydown',start);document.removeEventListener('visibilitychange',visibility);audio.dispose();sound.current=null;};},[aircraftType]);
 useEffect(()=>{sound.current?.update({speed,throttle,volume:settings.volume});},[speed,throttle,settings.volume,aircraftType]);
 useEffect(()=>{try{localStorage.setItem('skyward.cockpit-audio.v1',JSON.stringify(settings));}catch{}let active=true;if(!settings.enabled||suspended||document.hidden)sound.current?.pause();else void sound.current?.start().then(()=>{if(active)setBlocked(false);}).catch(()=>{if(active)setBlocked(true);});return()=>{active=false;};},[settings,suspended]);
 const toggle=()=>{if(blocked&&settings.enabled){void sound.current?.start().then(()=>setBlocked(false)).catch(()=>setBlocked(true));}else setSettings(s=>({...s,enabled:!s.enabled}));};
 return <div className="cockpit-audio"><button role="switch" aria-label="Cockpit audio" aria-checked={settings.enabled&&!blocked} onClick={toggle}>{blocked&&settings.enabled?'Enable cockpit audio':`Cockpit audio: ${settings.enabled?'On':'Off'}`}</button><label>Volume<input aria-label="Cockpit audio volume" type="range" min="0" max="1" step=".05" value={settings.volume} onChange={e=>setSettings(s=>({...s,volume:Number(e.target.value)}))}/></label><small>Synthesized engine &amp; airflow</small></div>;
}
