import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import type {AirportGeometry} from '../types';
import {AIRPORTS} from '../types';
import {loadAirportGeometry} from '../lib/geographyLoader';
import {demoPlan,demoFleet,demoFrame} from '../lib/demoTraffic';
import {applyAircraftRig} from '../lib/aircraftRig';
import {surfaceHeight} from '../lib/surfaceHeight';
import './demoTraffic.css';
export function DemoTraffic({viewer,airport,close,reduced,suspended,realAvailable}:{viewer:Cesium.Viewer|null;airport:string;close:()=>void;reduced:boolean;suspended:boolean;realAvailable:boolean}){
 const [geometry,setGeometry]=useState<AirportGeometry|null>(null),[error,setError]=useState(''),[seed,setSeed]=useState(()=>Math.floor(Math.random()*4294967296)),[paused,setPaused]=useState(reduced),[selected,setSelected]=useState(''),[rows,setRows]=useState<{id:string;phase:string}[]>([]),[speed,setSpeed]=useState(1);
 const settings=useRef({paused,suspended,speed});settings.current={paused,suspended,speed};
 useEffect(()=>{if(reduced)setPaused(true);},[reduced]);
 useEffect(()=>{const c=new AbortController();setGeometry(null);setError('');loadAirportGeometry(`${import.meta.env.BASE_URL}data/airports/${airport}.json`,airport,c.signal).then(g=>{if(!c.signal.aborted)setGeometry(g);}).catch(()=>{if(!c.signal.aborted)setError('Airport geometry could not load. Retry after reconnecting.');});return()=>c.abort();},[airport]);
 const plan=useMemo(()=>geometry?demoPlan(geometry):null,[geometry]),fleet=useMemo(()=>plan?demoFleet(airport,seed,plan):[],[airport,seed,plan]);
 const sourceRef=useRef<Cesium.CustomDataSource|null>(null);
 useEffect(()=>{
  if(!viewer||viewer.isDestroyed()||!geometry||!plan)return;const v=viewer,C=window.Cesium,source=new C.CustomDataSource('skyward-fictional-traffic');sourceRef.current=source;let alive=true,time=0,last=performance.now(),report=0;
  void v.dataSources.add(source).then(()=>{if(!alive&&!v.isDestroyed())v.dataSources.remove(source,true);});
  const entities=fleet.map(f=>source.entities.add({id:f.id,name:f.name,model:{uri:`${import.meta.env.BASE_URL}models/fleet/${f.model}-SKYWARD-v1.gltf`,minimumPixelSize:20,maximumScale:3},label:{text:f.name,font:'12px sans-serif',fillColor:C.Color.fromCssColorString('#9ff2d2'),showBackground:true,pixelOffset:new C.Cartesian2(0,-28),distanceDisplayCondition:new C.DistanceDisplayCondition(0,100000)}}));
  const handler=new C.ScreenSpaceEventHandler(v.canvas);handler.setInputAction((e:{position:Cesium.Cartesian2})=>{const id=v.scene.pick(e.position)?.id?.id;if(fleet.some(f=>f.id===id))setSelected(id);},C.ScreenSpaceEventType.LEFT_CLICK);
  const update=()=>{if(v.isDestroyed())return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(!document.hidden&&!settings.current.paused&&!settings.current.suspended)time+=dt*settings.current.speed;
   const frames=fleet.map(f=>demoFrame(plan,time+f.offset));
   entities.forEach((e,i)=>{const f=frames[i],terrain=surfaceHeight(v.scene.globe.getHeight(C.Cartographic.fromDegrees(f.lon,f.lat))),position=C.Cartesian3.fromDegrees(f.lon,f.lat,terrain+f.altitude*.3048+4);e.position=new C.ConstantPositionProperty(position);e.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(position,new C.HeadingPitchRoll((f.heading-90)*Math.PI/180,f.pitch*Math.PI/180,0)));applyAircraftRig(e,time,settings.current.paused?0:f.groundSpeed,f.gear,0,f.ground?.5:0,f.heading,f.ground);});
   if(now-report>500){report=now;setRows(frames.map((f,i)=>({id:fleet[i].id,phase:f.phase})));}if(!settings.current.paused&&!document.hidden)v.scene.requestRender();
  };update();const remove=v.scene.preUpdate.addEventListener(update);
  return()=>{alive=false;remove();handler.destroy();sourceRef.current=null;if(!v.isDestroyed()){if(v.trackedEntity&&entities.includes(v.trackedEntity))v.trackedEntity=undefined;v.dataSources.remove(source,true);v.scene.requestRender();}};
 },[viewer,geometry,plan,fleet]);
 const focus=(id:string)=>{setSelected(id);const e=sourceRef.current?.entities.getById(id);if(e&&viewer&&!viewer.isDestroyed()){e.viewFrom=new window.Cesium.ConstantProperty(new window.Cesium.Cartesian3(-160,-160,80));viewer.trackedEntity=e;}};
 const chosen=fleet.find(f=>f.id===selected),phase=rows.find(r=>r.id===selected)?.phase;
 return <section className="demo-traffic-panel" aria-label="Skyward simulated traffic"><header><strong>SKYWARD · SIMULATED TRAFFIC</strong><button aria-label="Close simulated traffic" onClick={close}>×</button></header><p>Fictional flights at {airport}. These are not received aircraft positions.</p>{realAvailable&&<button onClick={close}>Real observations are available · return to tracking</button>}{error?<p role="alert">{error}</p>:!geometry?<p role="status">Loading demonstration airport…</p>:!plan?<p>No usable runway here. Choose another airport for the demo.</p>:<><small>{plan.inbound.gate.startsWith('illustrative')?'Illustrative taxi route and stand; mapped layout unavailable.':'Mapped taxiways; fictional gate assignments.'} Routes and models are randomly selected. The animation follows a local circuit, not the full fictional journey.</small><div className="demo-controls"><button onClick={()=>setPaused(!paused)}>{paused?'Play demo':'Pause demo'}</button><label>Speed<select aria-label="Simulation speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="5">5×</option><option value="15">15×</option></select></label><button onClick={()=>{setSelected('');setSeed(Math.floor(Math.random()*4294967296));}}>New fleet</button></div><ul>{fleet.map(f=><li key={f.id}><button aria-pressed={selected===f.id} onClick={()=>focus(f.id)}><b>{f.name}</b><span>{rows.find(r=>r.id===f.id)?.phase??'Preparing'} · {f.model}</span></button></li>)}</ul>{chosen&&<div className="demo-flight-detail"><b>{chosen.name} · Skyward</b><p>{['landing','rollout','taxi in','parked at gate'].includes(phase??'')?`${chosen.destination} → ${airport}`:`${airport} → ${chosen.destination}`}</p><small>Fictional itinerary · {AIRPORTS[chosen.destination].name}</small><button onClick={()=>{const e=sourceRef.current?.entities.getById(chosen.id);if(e&&viewer)viewer.trackedEntity=viewer.trackedEntity===e?undefined:e;}}>Follow / release demo aircraft</button></div>}</>}<p className="demo-upgrade">Real observed traffic remains free where coverage exists. Premium offers richer flight details when available; coverage and update delays vary.</p><button onClick={()=>window.dispatchEvent(new Event('skyward-upgrade'))}>Explore Premium</button></section>;
}
