import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import type {AirportGeometry} from '../types';
import {AIRPORTS} from '../types';
import {loadAirportGeometry} from '../lib/geographyLoader';
import {demoPlan,demoFleet} from '../lib/demoTraffic';
import {operation,trafficFrame,trafficSchedule,journey,journeyFrame,parseDemoSave,compatibleModel,demoDestination,serviceVehicles,DEMO_HANDLING,type DemoPose,type DemoSave} from '../lib/demoOperations';
import {applyAircraftRig} from '../lib/aircraftRig';
import elevations from '../../data/airport-elevations.json';
import {surfaceHeight} from '../lib/surfaceHeight';
import './demoTraffic.css';
type Camera='side'|'cockpit'|'cabin'|'tower'|'free';
const key=(airport:string)=>`skyward.demo.v2.${airport}`;
function saved(airport:string){try{return parseDemoSave(localStorage.getItem(key(airport)),airport);}catch{return null;}}
export function DemoTraffic({viewer,airport,close,reduced,suspended,realAvailable}:{viewer:Cesium.Viewer|null;airport:string;close:()=>void;reduced:boolean;suspended:boolean;realAvailable:boolean}){
 const [restore]=useState(()=>saved(airport));
 const [geometry,setGeometry]=useState<AirportGeometry|null>(null),[destination,setDestination]=useState<AirportGeometry|null>(null),[error,setError]=useState('');
 const [seed,setSeed]=useState(()=>restore?.seed??Math.floor(Math.random()*4294967296)),[paused,setPaused]=useState(reduced||restore?.paused||false),[selected,setSelected]=useState(restore?.flight||'skyward-demo-0'),[rows,setRows]=useState<DemoPose[]>([]),[speed,setSpeed]=useState(restore?.speed??1),[camera,setCamera]=useState<Camera>((restore?.camera as Camera)||'side'),[trip,setTrip]=useState(restore?.journey??false);
 const elapsed=useRef(restore?.time??0),journeyTime=useRef(restore?.journeyTime??0);
 const settings=useRef({paused,suspended,speed,selected,camera,trip,seed});settings.current={paused,suspended,speed,selected,camera,trip,seed};
 const persist=()=>{try{const s=settings.current;const value:DemoSave={version:2,airport,seed:s.seed,time:elapsed.current,journeyTime:journeyTime.current,speed:s.speed,paused:s.paused,flight:s.selected,camera:s.camera,journey:s.trip};localStorage.setItem(key(airport),JSON.stringify(value));}catch{}};
 const persistRef=useRef(persist);persistRef.current=persist;
 useEffect(()=>{const write=()=>persistRef.current();const timer=setInterval(write,2000);window.addEventListener('pagehide',write);return()=>{clearInterval(timer);window.removeEventListener('pagehide',write);write();};},[airport]);
 useEffect(()=>{if(reduced)setPaused(true);},[reduced]);
 useEffect(()=>{const c=new AbortController();setGeometry(null);setError('');loadAirportGeometry(`${import.meta.env.BASE_URL}data/airports/${airport}.json`,airport,c.signal).then(g=>{if(!c.signal.aborted)setGeometry({...g,elevationFt:(elevations as Record<string,number>)[airport]??0});}).catch(()=>{if(!c.signal.aborted)setError('Airport geometry could not load. Close and retry after reconnecting.');});return()=>c.abort();},[airport]);
 const base=useMemo(()=>geometry?demoPlan(geometry):null,[geometry]);
 const fleet=useMemo(()=>base&&geometry?demoFleet(airport,seed,base).flatMap((f,i)=>{const model=compatibleModel(geometry,f.model);return model?[{...f,model,destination:demoDestination(airport,model,seed,i)}]:[];}):[],[airport,seed,base,geometry]);
 const operations=useMemo(()=>geometry?fleet.map((f,i)=>operation(geometry,f.model,i)).filter((o):o is NonNullable<typeof o>=>!!o):[],[geometry,fleet]);
 const schedule=useMemo(()=>trafficSchedule(operations),[operations]),chosen=fleet.find(f=>f.id===selected),index=Math.max(0,fleet.findIndex(f=>f.id===selected));
 useEffect(()=>{setDestination(null);if(!trip||!chosen)return;const c=new AbortController();setError('');loadAirportGeometry(`${import.meta.env.BASE_URL}data/airports/${chosen.destination}.json`,chosen.destination,c.signal).then(g=>{if(!c.signal.aborted)setDestination({...g,elevationFt:(elevations as Record<string,number>)[chosen.destination]??0});}).catch(()=>{if(!c.signal.aborted)setError('Destination geometry is unavailable. Return to airport activity or choose another fictional flight.');});return()=>c.abort();},[trip,chosen?.destination]);
 const flight=useMemo(()=>{if(!trip||!destination||!chosen||!operations[index])return null;const dest=operation(destination,chosen.model);return dest?journey(operations[index],dest):null;},[trip,destination,chosen,operations,index]);
 const sourceRef=useRef<Cesium.CustomDataSource|null>(null),poses=useRef<DemoPose[]>([]);
 useEffect(()=>{
  if(!viewer||viewer.isDestroyed()||!geometry||!operations.length)return;
  const v=viewer,C=window.Cesium,source=new C.CustomDataSource('skyward-fictional-traffic');sourceRef.current=source;let alive=true,last=performance.now(),report=0,lastCamera='';
  void v.dataSources.add(source).then(()=>{if(!alive&&!v.isDestroyed())v.dataSources.remove(source,true);});
  const groundAt=(port:AirportGeometry)=>surfaceHeight(v.scene.globe.getHeight(C.Cartographic.fromDegrees(port.lon,port.lat)));
  const offsetAt=(port:AirportGeometry)=>groundAt(port)-(port.elevationFt??0)*.3048;
  const entities=fleet.map(f=>source.entities.add({id:f.id,name:f.name,model:{uri:`${import.meta.env.BASE_URL}models/fleet/${f.model}-SKYWARD-v1.gltf`,minimumPixelSize:20,maximumScale:3},label:{text:f.name,font:'12px sans-serif',fillColor:C.Color.fromCssColorString('#9ff2d2'),showBackground:true,pixelOffset:new C.Cartesian2(0,-28),distanceDisplayCondition:new C.DistanceDisplayCondition(0,100000)}}));
  const vehicles=fleet.map((f)=>['tug','baggage','stairs'].map((kind,j)=>source.entities.add({id:`${f.id}-${kind}`,show:false,box:{dimensions:new C.Cartesian3(j===2?4:5,2,j===2?3.5:1.5),material:C.Color.fromCssColorString(j===0?'#f9c967':j===1?'#63b7af':'#e4eeee'),outline:true,outlineColor:C.Color.fromCssColorString('#163340')},label:{text:kind,font:'10px sans-serif',showBackground:true,pixelOffset:new C.Cartesian2(0,-16),distanceDisplayCondition:new C.DistanceDisplayCondition(0,350)}})));
  const vehicleParts=vehicles.map((cars,i)=>cars.map((car,j)=>Array.from({length:j===2?6:5},(_,part)=>source.entities.add({id:`${fleet[i].id}-vehicle-${j}-part-${part}`,show:false,box:{dimensions:part<4?new C.Cartesian3(.65,.3,.65):new C.Cartesian3(j===2?1.2:1.6,1.8,j===2?.35:1.1),material:C.Color.fromCssColorString(part<4?'#162027':j===2?'#ecf1f0':'#203b4c')}}))));
  if(flight){for(const r of flight.destination.airport.runways){const middle=C.Cartesian3.fromDegrees((r.a[0]+r.b[0])/2,(r.a[1]+r.b[1])/2,groundAt(flight.destination.airport)+.3),heading=Math.atan2((r.b[0]-r.a[0])*Math.cos(flight.destination.airport.lat*Math.PI/180),r.b[1]-r.a[1]);source.entities.add({id:`skyward-destination-runway-${r.id}`,position:middle,orientation:C.Transforms.headingPitchRollQuaternion(middle,new C.HeadingPitchRoll(heading-Math.PI/2,0,0)),box:{dimensions:new C.Cartesian3(r.length,r.width,.2),material:C.Color.fromCssColorString('#434e57'),outline:true,outlineColor:C.Color.WHITE}});}}
  const handler=new C.ScreenSpaceEventHandler(v.canvas);handler.setInputAction((e:{position:Cesium.Cartesian2})=>{const id=v.scene.pick(e.position)?.id?.id;if(fleet.some(f=>f.id===id)){setSelected(id);setCamera('side');}},C.ScreenSpaceEventType.LEFT_CLICK);
  const update=()=>{if(v.isDestroyed())return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;const s=settings.current,selectedIndex=Math.max(0,fleet.findIndex(f=>f.id===s.selected));
   if(!document.hidden&&!s.paused&&!s.suspended){if(s.trip&&flight)journeyTime.current=Math.min(flight.end,journeyTime.current+dt*s.speed);else if(!s.trip)elapsed.current+=dt*s.speed;}
   const frames=operations.map((o,i)=>s.trip&&i===selectedIndex&&flight?journeyFrame(flight,journeyTime.current):trafficFrame(o,i,elapsed.current,schedule));poses.current=frames;
   entities.forEach((e,i)=>{const f=frames[i],terrain=surfaceHeight(v.scene.globe.getHeight(C.Cartographic.fromDegrees(f.lon,f.lat)));let offset=offsetAt(operations[i].airport);if(s.trip&&flight&&i===selectedIndex){const u=Math.max(0,Math.min(1,(journeyTime.current-flight.departureSeconds)/flight.cruiseSeconds));offset=offsetAt(flight.origin.airport)*(1-u)+offsetAt(flight.destination.airport)*u;}const alt=Math.max(terrain,f.altitude*.3048+offset)+4,position=C.Cartesian3.fromDegrees(f.lon,f.lat,alt),visible=!s.trip||i===selectedIndex;
    e.show=visible&&!(i===selectedIndex&&(s.camera==='cockpit'||s.camera==='cabin'));e.position=new C.ConstantPositionProperty(position);e.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(position,new C.HeadingPitchRoll((f.heading-90)*Math.PI/180,f.pitch*Math.PI/180,f.bank*Math.PI/180)));applyAircraftRig(e,s.trip?journeyTime.current:elapsed.current,s.paused?0:f.groundSpeed,f.gear,0,f.ground?.5:0,f.heading,f.ground);
    const op=s.trip&&flight&&journeyTime.current>flight.departureSeconds+flight.cruiseSeconds?flight.destination:operations[i];
    serviceVehicles(op,f).forEach((car,j)=>{const vehicle=vehicles[i][j];vehicle.show=visible&&car.show;const travel=f.phase==='pushback'?0:12*Math.sin(Math.PI*f.service)**2;const h=(f.heading+90)*Math.PI/180;vehicle.position=new C.ConstantPositionProperty(C.Cartesian3.fromDegrees(car.lon+Math.sin(h)*travel/(111120*Math.max(.1,Math.cos(car.lat*Math.PI/180))),car.lat+Math.cos(h)*travel/111120,alt-4+(j===2?1.75:.75)));vehicle.orientation=e.orientation;
     const center=vehicle.position.getValue(v.clock.currentTime)!;const transform=C.Transforms.headingPitchRollToFixedFrame(center,new C.HeadingPitchRoll((f.heading-90)*Math.PI/180,0,0));vehicleParts[i][j].forEach((part,n)=>{part.show=vehicle.show;const offset=n<4?new C.Cartesian3(n<2?-1.5:1.5,n%2?1.05:-1.05,j===2?-1.35:-.4):new C.Cartesian3(j===2?(n-4)*1.2:1.3,0,j===2?(n-4)*.7-1:.8);part.position=new C.ConstantPositionProperty(C.Matrix4.multiplyByPoint(transform,offset,new C.Cartesian3()));part.orientation=e.orientation;});
    });
   });
   const entity=entities[selectedIndex],f=frames[selectedIndex],position=entity.position!.getValue(v.clock.currentTime)!;
   const camKey=`${s.selected}/${s.camera}/${s.trip}`;
   if(camKey!==lastCamera){v.trackedEntity=undefined;v.camera.lookAtTransform(C.Matrix4.IDENTITY);if(s.camera==='side'){entity.viewFrom=new C.ConstantProperty(new C.Cartesian3(-160,-160,80));v.trackedEntity=entity;}lastCamera=camKey;}
   if(s.camera==='cockpit'||s.camera==='cabin'){
    const offset=s.camera==='cockpit'?new C.Cartesian3(0,0,3):new C.Cartesian3(0,0,2),eye=C.Matrix4.multiplyByPoint(C.Transforms.eastNorthUpToFixedFrame(position),offset,new C.Cartesian3());v.camera.setView({destination:eye,orientation:{heading:(f.heading+(s.camera==='cabin'?90:0))*Math.PI/180,pitch:(s.camera==='cockpit'?f.pitch-2:-8)*Math.PI/180,roll:f.bank*Math.PI/180}});
   }else if(s.camera==='tower'){
    const op=s.trip&&flight&&journeyTime.current>flight.departureSeconds+flight.cruiseSeconds*.5?flight.destination:operations[selectedIndex];const eye=C.Cartesian3.fromDegrees(op.airport.lon,op.airport.lat,groundAt(op.airport)+65),direction=C.Cartesian3.normalize(C.Cartesian3.subtract(position,eye,new C.Cartesian3()),new C.Cartesian3()),up=C.Cartesian3.normalize(eye,new C.Cartesian3());v.camera.setView({destination:eye,orientation:{direction,up}});
   }
   if(now-report>400){report=now;setRows(frames);}if(!s.paused&&!document.hidden)v.scene.requestRender();
  };update();const remove=v.scene.preUpdate.addEventListener(update);
  return()=>{alive=false;remove();handler.destroy();sourceRef.current=null;if(!v.isDestroyed()){if(v.trackedEntity&&entities.includes(v.trackedEntity))v.trackedEntity=undefined;v.camera.lookAtTransform(C.Matrix4.IDENTITY);v.dataSources.remove(source,true);v.scene.requestRender();}};
 },[viewer,geometry,operations,fleet,schedule,flight]);
 const focus=(id:string)=>{setSelected(id);setCamera('side');};
 const current=rows[index],active=rows.findIndex(f=>f.ground||f.phase==='landing'),op=operations[index];
 const nextArrival=()=>{if(!schedule.slot)return;const current=Math.floor(elapsed.current/schedule.slot),next=elapsed.current-current*schedule.slot<operations[current%fleet.length].arrival?current:current+1;setSelected(fleet[next%fleet.length].id);setCamera('tower');};
 return <><section className="demo-traffic-panel" aria-label="Skyward simulated traffic"><header><strong>SKYWARD · SIMULATED TRAFFIC</strong><button aria-label="Close simulated traffic" onClick={close}>×</button></header><p>Fictional flights at {airport}. These are not received aircraft positions.</p>{realAvailable&&<button onClick={close}>Real observations are available · return to tracking</button>}{error&&<p role="alert">{error}</p>}{!geometry?<p role="status">Loading demonstration airport…</p>:!operations.length?<p>No suitable runway here. Choose another airport.</p>:<>
 <small>{trip?'Complete fictional journey · progress saved on this device.':'Airport activity · fictional local circuits. One flight reserves the movement area at a time.'} Stand assignments and service vehicles are illustrative.</small>
 <div className="demo-controls"><button onClick={()=>setPaused(!paused)}>{paused?'Play demo':'Pause demo'}</button><label>Speed<select aria-label="Simulation speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,5,15,60,120].map(s=><option key={s} value={s}>{s}×</option>)}</select></label>{!trip&&<button onClick={()=>{elapsed.current=0;journeyTime.current=0;setSeed(Math.floor(Math.random()*4294967296));setSelected('skyward-demo-0');}}>New fleet</button>}</div>
 <div className="demo-camera"><label>Camera<select aria-label="Demo camera" value={camera} onChange={e=>setCamera(e.target.value as Camera)}>{(['side','cockpit','cabin','tower','free'] as Camera[]).map(c=><option key={c} value={c}>{c[0].toUpperCase()+c.slice(1)}</option>)}</select></label>{!trip&&<><button onClick={nextArrival}>Watch next arrival</button><button title="Advance fictional activity to the next reserved arrival" onClick={()=>{const next=Math.floor(elapsed.current/schedule.slot)+1;elapsed.current=next*schedule.slot;setSelected(fleet[next%fleet.length].id);setCamera('tower');}}>Skip wait</button></>}</div>
 {!trip&&<><p className="demo-reservation">{active>=0?`${fleet[active]?.name} · movement area reserved`:'Movement area clear'} · other flights await their slots</p><ul>{fleet.map((f,i)=><li key={f.id}><button aria-pressed={selected===f.id} onClick={()=>focus(f.id)}><b>{f.name}</b><span>{rows[i]?.phase??'Preparing'} · {f.model}</span></button></li>)}</ul></>}
 {chosen&&op&&<div className="demo-flight-detail"><b>{chosen.name} · Skyward</b><p>{airport} → {chosen.destination} · {AIRPORTS[chosen.destination].name}</p><small>{current?.phase} · {current?.gate}<br/>{chosen.model} · approach {DEMO_HANDLING[chosen.model].approach} kt · cruise {DEMO_HANDLING[chosen.model].cruise} kt</small>{current&&['deboarding','servicing','boarding','ready for pushback'].includes(current.phase)&&<label>Turnaround<progress aria-label="Turnaround progress" max="1" value={current.service}/></label>}
 {trip?<><p>{!destination?'Loading destination…':!flight?'This aircraft needs a longer runway at the destination. Choose another flight.':`${Math.round(journeyTime.current/flight.end*100)}% · ${Math.round(flight.distance)} nm · ${current?.phase}`}</p>{flight&&<progress aria-label="Journey progress" max={flight.end} value={journeyTime.current}/>}<button onClick={()=>{setTrip(false);journeyTime.current=0;}}>Return to airport activity</button></>:<button onClick={()=>{journeyTime.current=0;setTrip(true);setCamera('side');}}>Fly complete journey</button>}
 <button onClick={()=>setCamera(camera==='free'?'side':'free')}>{camera==='free'?'Follow demo aircraft':'Release camera'}</button></div>}
 </>}<p className="demo-upgrade">Real observed traffic remains free where coverage exists. Premium adds flight details when available; coverage and update delays vary.</p><button onClick={()=>window.dispatchEvent(new Event('skyward-upgrade'))}>Explore Premium</button></section>
 {current&&camera==='cockpit'&&<section className="demo-cockpit" aria-label="Demo cockpit instruments"><span>SKYWARD · AUTOPILOT DEMO</span><strong>{airport} → {chosen?.destination}</strong><div><b>{Math.round(current.groundSpeed)}<small>KT</small></b><b>{Math.round(current.heading%360)}°<small>HDG</small></b><b>{Math.round(current.altitude).toLocaleString()}<small>FT</small></b><b>{current.gear>.9?'DOWN':'UP'}<small>GEAR</small></b></div><p>{current.phase} · use Fly an aircraft for manual controls</p></section>}
 {camera==='cabin'&&<div className="demo-cabin-window" aria-hidden="true"/>}</>;
}
