import {AirportTimeline} from './AirportTimeline';
import {MyFlights} from './MyFlights';
import {flightMoment} from '../lib/flightMoment';
import {FlightMoment} from './FlightMoment';
import type {SharedCamera} from '../lib/sharedCamera';
import type {WatchItem} from '../lib/useObservatory';
import {LocalBackup} from './LocalBackup';
import {InstallApp} from './InstallApp';
import {SessionTools} from './SessionTools';
import type {useSessionRecorder} from '../lib/useSessionRecorder';
import type {Recording} from '../lib/sessionRecording';
import {Discovery} from './Discovery';
import {TrafficBoard} from './TrafficBoard';
import {PersonalFavorites} from './PersonalFavorites';
import {HistoryExplorer} from './HistoryExplorer';
import {ReliabilityPanel} from './ReliabilityPanel';
import type {useOfflineMaps} from '../lib/offlineMaps';
import type {Quality} from '../lib/adaptiveQuality';
import {lazy,Suspense} from 'react';
const ModelGallery=lazy(()=>import('./ModelGallery').then(m=>({default:m.ModelGallery})));
import {useEffect,useMemo,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {AIRPORTS,type Aircraft,type AirportGeometry,type FacilityTarget,type TrailPoint} from '../types';
import {airportFacilities} from './AirportInspector';
import {nearestAirports,sanitizeCollections,type AirportCollection,type ActivityBin,type Movement} from '../lib/exploration';
import type {MapPreferences} from '../lib/mapPreferences';
import {ActivityChart} from './ActivityChart';
import {FlightComparison} from './FlightComparison';
export type ExploreTab='dashboard'|'session'|'density'|'spotter'|'discover'|'board'|'history'|'gallery'|'reliability'|'airport'|'activity'|'compare'|'coverage'|'collections'|'access';
interface Props {watchFlight:(a:Aircraft)=>void;captureCamera:()=>SharedCamera|null;startGround:()=>void;watches:WatchItem[];toggleWatch:(a:WatchItem)=>void;alertsEnabled:boolean;setAlertsEnabled:(v:boolean)=>void;recorder:ReturnType<typeof useSessionRecorder>;playSession:(r:Recording)=>void;density:boolean;setDensity:(v:boolean)=>void;startSpotter:()=>void;initialTab?:ExploreTab;center:{lat:number;lon:number};airportRows:Aircraft[];airportError:string;lookup:(hex:string)=>Promise<Aircraft|null>;replay:(a:Aircraft,index:number)=>void;offline:ReturnType<typeof useOfflineMaps>;automatic:Quality|null;restore:()=>void;airport:string;geometry?:AirportGeometry;close:()=>void;focusAirport:(id:string)=>void;overview:()=>void;focusFacility:(f:FacilityTarget)=>void;activity:ActivityBin[];now:number;movements:Movement[];showMovements:boolean;setShowMovements:(x:boolean)=>void;observations:Aircraft[];histories:Map<string,TrailPoint[]>;selected:Aircraft|null;ingest:(rows:Aircraft[])=>Aircraft[];select:(a:Aircraft)=>void;preferences:MapPreferences;setPreferences:(p:MapPreferences)=>void;}
interface Coverage {facilityImport?:{status:string;checkedAt:string|null;matching:string|null};paths?:number;courtyards?:number;id:string;name:string;city:string;country:string;icao:string;runways:number;terminals:number;buildings:number;gates:number;coverage:{runways:string;buildings:string;gates:string;omittedRunways:number};directoryDate:string;facilityDate:string|null;sourceUrl:string;source:string;omittedComplexFeatures:number|null;}
function CoverageDashboard({go}:{go:(id:string)=>void}){
 const [data,setData]=useState<Coverage[]|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 useEffect(()=>{const c=new AbortController();setError('');fetch(`${import.meta.env.BASE_URL}data/coverage.json`,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(15000)])}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(()=>{if(!c.signal.aborted)setError('Coverage metadata could not load.');});return()=>c.abort();},[attempt]);
 const rows=useMemo(()=>(data??[]).filter(a=>`${a.id} ${a.icao} ${a.name} ${a.city} ${a.country}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='facilities'&&(a.buildings>0||a.gates>0)||filter==='missing'&&(!a.buildings||!a.gates)||filter==='runways'&&a.coverage.runways!=='mapped')),[data,query,filter]);
 if(error)return <p role="status">{error} <button className="quiet-button" onClick={()=>setAttempt(x=>x+1)}>Retry coverage</button></p>;
 if(!data)return <p role="status">Loading coverage metadata…</p>;
 return <><p>{data.length.toLocaleString()} airports · {data.filter(a=>a.buildings||a.gates).length} with mapped facilities. All facility coverage is partial. Counts do not prove a complete or current inventory.</p><div className="tools-controls"><input aria-label="Search coverage" placeholder="Airport, city or country" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><select aria-label="Coverage filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All airports</option><option value="facilities">Mapped facilities</option><option value="missing">Gates or buildings unavailable</option><option value="runways">Partial / unavailable runways</option></select></div><p role="status">{rows.length} matching airports</p><div className="coverage-table"><table><caption>Coverage and source snapshots</caption><thead><tr><th>Airport</th><th>Runways</th><th>Facilities</th><th>Snapshots / source</th></tr></thead><tbody>{rows.slice(page*30,page*30+30).map(a=><tr key={a.id}><td><button className="text-button" onClick={()=>go(a.id)}>{a.id} · {a.name}</button><small>{a.country}</small></td><td>{a.runways} · {a.coverage.runways}{a.coverage.omittedRunways>0&&<small>{a.coverage.omittedRunways} rows omitted</small>}</td><td>{a.terminals} terminal footprints · {a.buildings} buildings · {a.gates} gates<small>Buildings {a.coverage.buildings}; gates {a.coverage.gates}</small><small>{a.paths??0} mapped paths · {a.courtyards??0} courtyards</small>{a.facilityImport&&<small>Import: {a.facilityImport.status.replaceAll('_',' ')}</small>}{a.omittedComplexFeatures!==null&&<small>{a.omittedComplexFeatures} complex/open features omitted</small>}</td><td><small>Directory {a.directoryDate.slice(0,10)}</small><small>Facilities {a.facilityDate?.slice(0,10)??'Unavailable'}</small><a href={a.sourceUrl} target="_blank" rel="noreferrer">Airport source ↗</a><details><summary>Provenance</summary>{a.source}</details></td></tr>)}</tbody></table></div><div className="tools-controls"><button className="quiet-button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous page</button><span>Page {page+1} of {Math.max(1,Math.ceil(rows.length/30))}</span><button className="quiet-button" disabled={(page+1)*30>=rows.length} onClick={()=>setPage(p=>p+1)}>Next page</button></div></>;
}
function Collections({airport,go}:{airport:string;go:(id:string)=>void}){
 const [groups,setGroups]=useState<AirportCollection[]>(()=>{try{return sanitizeCollections(JSON.parse(localStorage.getItem('skyward.collections.v1')??'[]'));}catch{return [];}}),[name,setName]=useState(''),[active,setActive]=useState(''),[error,setError]=useState('');
 useEffect(()=>{try{localStorage.setItem('skyward.collections.v1',JSON.stringify(groups));setError('');}catch{setError('Browser storage is unavailable. Changes last only while this panel stays open.');}},[groups]);
 const group=groups.find(g=>g.id===active)??groups[0];
 return <><p>Named airport collections stay in this browser. Up to 20 collections with 50 airports each.</p><form className="inline-form" onSubmit={e=>{e.preventDefault();if(!name.trim()||groups.length>=20)return;const id=crypto.randomUUID();setGroups(old=>[...old,{id,name:name.trim(),airports:[]}]);setActive(id);setName('');}}><input aria-label="New airport collection name" value={name} maxLength={60} placeholder="e.g. European hubs" onChange={e=>setName(e.target.value)}/><button className="quiet-button" disabled={!name.trim()||groups.length>=20}>Create collection</button></form>{error&&<p className="warning" role="status">{error}</p>}{!group?<p>No collections yet. Create one, then add the selected airport.</p>:<><label>Collection<select aria-label="Saved airport collection" value={group.id} onChange={e=>setActive(e.target.value)}>{groups.map(g=><option value={g.id} key={g.id}>{g.name} ({g.airports.length})</option>)}</select></label><div className="tools-controls"><button className="quiet-button" disabled={group.airports.includes(airport)||group.airports.length>=50} onClick={()=>setGroups(old=>old.map(g=>g.id===group.id?{...g,airports:[...g.airports,airport]}:g))}>Add {airport} to collection</button><button className="quiet-button" onClick={()=>setGroups(old=>old.filter(g=>g.id!==group.id))}>Delete collection</button></div><ul className="collection-list">{group.airports.map(id=><li key={id}><button className="text-button" onClick={()=>go(id)}>{id} · {AIRPORTS[id].name}</button><button aria-label={`Remove ${id} from collection`} onClick={()=>setGroups(old=>old.map(g=>g.id===group.id?{...g,airports:g.airports.filter(x=>x!==id)}:g))}><X size={15}/></button></li>)}</ul>{!group.airports.length&&<p>This collection is empty.</p>}</>}</>;
}
export function ExploreTools(p:Props){
 const [tab,setTab]=useState<ExploreTab>(p.initialTab??'discover');const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>before?.focus();},[]);
 const nearby=useMemo(()=>nearestAirports(p.airport),[p.airport]);
 const facilities=useMemo(()=>airportFacilities(p.geometry).filter(f=>f.kind==='terminal'||f.kind==='runway'),[p.geometry]);
 const go=(id:string)=>{p.focusAirport(id);p.close();};
 return <dialog ref={ref} className="data-dialog explore-dialog" aria-labelledby="explore-title" onCancel={p.close} onClick={e=>{if(e.target===e.currentTarget)p.close();}}><div className="dialog-heading"><h2 id="explore-title">Explore tools</h2><button className="icon-button" aria-label="Close explore tools" onClick={p.close}><X size={20}/></button></div><nav className="explore-tabs" aria-label="Exploration tools">{([['dashboard','My flights'],['session','Sessions'],['spotter','Spotter'],['density','Density'],['discover','Discover'],['board','Traffic board'],['history','Flight history'],['gallery','Model gallery'],['airport','Airport'],['activity','Activity'],['compare','Compare flights'],['coverage','Coverage'],['collections','Collections'],['access','Accessibility'],['reliability','Device & offline']] as [ExploreTab,string][]).map(([t,label])=><button key={t} className="quiet-button" aria-pressed={tab===t} onClick={()=>setTab(t)}>{label}</button>)}</nav><div className="explore-content">
 {tab==='dashboard'&&<><MyFlights watches={p.watches} rows={p.observations} lookup={p.lookup} watch={p.watchFlight} canReplay={hex=>(p.histories.get(hex)?.filter(pt=>pt.time>=p.now-300000).length??0)>=2} replay={a=>p.playSession(flightMoment(a,p.histories.get(a.hex)??[],p.now,300,p.captureCamera()))}/><PersonalFavorites watches={p.watches} toggleWatch={p.toggleWatch} alertsEnabled={p.alertsEnabled} setAlertsEnabled={p.setAlertsEnabled} airport={p.airport} rows={p.observations} selected={p.selected} go={go} view={p.watchFlight} lookup={p.lookup}/></>}
 {tab==='session'&&<><FlightMoment checkPremium={p.recorder.checkPremium} aircraft={p.selected} points={p.selected?p.histories.get(p.selected.hex)??[]:[]} camera={p.captureCamera} play={p.playSession}/><SessionTools airport={p.airport} recorder={p.recorder} play={p.playSession}/></>}
 {tab==='spotter'&&<><h3>{p.airport} · Airport spotter</h3><p>Watch arrival candidates, departure candidates or reported ground traffic. Automatically switch aircraft every 20 seconds, or keep following one. The queue uses multiple received fixes, not published arrival schedules. It waits when there is no credible candidate and switches after a trend ends or a signal goes stale.</p><p>Dragging the globe or manually choosing an aircraft stops automatic following. Opening tools pauses the queue.</p><button className="primary-button" onClick={p.startSpotter}>Start airport spotter</button></>}
 {tab==='density'&&<><h3>Observed traffic density</h3><label className="toggle-option"><input type="checkbox" checked={p.density} onChange={e=>p.setDensity(e.target.checked)}/>Show traffic-density overlay</label><p>Counts distinct airborne aircraft in each 0.1° cell using retained observations from the last 30 minutes. Repeated fixes do not inflate a cell’s aircraft count. Only received positions contribute; gaps are not connected.</p><p>The 2,000 busiest retained cells are shown. Coverage depends on where you have looked and what the receivers reported. This is not total traffic volume or a worldwide coverage measure.</p><button className="quiet-button" onClick={p.close}>View map</button></>}
 {tab==='discover'&&<Discovery rows={p.observations} now={p.now} center={p.center} select={a=>{p.select(a);p.close();}} airport={go}/>}
 {tab==='board'&&<TrafficBoard airport={p.airport} rows={p.airportRows} histories={p.histories} now={p.now} error={p.airportError} select={a=>{p.select(a);p.close();}}/>}
 {tab==='history'&&<HistoryExplorer rows={p.observations} histories={p.histories} selected={p.selected} replay={(a,index)=>{p.replay(a,index);p.close();}}/>}
 {tab==='gallery'&&<Suspense fallback={<p role="status">Loading model gallery…</p>}><ModelGallery reducedMotion={p.preferences.reducedMotion} observations={p.observations}/></Suspense>}
 {tab==='reliability'&&<><LocalBackup recording={p.recorder.recording}/><InstallApp/><ReliabilityPanel preferences={p.preferences} change={p.setPreferences} offline={p.offline} automatic={p.automatic} restore={p.restore}/></>}
 {tab==='airport'&&<><h3>{p.airport} · {AIRPORTS[p.airport].name}</h3><p>Frame all mapped runways and terminals, or jump directly to a facility.</p><button className="primary-button" disabled={!p.geometry} onClick={()=>{p.overview();p.close();}}>Airport overview</button><div className="facility-shortcuts">{facilities.slice(0,24).map(f=><button key={f.id} className="quiet-button" onClick={()=>{p.focusFacility(f);p.close();}}>{f.label}</button>)}</div>{facilities.length>24&&<p>More facilities are available in the airport inspector.</p>}<h3>Ground turnaround animation</h3><p>Optional simulation: mapped taxi routes, runway holds, ground services and pushback. Independent of reported traffic and gate assignments.</p><button className="quiet-button" disabled={!p.geometry} onClick={p.startGround}>Start ground animation</button><h3>Nearby major airports</h3><p>Distance from {p.airport}; these are the closest airports in our directory, not necessarily every nearby airfield.</p><ul className="nearby-airports">{nearby.map(a=><li key={a.code}><button onClick={()=>go(a.code)}><strong>{a.code} · {a.name}</strong><span>{a.city} · {a.distance.toFixed(1)} nm</span></button></li>)}</ul></>}
 {tab==='activity'&&<><AirportTimeline rows={p.observations} histories={p.histories} center={AIRPORTS[p.airport]} now={p.now} select={a=>{p.select(a);p.close();}}/><h3>{p.airport} · Session observations</h3><label className="toggle-option"><input type="checkbox" checked={p.showMovements} onChange={e=>p.setShowMovements(e.target.checked)}/>Show approach / departure candidates on globe</label><p>Blue solid trails: approaching the airport. Orange dashed trails: moving away. Inferred from fresh, contiguous observed fixes within 20 nm; flyovers are possible. No landing, takeoff or itinerary is confirmed. Only the latest three minutes are evaluated.</p><p role="status">{p.movements.length} current movement candidates · collecting for the selected airport while this page is visible</p><ul className="movement-list">{p.movements.slice(0,20).map(m=><li key={m.hex}><button className="text-button" onClick={()=>{const a=p.observations.find(a=>a.hex===m.hex);if(a){p.select(a);p.close();}}}>{m.label} · {m.direction} · {m.distance.toFixed(1)} nm · inferred</button></li>)}</ul><ActivityChart bins={p.activity} now={p.now}/></>}
 {tab==='compare'&&<FlightComparison observations={p.observations} histories={p.histories} now={p.now} selected={p.selected} ingest={p.ingest} view={a=>{p.select(a);p.close();}}/>}
 {tab==='coverage'&&<CoverageDashboard go={go}/>}
 {tab==='collections'&&<><PersonalFavorites watches={p.watches} toggleWatch={p.toggleWatch} alertsEnabled={p.alertsEnabled} setAlertsEnabled={p.setAlertsEnabled} airport={p.airport} rows={p.observations} selected={p.selected} go={go} view={a=>{p.select(a);p.close();}} lookup={p.lookup}/><h3>Named airport collections</h3><Collections airport={p.airport} go={go}/></>}
 {tab==='access'&&<><h3>Make the view comfortable</h3>{([['reducedMotion','Reduced motion'],['largeLabels','Larger labels and controls'],['highContrast','Higher contrast']] as const).map(([key,label])=><label className="toggle-option" key={key}><input type="checkbox" checked={p.preferences[key]} onChange={e=>p.setPreferences({...p.preferences,[key]:e.target.checked})}/>{label}</label>)}<p>Settings stay on this device. Reduced motion starts from your system preference. Keyboard: Tab to controls; Enter/Space activate. Focus the globe and use left/right arrows, +/−, N (north), or T (tilt). Native facility selectors support typing a label. Escape closes this dialog and returns focus.</p><button className="quiet-button" onClick={()=>{p.close();setTimeout(()=>document.querySelector<HTMLCanvasElement>('.cesium-widget canvas')?.focus(),0);}}>Focus globe</button></>}
 </div></dialog>;
}
