import {useEffect,useRef,useState,type MutableRefObject} from 'react';
import type * as Cesium from 'cesium';
import type {AirportGeometry,Aircraft} from '../types';
import {AIRPORTS} from '../lib/airportCatalog';
import {accountRequest,type Account} from '../lib/membership';
import {saveAccountItem} from '../lib/accountLibrary';
import {AIRFRAMES,initialFlight,stepFlight,chooseRunway,runwayStart,runwayEnd,runwayHeading,runwayOffset,nauticalMiles,headingTo,flightGuidance,type FlightPlan,type FlightState,type FlightInput,type AircraftType,type Difficulty} from '../lib/flightSimulator';
import {fleetUri} from '../lib/flightPresentation';
import {applyAircraftRig} from '../lib/aircraftRig';
import {installLandingGear,sourcedGearClearance} from '../lib/landingGear';
import {runwayMarkings} from '../lib/runwayDetails';
import './flight-simulator.css';
function FlightScene({plan,geometry,state,camera}:{plan:FlightPlan;geometry:AirportGeometry[];state:MutableRefObject<FlightState>;camera:MutableRefObject<'chase'|'front'|'overhead'>}){
 const root=useRef<HTMLDivElement>(null),[error,setError]=useState('');
 useEffect(()=>{let viewer:Cesium.Viewer|undefined,disposed=false,cleanupGear:(()=>void)|undefined,removeFrame:(()=>void)|undefined;
  const timer=setInterval(()=>{if(!window.Cesium||!root.current||disposed)return;clearInterval(timer);try{
   const C=window.Cesium;viewer=new C.Viewer(root.current,{baseLayer:false,animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,requestRenderMode:false});const v=viewer;
   v.resolutionScale=Math.min(1,1.5/window.devicePixelRatio);v.scene.globe.baseColor=C.Color.fromCssColorString('#355b55');v.scene.globe.depthTestAgainstTerrain=false;v.scene.screenSpaceCameraController.enableInputs=false;
   v.imageryLayers.addImageryProvider(new C.UrlTemplateImageryProvider({url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',credit:'Source: Esri, Vantor, Earthstar Geographics, and the GIS User Community',maximumLevel:19}));
   v.cesiumWidget.creditDisplay.addStaticCredit(new C.Credit('Airports: © OpenStreetMap contributors / OurAirports',true));
   for(const airport of geometry){
    for(const surface of airport.surfaces.slice(0,300))if(surface.points.length>2)v.entities.add({polygon:{hierarchy:C.Cartesian3.fromDegreesArray(surface.points.flat()),height:0,extrudedHeight:Math.min(surface.height||8,60),material:C.Color.fromCssColorString(surface.kind==='terminal'?'#718187':'#425759')}});
    for(const r of airport.runways){v.entities.add({corridor:{positions:C.Cartesian3.fromDegreesArray([...r.a,...r.b]),width:r.width,height:.2,material:C.Color.fromCssColorString('#343e43')}});for(const mark of runwayMarkings(r))v.entities.add({polyline:{positions:C.Cartesian3.fromDegreesArrayHeights(mark.flatMap(p=>[...p,.5])),width:2,material:C.Color.WHITE}});}
   }
   v.entities.add({polyline:{positions:C.Cartesian3.fromDegreesArrayHeights([...plan.departure.b,800,...plan.arrival.a,800]),width:1.5,material:C.Color.fromCssColorString('#b4f3dc').withAlpha(.4)}});
   const aircraft:Aircraft={hex:'000001',callsign:'SKYWARD',registration:'Simulation',aircraftType:plan.aircraftType,targetKind:'aircraft',lat:0,lon:0,altitude:0,observedAt:Date.now(),ground:true,groundSpeed:0,heading:0,verticalRate:0,sourceType:'Simulation'};
   const entity=v.entities.add({id:'flight-simulation',position:C.Cartesian3.fromDegrees(state.current.lon,state.current.lat,6),model:{uri:'/watch/'+fleetUri(aircraft),scale:1,minimumPixelSize:0,maximumScale:1}});
   cleanupGear=installLandingGear(C,v,()=>({aircraft:[aircraft],selected:aircraft,quality:'high'}));
   removeFrame=v.scene.preRender.addEventListener(()=>{const s=state.current,pos=C.Cartesian3.fromDegrees(s.lon,s.lat,s.altitude*.3048+sourcedGearClearance(plan.aircraftType,4));entity.position=new C.ConstantPositionProperty(pos);entity.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(pos,new C.HeadingPitchRoll((s.heading-90)*Math.PI/180,s.pitch*Math.PI/180,-s.bank*Math.PI/180)));applyAircraftRig(entity,s.elapsed,s.speed,s.gear?1:0,0,s.flaps/2,s.heading,s.ground);aircraft.ground=s.ground;aircraft.altitude=s.altitude;aircraft.groundSpeed=s.speed;const small=plan.aircraftType==='C172',range=camera.current==='overhead'?Math.max(600,s.altitude*.2):camera.current==='front'?small?13:38:small?30:plan.aircraftType==='C560'?50:75;v.camera.lookAt(pos,new C.HeadingPitchRange(s.heading*Math.PI/180,camera.current==='overhead'?-Math.PI/2:camera.current==='front'?-.01:-.18,range));entity.show=camera.current!=='front';});
   v.scene.renderError.addEventListener(()=>setError('The 3D view could not render. Pause and reload the simulator.'));
  }catch{setError('The 3D view could not start. Try a browser with WebGL enabled.');}},50);
  return()=>{disposed=true;clearInterval(timer);removeFrame?.();cleanupGear?.();if(viewer&&!viewer.isDestroyed())viewer.destroy();};
 },[plan,geometry,state,camera]);
 return <div className="pilot-scene" ref={root} aria-label="Flight simulation 3D view">{error&&<p className="pilot-render-error" role="alert">{error}</p>}</div>;
}
export function FlightSimulator(){
 const [account,setAccount]=useState<Account|null>(null),[from,setFrom]=useState('IAD'),[to,setTo]=useState('DCA'),[difficulty,setDifficulty]=useState<Difficulty>('easy'),[aircraftType,setType]=useState<AircraftType>('B738'),[challenge,setChallenge]=useState<FlightPlan['challenge']>('calm'),[plan,setPlan]=useState<FlightPlan|null>(null),[geometry,setGeometry]=useState<AirportGeometry[]>([]),[snapshot,setSnapshot]=useState<FlightState|null>(null),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[camera,setCamera]=useState<'chase'|'front'|'overhead'>('chase'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const state=useRef<FlightState>(null!),input=useRef<FlightInput>({pitch:0,roll:0,rudder:0}),cameraRef=useRef(camera);cameraRef.current=camera;
 useEffect(()=>{document.title='Flight simulator · Skyward';accountRequest<Account>('/api/account').then(setAccount).catch(()=>setMessage('Account service unavailable.'));},[]);
 useEffect(()=>{if(!plan)return;let id=0,last=performance.now(),paint=last;const tick=(now:number)=>{const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!document.hidden){const s=state.current,scale=s.altitude<1000||s.ground||['approach','landing'].includes(s.phase)?1:speed;state.current=stepFlight(s,plan,input.current,dt*scale);if(now-paint>80){setSnapshot({...state.current});paint=now;}}id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);const hide=()=>{input.current={pitch:0,roll:0,rudder:0};if(document.hidden)setPaused(true);};document.addEventListener('visibilitychange',hide);return()=>{cancelAnimationFrame(id);document.removeEventListener('visibilitychange',hide);};},[plan,paused,speed]);
 const change=(patch:Partial<FlightState>)=>{if(!state.current)return;state.current={...state.current,...patch};setSnapshot({...state.current});};
 useEffect(()=>{const keys=new Set<string>();const update=()=>{input.current={pitch:Number(keys.has('w')||keys.has('arrowdown'))-Number(keys.has('s')||keys.has('arrowup')),roll:Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),rudder:Number(keys.has('e'))-Number(keys.has('q'))};};const down=(e:KeyboardEvent)=>{if(!plan||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;const key=e.key.toLowerCase();if(['w','s','a','d','q','e','arrowup','arrowdown','arrowleft','arrowright','+','-','g','b','p'].includes(key)){e.preventDefault();if(key==='+')change({throttle:Math.min(1,state.current.throttle+.05)});else if(key==='-')change({throttle:Math.max(0,state.current.throttle-.05)});else if(!e.repeat&&key==='g'&&!state.current.ground)change({gear:!state.current.gear});else if(!e.repeat&&key==='b')change({brakes:!state.current.brakes});else if(!e.repeat&&key==='p')setPaused(v=>!v);else keys.add(key);update();}};const up=(e:KeyboardEvent)=>{keys.delete(e.key.toLowerCase());update();};const blur=()=>{keys.clear();update();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[plan]);
 async function start(){setBusy(true);setMessage('');try{if(from===to||!AIRPORTS[from]||!AIRPORTS[to])throw Error('Choose two different airports.');const data=await Promise.all([from,to].map(async id=>{const r=await fetch(`/watch/data/airports/${id}.json`,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Mapped airport geometry is unavailable. Choose another airport.');return await r.json() as AirportGeometry;}));const next:FlightPlan={from,to,difficulty,aircraftType,challenge,departure:chooseRunway(data[0].runways,AIRPORTS[to],true,aircraftType),arrival:chooseRunway(data[1].runways,AIRPORTS[from],false,aircraftType)};state.current=initialFlight(next);setSnapshot({...state.current});setGeometry(data);setPlan(next);setPaused(false);setSaved(false);setSpeed(1);input.current={pitch:0,roll:0,rudder:0};}catch(e){setMessage(e instanceof Error?e.message:'Unable to start.');}finally{setBusy(false);}}
 async function save(){if(!snapshot||!plan)return;setBusy(true);try{await saveAccountItem('missions',crypto.randomUUID(),{...plan,result:snapshot.phase==='landed'?'landed':snapshot.phase==='crashed'?'crashed':'aborted',duration:snapshot.elapsed,touchdownRate:snapshot.touchdownRate,assisted:snapshot.assisted});setSaved(true);setMessage('Saved to your Premium career.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 const hold=(axis:keyof FlightInput,value:number)=>({onKeyDown:(e:React.KeyboardEvent<HTMLButtonElement>)=>{if([' ','Enter'].includes(e.key)){e.preventDefault();input.current[axis]=value;}},onKeyUp:(e:React.KeyboardEvent<HTMLButtonElement>)=>{if([' ','Enter'].includes(e.key)){e.preventDefault();input.current[axis]=0;}},onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);input.current[axis]=value;},onPointerUp:()=>{input.current[axis]=0;},onPointerCancel:()=>{input.current[axis]=0;},onLostPointerCapture:()=>{input.current[axis]=0;}});
 const active=plan&&snapshot,finished=snapshot&&['landed','crashed'].includes(snapshot.phase),distance=active?nauticalMiles(snapshot,runwayStart(plan.arrival)):0,total=plan?nauticalMiles(runwayStart(plan.departure),runwayStart(plan.arrival)):1;
 return <main className="pilot-app"><header className="pilot-header"><strong>Skyward <span>/ Flight simulator</span></strong><a href="/">← Back to globe</a>{plan&&<span>{plan.from} → {plan.to} · {AIRFRAMES[plan.aircraftType].name}</span>}<button disabled={!plan} onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button></header>
 {(!account||!account.user?.premium)?<section className="pilot-setup"><h1>Fly your own journey.</h1><p>{message||(!account?'Checking your account…':'Flight controls and persistent careers are included with Premium.')}</p><a href="/?account=upgrade">Account &amp; Premium</a></section>:!active?<section className="pilot-setup"><h1>Your aircraft. Your destination.</h1><p>Choose a route, line up on a mapped runway, and fly from takeoff to landing. This is an entertainment simulation.</p><form onSubmit={e=>{e.preventDefault();void start();}}><label>Departure airport<input list="pilot-airports" value={from} onChange={e=>setFrom(e.target.value.toUpperCase())} required/></label><label>Destination airport<input list="pilot-airports" value={to} onChange={e=>setTo(e.target.value.toUpperCase())} required/></label><label>Aircraft<select aria-label="Aircraft" value={aircraftType} onChange={e=>setType(e.target.value as AircraftType)}>{Object.entries(AIRFRAMES).map(([id,a])=><option key={id} value={id}>{a.name}</option>)}</select></label><label>Difficulty<select aria-label="Difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="easy">Easy · assisted controls, optional autopilot</option><option value="advanced">Advanced · manual flying, trim and stalls</option></select></label><label>Challenge<select aria-label="Challenge" value={challenge} onChange={e=>setChallenge(e.target.value as FlightPlan['challenge'])}><option value="calm">Calm conditions</option><option value="crosswind">12 kt crosswind</option><option value="precision">Precision landing</option></select></label><button className="pilot-primary" disabled={busy}>{busy?'Preparing runways…':'Start flight'}</button></form>{AIRPORTS[from]&&AIRPORTS[to]&&<p>Route distance: {Math.round(nauticalMiles(AIRPORTS[from],AIRPORTS[to])).toLocaleString()} nm. Start with a short route such as IAD → DCA; cruise time acceleration is available.</p>}<datalist id="pilot-airports">{Object.entries(AIRPORTS).map(([id,a])=><option key={id} value={id}>{a.city} · {a.name}</option>)}</datalist>{message&&<p role="status">{message}</p>}<p>Easy offers self-levelling, gentler stall behavior and automatic landing brakes. Advanced requires manual pitch, bank, rudder, trim, gear and braking. The scenery uses mapped airport data and simplified flight physics.</p></section>:<>
 <div className="pilot-workspace"><aside className="pilot-instruments" aria-label="Flight instruments">{[['Airspeed',Math.round(snapshot.speed),'kt'],['Altitude',Math.round(snapshot.altitude),'ft above runway datum'],['Heading',Math.round(snapshot.heading)+'°',''],['Vertical speed',Math.round(snapshot.verticalSpeed),'ft/min']].map(([label,value,unit])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{unit}</small></div>)}</aside>
 <FlightScene plan={plan} geometry={geometry} state={state} camera={cameraRef}/>
 <aside className="pilot-mission"><span>Mission</span><h2>{snapshot.phase==='ready'?'Departure':snapshot.phase}</h2><p>{plan.difficulty==='easy'?'Easy':'Advanced'} · {plan.challenge}</p><ol><li>Take off from {plan.from}</li><li>Navigate to {plan.to}</li><li>Align with runway {plan.arrival.id.split('/')[0]}</li><li>Touch down and stop</li></ol><h3>Next instruction</h3><p className={snapshot.warning?'pilot-warning':'pilot-cue'} role="status">{snapshot.warning||flightGuidance(snapshot,plan)}</p><label>Route progress<progress max={1} value={Math.max(0,Math.min(1,1-distance/total))}/></label><p>{distance.toFixed(1)} nm to destination · bearing {Math.round(headingTo(snapshot,runwayStart(plan.arrival)))}°</p><p aria-label="Attitude">Pitch {snapshot.pitch.toFixed(1)}° · bank {snapshot.bank.toFixed(1)}°</p>{distance<12&&<><h3>Landing guidance</h3><p>{Math.round(runwayOffset(snapshot,plan.arrival).cross)} m from extended centreline · target {AIRFRAMES[plan.aircraftType].approach} kt</p></>}<h3>Destination runway</h3><p>{plan.to} · {plan.arrival.id}<br/>{Math.round(plan.arrival.length)} m · heading {Math.round(runwayHeading(plan.arrival))}°</p><label>View<select aria-label="View" value={camera} onChange={e=>setCamera(e.target.value as typeof camera)}><option value="chase">Chase</option><option value="front">Front</option><option value="overhead">Bird view</option></select></label><label>Time speed<select aria-label="Time speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1×</option><option value={4}>4× cruise</option><option value={16}>16× cruise</option></select></label><small>Automatically 1× near the ground and on approach.</small>{finished&&<><h3>{snapshot.phase==='landed'?'Arrival complete':'Flight ended'}</h3><p>Touchdown: {Math.round(Math.abs(snapshot.touchdownRate))} ft/min</p><button disabled={busy||saved} onClick={()=>void save()}>{saved?'Saved':'Save career result'}</button></>}<button onClick={()=>{setPlan(null);setSnapshot(null);}}>Choose another flight</button>{message&&<p role="status">{message}</p>}</aside></div>
 <section className="pilot-controls" aria-label="Aircraft controls"><label className="pilot-throttle">Throttle <strong>{Math.round(snapshot.throttle*100)}%</strong><input aria-label="Throttle" type="range" min={0} max={100} value={snapshot.throttle*100} disabled={snapshot.autopilot||!!finished} onChange={e=>change({throttle:Number(e.target.value)/100})}/></label><div className="pilot-attitude"><span>Attitude control</span><div><button {...hold('pitch',1)} disabled={snapshot.autopilot}>↑<small>Pitch up</small></button><button {...hold('pitch',-1)} disabled={snapshot.autopilot}>↓<small>Pitch down</small></button><button {...hold('roll',-1)} disabled={snapshot.autopilot}>←<small>Bank left</small></button><button {...hold('roll',1)} disabled={snapshot.autopilot}>→<small>Bank right</small></button></div></div><label>Gear<button disabled={snapshot.ground||snapshot.autopilot} aria-pressed={snapshot.gear} onClick={()=>change({gear:!snapshot.gear})}>{snapshot.gear?'Down':'Up'}</button></label><label>Flaps<select aria-label="Flaps" disabled={snapshot.autopilot} value={snapshot.flaps} onChange={e=>change({flaps:Number(e.target.value)})}><option value={0}>Retracted</option><option value={1}>Takeoff</option><option value={2}>Landing</option></select></label><label>Brakes<button disabled={snapshot.autopilot} aria-pressed={snapshot.brakes} onClick={()=>change({brakes:!snapshot.brakes})}>{snapshot.brakes?'On':'Off'}</button></label>{plan.difficulty==='easy'?<label>Autopilot<button aria-pressed={snapshot.autopilot} onClick={()=>change({autopilot:!snapshot.autopilot,assisted:true})}>{snapshot.autopilot?'On':'Off'}</button></label>:<label>Trim<input aria-label="Pitch trim" type="range" min={-10} max={10} step={1} value={snapshot.trim} onChange={e=>change({trim:Number(e.target.value)})}/></label>}<div className="pilot-rudder"><span>Rudder</span><button {...hold('rudder',-1)}>Left</button><button {...hold('rudder',1)}>Right</button></div></section><footer className="pilot-footer"><span>Simulation · simplified physics · {Math.floor(snapshot.elapsed/60)}:{String(Math.floor(snapshot.elapsed%60)).padStart(2,'0')}</span><details><summary>Keyboard controls</summary>W/S pitch · A/D bank · Q/E rudder · +/− throttle · G gear · B brakes · P pause. Hold touch controls to steer.</details><a href="/?account=return">Your career</a></footer>
 </>}
 </main>;
}
