import {AircraftIdentity} from './AircraftIdentity';
import {compareFlights} from '../lib/comparison';
import {airline,aircraftNames} from '../lib/aircraft';
import {useEffect,useMemo,useState} from 'react';
import type {Aircraft,TrailPoint} from '../types';
import {useFlightRoute} from '../lib/useFlightRoute';
import {ageSeconds,duration,splitTrail} from '../lib/aircraft';
import {kindLabel} from '../lib/exploration';
interface PlotDomain {start:number;end:number;low:number;high:number;}
function TrailPlot({points,label,domain}:{points:TrailPoint[];label:string;domain:PlotDomain}){
 if(points.length<2)return <p>Waiting for at least two observed fixes. No earlier history is supplied.</p>;
 const start=domain.start,span=Math.max(1,domain.end-start),height=domain.high-domain.low;
 return <><svg viewBox="0 0 320 100" role="img" aria-label={`${label}: observed altitude from ${Math.round(points[0].altitude)} to ${Math.round(points.at(-1)!.altitude)} feet; gaps over two minutes are disconnected`}><text x="0" y="14" fill="currentColor" fontSize="10">{domain.high.toLocaleString()}</text><text x="0" y="79" fill="currentColor" fontSize="10">{domain.low.toLocaleString()}</text><path d="M45 10V75H315" fill="none" stroke="#7897a7"/>{splitTrail(points).map((s,i)=><polyline key={i} points={s.map(p=>`${45+(p.time-start)/span*270},${75-(p.altitude-domain.low)/height*65}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2"/>)}</svg><p>{points.length} session fixes · {new Date(start).toISOString().slice(11,19)}–{new Date(domain.end).toISOString().slice(11,19)} UTC · altitude (ft)</p></>;
}
function FlightCard({a,points,now,view,domain}:{a:Aircraft|null;points:TrailPoint[];now:number;view:(a:Aircraft)=>void;domain:PlotDomain}){
 const route=useFlightRoute(a);
 if(!a)return <p>Choose a target from current observations or look up an identifier.</p>;
 return <><h3>{a.callsign||a.registration||a.hex}</h3><p>{kindLabel(a)} · {a.registration||a.hex} · {aircraftNames[a.aircraftType]||a.aircraftType||'Type unknown'} · {airline(a)}</p><AircraftIdentity aircraft={a}/>{a.positionWarning&&<p className="warning">Position quality: {a.positionWarning}</p>}<dl className="comparison-metrics"><div><dt>Altitude</dt><dd>{a.ground?'Ground':a.altitude===null?'Unknown':`${a.altitude.toLocaleString()} ft`}</dd></div><div><dt>Speed</dt><dd>{a.groundSpeed===null?'Unknown':`${Math.round(a.groundSpeed)} kt`}</dd></div><div><dt>Last fix</dt><dd>{duration(ageSeconds(a,now))}</dd></div></dl><p className={ageSeconds(a,now)>120?'warning':''}>{ageSeconds(a,now)>120?'Coverage gap · last observation retained.':'Reported values are not synchronized between flights.'}</p>
 <div className="comparison-route"><strong>Route record</strong><p>{route.loading?'Looking up route…':route.data?.airports.length?route.data.airports.map(a=>a.iata||a.icao).join(' → '):route.error||'Unavailable'}</p>{route.data?.airports.length? <p>{route.data.status==='POSITION_MISMATCH'?'Position mismatch':route.data.airports.length!==2?'Current leg unknown':route.data.status==='PLAUSIBLE'?'Estimated route':'Unverified route'} · not a confirmed itinerary</p>:null}</div><TrailPlot domain={domain} points={points} label={a.callsign||a.hex}/><button className="quiet-button" onClick={()=>view(a)}>View on globe</button></>;
}
export function FlightComparison({observations,histories,now,selected,ingest,view}:{observations:Aircraft[];histories:Map<string,TrailPoint[]>;now:number;selected:Aircraft|null;ingest:(rows:Aircraft[])=>Aircraft[];view:(a:Aircraft)=>void}){
 const [ids,setIds]=useState<[string,string]>([selected?.hex??'', '']);const [extra,setExtra]=useState<Aircraft[]>([]);const [query,setQuery]=useState(['','']);const [kind,setKind]=useState(['callsign','callsign']);const [errors,setErrors]=useState(['','']);const [busy,setBusy]=useState([false,false]);
 const pool=useMemo(()=>{const m=new Map(extra.map(a=>[a.hex,a]));for(const a of observations){if((a.observedAt??0)>=(m.get(a.hex)?.observedAt??0))m.set(a.hex,a);}return [...m.values()].sort((a,b)=>(a.callsign||a.hex).localeCompare(b.callsign||b.hex));},[observations,extra]);
 const difference=compareFlights(pool.find(a=>a.hex===ids[0]),pool.find(a=>a.hex===ids[1]));
 const allPoints=ids.flatMap(id=>histories.get(id)??[]);
 const domain:PlotDomain={start:allPoints.length?Math.min(...allPoints.map(p=>p.time)):now,end:allPoints.length?Math.max(...allPoints.map(p=>p.time)):now,low:Math.floor(Math.min(0,...allPoints.map(p=>p.altitude))/1000)*1000,high:Math.ceil(Math.max(1000,...allPoints.map(p=>p.altitude))/1000)*1000};
 const [requests,setRequests]=useState<[null|{kind:string;q:string},null|{kind:string;q:string}]>([null,null]);
 useEffect(()=>{const controller=new AbortController();let alive=true;setBusy([false,false]);const lookup=async(slot:number)=>{const r=requests[slot];if(!r)return;setBusy(b=>b.map((x,i)=>i===slot?true:x));try{const response=await fetch(`/api/search?kind=${encodeURIComponent(r.kind)}&q=${encodeURIComponent(r.q)}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(25000)])});if(!response.ok)throw new Error('Lookup unavailable; retained observations are unchanged.');const data=await response.json();if(!alive)return;const a=ingest(data.aircraft)[0] as Aircraft|undefined;if(!a)throw new Error('No current observation for that identifier.');setExtra(old=>[...old.filter(x=>x.hex!==a.hex),a].slice(-8));setIds(old=>old.map((x,i)=>i===slot?a.hex:x) as [string,string]);setErrors(old=>old.map((x,i)=>i===slot?'':x));}catch(e){if(alive)setErrors(old=>old.map((x,i)=>i===slot?(e as Error).message:x));}finally{if(alive)setBusy(old=>old.map((x,i)=>i===slot?false:x));}};for(let i=0;i<2;i++)void lookup(i);return()=>{alive=false;controller.abort();};},[requests,ingest]);
 // At most two explicit watches while comparison is open; no polling when hidden.
 const key=ids.filter(Boolean).sort().join(',');
 useEffect(()=>{if(!key)return;const controller=new AbortController();let alive=true,running=false;async function refresh(){if(document.hidden||running)return;running=true;try{for(const hex of key.split(',')){try{const response=await fetch(`/api/search?kind=hex&q=${hex}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(25000)])});if(!response.ok)continue;const data=await response.json();if(alive)ingest(data.aircraft);}catch{/* Staleness stays visible. */}}}finally{running=false;}}void refresh();const timer=setInterval(refresh,25000);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[key,ingest]);
 return <><p>Compare two reported targets. Positions refresh while this panel is open and visible. Trails contain only this session’s observed fixes. Both charts share the same time and altitude axes; gaps over two minutes are disconnected.</p>{difference&&<section className="comparison-difference" aria-label="Flight comparison differences"><h3>Flight 1 relative to Flight 2</h3><p>Altitude: {difference.altitude===null?'not comparable':`${difference.altitude>0?'+':''}${difference.altitude.toLocaleString()} ft`} · Speed: {difference.speed===null?'unavailable':`${difference.speed>0?'+':''}${Math.round(difference.speed)} kt`}</p><p>Observation time difference: {difference.skew===null?'unknown':`${Math.round(difference.skew)} seconds`}. Values are received measurements, not synchronized estimates.</p></section>}<div className="comparison-grid">{[0,1].map(i=><section key={i}><h3>Flight {i+1}</h3><label>Observed target<select aria-label={`Comparison flight ${i+1}`} value={ids[i]} onChange={e=>setIds(old=>old.map((x,j)=>i===j?e.target.value:x) as [string,string])}><option value="">Choose a target…</option>{pool.map(a=><option key={a.hex} value={a.hex} disabled={a.hex===ids[1-i]}>{a.callsign||a.registration||a.hex} · {a.hex}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();if(query[i].trim())setRequests(old=>old.map((x,j)=>i===j?{kind:kind[i],q:query[i].trim()}:null) as typeof requests);}}><label>Identifier<select aria-label={`Comparison identifier type ${i+1}`} value={kind[i]} onChange={e=>setKind(old=>old.map((x,j)=>j===i?e.target.value:x))}><option value="callsign">Callsign</option><option value="registration">Registration</option><option value="hex">ICAO hex</option></select></label><div className="inline-form"><input aria-label={`Comparison search ${i+1}`} maxLength={12} value={query[i]} onChange={e=>setQuery(old=>old.map((x,j)=>j===i?e.target.value:x))}/><button className="quiet-button" disabled={busy[i]||!query[i].trim()}>{busy[i]?'Searching…':'Look up'}</button></div></form>{errors[i]&&<p className="warning" role="status">{errors[i]}</p>}{ids[0]&&ids[0]===ids[1]&&<p className="warning">Both slots identify the same target.</p>}<FlightCard domain={domain} a={pool.find(a=>a.hex===ids[i])??null} points={histories.get(ids[i])??[]} now={now} view={view}/></section>)}</div></>;
}
