import {useMemo} from 'react';
import type {Aircraft,TrailPoint} from '../types';
import {AIRPORTS} from '../types';
import {coloredTrail,trackSummary,trackDistance} from '../lib/positionQuality';
export function FlightSummary({aircraft,points}:{aircraft:Aircraft;points:TrailPoint[]}){
 const summary=useMemo(()=>trackSummary(points),[points]);
 const nearby=useMemo(()=>aircraft.lat===null||aircraft.lon===null?[]:Object.entries(AIRPORTS).map(([id,a])=>({id,distance:trackDistance({lat:aircraft.lat!,lon:aircraft.lon!},a)})).sort((a,b)=>a.distance-b.distance).slice(0,3),[aircraft.lat,aircraft.lon]);
 const first=points[0]?.time??0,span=Math.max(1,summary.spanMs),max=Math.max(1000,...points.map(p=>p.altitude));
 return <details className="flight-summary"><summary>Flight session summary &amp; altitude profile</summary>{aircraft.positionWarning&&<p role="status" className="warning">Position quality: {aircraft.positionWarning}. Suspect fix excluded; last accepted position retains its original time.</p>}<p>{points.length} accepted fixes · {(summary.observedMs/60000).toFixed(1)} minutes observed within {(summary.spanMs/60000).toFixed(1)} minutes elapsed · {summary.gaps} disconnected gaps</p><p>{summary.distance.toFixed(1)} nm observed · {Math.round(summary.climb).toLocaleString()} ft cumulative climb · {Math.round(summary.descent).toLocaleString()} ft cumulative descent</p><p>Nearest directory airports to last accepted position: {nearby.map(a=>`${a.id} (${a.distance.toFixed(1)} nm)`).join(' · ')||'Position unavailable'}. These are not inferred destinations.</p><details><summary>Show altitude profile</summary>{points.length<2?<p>Waiting for another accepted observation.</p>:<><svg viewBox="0 0 500 120" role="img" aria-label="Observed altitude over elapsed session time; gaps disconnected">{coloredTrail(points).map((s,i)=><polyline key={i} fill="none" stroke={s.color} strokeWidth="3" points={s.points.map(p=>`${5+(p.time-first)/span*490},${110-Math.max(0,p.altitude)/max*100}`).join(' ')}/>)}</svg><p>0–{Math.round(max).toLocaleString()} ft · left to right: elapsed time</p></>}</details><p>Trail altitude: blue &lt;10,000 ft · mint 10,000–25,000 ft · violet ≥25,000 ft. Data gaps stay disconnected. This covers retained session observations, not the entire flight.</p></details>;
}
