import {publishGroundTraffic,forgetGroundTraffic} from '../lib/groundSafety';
import type {TowerDemoRadio} from './TowerRadio';
import {surfaceHeight} from '../lib/surfaceHeight';
import {towerCycle,runwayDemonstration,usableDemoRunway} from '../lib/towerCycle';
import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import type {AirportGeometry,Aircraft} from '../types';
import {groundFrame,groundPlan,groundHold} from '../lib/groundOperations';
import {applyAircraftRig} from '../lib/aircraftRig';
export function GroundAnimation({viewer,airport,observations,close,reduced,suspended,embedded=false,runwayIndex=0,onRadioState}:{onRadioState?:(state:TowerDemoRadio|null)=>void;embedded?:boolean;runwayIndex?:number;viewer:Cesium.Viewer|null;airport:AirportGeometry|undefined;observations:Aircraft[];close:()=>void;reduced:boolean;suspended:boolean}){
 const plan=useMemo(()=>airport?groundPlan(embedded?{...airport,runways:airport.runways[runwayIndex]?[airport.runways[runwayIndex]]:[]}:airport):null,[airport,embedded,runwayIndex]),[playing,setPlaying]=useState(!reduced),[speed,setSpeed]=useState(1),[revision,setRevision]=useState(0),[status,setStatus]=useState('Ready'),[count,setCount]=useState(0),[cue,setCue]=useState<'landing'|'taxi'|'takeoff'>('landing');
 const runway=plan?.runway??(embedded?airport?.runways[runwayIndex]:airport?.runways.find(usableDemoRunway)),available=usableDemoRunway(runway);
 const state=useRef({playing,speed,observations,suspended});state.current={playing,speed,observations,suspended};
 useEffect(()=>{if(reduced)setPlaying(false);},[reduced]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed()||!available||!runway||!airport)return;const v=viewer,C=window.Cesium;let time=plan&&embedded?(cue==='taxi'?45:cue==='takeoff'?plan.taxiSeconds+plan.outboundSeconds+95.25:0):0,completed=0,last=performance.now(),report=0,lastDrawn='';setCount(0);setStatus('Ready');
 const source=new C.CustomDataSource('illustrative-ground-operations');let alive=true;void v.dataSources.add(source).then(()=>{if(!alive&&!v.isDestroyed())v.dataSources.remove(source,true);});
 const plane=source.entities.add({id:'ground-demo-plane',model:{uri:import.meta.env.BASE_URL+'models/fleet/ground-b737.gltf?detail=6',minimumPixelSize:0,maximumScale:1},label:{text:'SIMULATION',font:'12px sans-serif',pixelOffset:new C.Cartesian2(0,-45),showBackground:true}});
 const service=(id:string,dimensions:Cesium.Cartesian3,color:string)=>source.entities.add({id,box:{dimensions,material:C.Color.fromCssColorString(color)}});
 const tug=service('ground-demo-tug',new C.Cartesian3(3,5,1.5),'#e4ba55'),cart=service('ground-demo-baggage',new C.Cartesian3(2,6,1.5),'#7895a3'),bridge=service('ground-demo-bridge',new C.Cartesian3(3,14,3),'#bec8ca');
 const sample=(t:number)=>plan?(embedded?towerCycle(plan,t):groundFrame(plan,t)):runwayDemonstration(runway,cue==='takeoff'?'takeoff':'landing',t),end=plan?plan.end+(embedded?46.5:0):45;
 const removeFrame=v.scene.preUpdate.addEventListener(()=>{if(v.isDestroyed())return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(document.hidden||state.current.suspended)return;
 let hold='';const proposed=sample(Math.min(end,time+dt*state.current.speed));
 if(state.current.playing&&completed<3){const nearby=state.current.observations.filter(a=>a.ground&&a.lat!==null&&a.lon!==null&&a.observedAt!==null&&Date.now()-a.observedAt<30000&&a.observedAt<=Date.now()+5000) as (Aircraft&{lat:number;lon:number})[];hold=proposed.altitude<1?groundHold(proposed,nearby,airport,state.current.observations,Date.now(),sample(time)):'';if(!hold)time+=dt*state.current.speed;}
 let f=sample(time);publishGroundTraffic('ground-demo-plane',{...f,ground:f.altitude<1},30,Date.now());if(f.phase==='complete'&&completed<(plan?3:1)){completed++;setCount(completed);if(plan){time=0;f=sample(0);}else{time=end;setPlaying(false);}}
 if(now-report>400){report=now;onRadioState?.({phase:f.phase,playing:state.current.playing&&completed<(plan?3:1)&&!hold});setStatus(completed===(plan?3:1)?(plan?'Turnarounds complete':`${cue==='takeoff'?'Takeoff':'Landing'} demonstration complete`):hold?`Holding · ${hold}`:`Aircraft ${completed+1} · ${f.phase}${plan?' · stand '+plan.inbound.gate:''}`);}const drawKey=`${time}/${completed}`;if(drawKey===lastDrawn)return;lastDrawn=drawKey;
 plane.show=plan?completed<3:!(completed&&cue==='takeoff');const terrain=surfaceHeight(v.scene.globe.getHeight(C.Cartographic.fromDegrees(f.lon,f.lat))),pos=C.Cartesian3.fromDegrees(f.lon,f.lat,terrain+f.altitude*.3048+4);
 plane.position=new C.ConstantPositionProperty(pos);plane.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(pos,new C.HeadingPitchRoll((f.heading-90)*Math.PI/180,f.pitch*Math.PI/180,0)));
 applyAircraftRig(plane,time,hold||!state.current.playing?0:f.groundSpeed,f.phase==='takeoff'?Math.max(0,1-f.altitude/150):1,0,f.phase==='takeoff'?.5:0,f.heading);
 const servicePhase=!!plan&&f.phase==='gate service',push=!!plan&&f.phase==='pushback',matrix=C.Transforms.headingPitchRollToFixedFrame(pos,new C.HeadingPitchRoll((f.heading-90)*Math.PI/180,0,0));
 for(const [e,x,y,z] of [[bridge,7,8,0],[cart,-8,Math.sin(time*.25)*9,-2],[tug,20,0,-2]] as [Cesium.Entity,number,number,number][]){e.show=completed<3&&(e===tug?push:servicePhase);e.position=new C.ConstantPositionProperty(C.Matrix4.multiplyByPoint(matrix,new C.Cartesian3(x,y,z),new C.Cartesian3()));e.orientation=plane.orientation;}
 if(bridge.box&&plan)bridge.box.dimensions=new C.ConstantProperty(new C.Cartesian3(3,4+10*Math.max(0,Math.min(1,(time-plan.taxiSeconds-(embedded?46.5:0))/5)),3));
 v.scene.requestRender();
 // Each route/stand is reserved through departure; queued aircraft cannot enter an occupied stand or meet an outgoing aircraft head-on.

 });
 return()=>{forgetGroundTraffic('ground-demo-plane');onRadioState?.(null);alive=false;removeFrame();if(!v.isDestroyed()){v.dataSources.remove(source,true);v.scene.requestRender();}};
 },[viewer,airport,plan,runway,available,revision,embedded,cue]);
 return <section className={embedded?'tower-animation-controls':'ground-animation-panel'} aria-label="Ground turnaround simulation"><strong>{plan?(embedded?'Landing → taxi → takeoff · SIMULATION':'Ground turnaround · SIMULATION'):'Runway demonstrations · SIMULATION'}</strong>{!embedded&&<p>Illustrative traffic, services and gate use. Received flight positions are unchanged.</p>}{available?<><p role="status">{status}</p>{(embedded||!plan)&&<div aria-label="Tower demonstration phase">{(['landing','taxi','takeoff'] as const).map(phase=><button key={phase} disabled={phase==='taxi'&&!plan} title={phase==='taxi'&&!plan?'Taxi-to-gate needs a connected mapped route':undefined} onClick={()=>{setCue(phase);setRevision(r=>r+1);setPlaying(!reduced);}}>Watch {phase}</button>)}</div>}<small>{plan?`${count} / 3 turnarounds · ${Math.max(0,2-count)} queued · shared route reserved until departure · observed traffic gets priority`:'Landing and takeoff are available. Taxi-to-gate is unavailable because mapped taxiways do not connect this runway to a stand. Each runway demonstration runs separately.'}</small><button onClick={()=>{if(!plan&&count){setRevision(r=>r+1);setPlaying(true);}else setPlaying(p=>!p);}}>{playing?'Pause animation':!plan&&count?'Replay demonstration':'Play animation'}</button><label>Speed<select aria-label="Ground animation speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,5,20].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><button onClick={()=>setRevision(r=>r+1)}>Restart animation</button>{!embedded&&plan&&<button onClick={()=>{const C=window.Cesium,p=plan.inbound.points.at(-1)!;viewer?.camera.flyTo({destination:C.Cartesian3.fromDegrees(p.lon,p.lat,800),orientation:{heading:0,pitch:-1.2,roll:0},duration:reduced?0:1});}}>View stand</button>}</>:<p>No usable runway geometry is available for a demonstration at this airport.</p>}{!embedded&&available&&<button onClick={()=>{const C=window.Cesium,s=viewer?.dataSources.getByName('illustrative-ground-operations')[0],e=s?.entities.getById('ground-demo-plane'),p=viewer&&e?.position?.getValue(viewer.clock.currentTime);if(p)viewer?.camera.lookAt(p,new C.HeadingPitchRange(0,-.5,220));viewer?.camera.lookAtTransform(C.Matrix4.IDENTITY);}}>View aircraft</button>}<button onClick={close}>Close ground animation</button></section>;
}
