import {useState} from 'react';
import type {Aircraft} from '../types';
import type {WatchItem} from '../lib/useObservatory';
import {savedFlight} from '../lib/watchDiscovery';
export function MyFlights({watches,rows,lookup,watch,replay,canReplay}:{watches:WatchItem[];rows:Aircraft[];lookup:(hex:string)=>Promise<Aircraft|null>;watch:(a:Aircraft)=>void;replay:(a:Aircraft)=>void;canReplay:(hex:string)=>boolean}){
 const [last]=useState(()=>{try{return savedFlight(JSON.parse(localStorage.getItem('skyward.last-flight.v1')??'null'));}catch{return null;}}),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const open=async(hex:string)=>{setBusy(hex);setMessage('');try{const recent=rows.find(a=>a.hex===hex&&a.observedAt!==null&&Date.now()-a.observedAt<30000);const a=recent??await lookup(hex);if(a)watch(a);else setMessage('No current position is available. Your saved flight is still here.');}catch{setMessage('Flight lookup is temporarily unavailable. Try again.');}finally{setBusy('');}};
 return <section className="my-flights" aria-label="My flights dashboard"><h3>Pick up where you left off</h3><p>Saved on this device. Opening a saved aircraft finds its latest position; it may now be operating a different flight.</p>{last?<button className="primary-button" disabled={!!busy} onClick={()=>void open(last.hex)}>Resume {last.label}</button>:<p>Watch a flight to make it available here next time.</p>}<h3>Watched flights</h3>{!watches.length&&<p>Star a flight to add it to this dashboard.</p>}<ul className="dashboard-flights">{watches.map(w=>{const a=rows.find(a=>a.hex===w.hex);return <li key={w.hex}><div><strong>{w.callsign||w.registration||w.hex}</strong><small>{a?.observedAt?`Last received ${Math.max(0,Math.round((Date.now()-a.observedAt)/1000))}s ago`:'No observation in this session'}</small></div><button disabled={!!busy} onClick={()=>void open(w.hex)}>{busy===w.hex?'Finding flight…':'Watch flight'}</button><button disabled={!a||!canReplay(w.hex)} onClick={()=>a&&replay(a)}>Replay received track</button></li>;})}</ul>{message&&<p role="status">{message}</p>}</section>;
}
