import LiveDirectory from './LiveDirectory';
import {useState} from 'react';
import type {Catalog} from '../lib/airframeCatalog';
import {aircraftLabel,directoryCategories,directoryMatches,entityAircraft,entityTypeLabel,type DirectoryCategory} from '../lib/notableDirectory';
export default function NotableDirectory({c,ids,onToggle}:{c:Catalog;ids:string[];onToggle:(id:string)=>void}){
 const [view,setView]=useState<'live'|'reference'>(()=>new URLSearchParams(location.search).has('category')||new URLSearchParams(location.search).has('q')?'reference':'live');
 const initial=new URLSearchParams(location.search),[query,setQuery]=useState(initial.get('q')??''),[category,setCategory]=useState<DirectoryCategory>(directoryCategories.find(v=>v===initial.get('category'))??'All');
 const update=(q:string,cat:DirectoryCategory)=>{setQuery(q);setCategory(cat);const params=new URLSearchParams();if(q)params.set('q',q);if(cat!=='All')params.set('category',cat);history.replaceState(null,'',location.pathname+(params.size?'?'+params:''));};
 const entities=directoryMatches(c,query,category);
 return <><h1>Notable aircraft</h1><div className="airframe-actions" role="group" aria-label="Directory view"><button aria-pressed={view==='live'} onClick={()=>setView('live')}>Watch live</button><button aria-pressed={view==='reference'} onClick={()=>setView('reference')}>Aircraft &amp; history</button></div>{view==='live'?<LiveDirectory c={c}/>:<><p className="airframe-eyebrow">Discover the stories behind the aircraft</p><h2>Aircraft &amp; history</h2><p>Explore sports, business, public-service and historic aircraft. Follow the airframe to keep it in your collection across verified registration changes.</p><label>Search the directory<input type="search" value={query} maxLength={100} placeholder="Team, organization, registration or aircraft…" onChange={e=>update(e.target.value,category)}/></label><div className="airframe-actions" role="group" aria-label="Directory categories">{directoryCategories.map(cat=><button key={cat} aria-pressed={cat===category} onClick={()=>update(query,cat)}>{cat} <span>({directoryMatches(c,'',cat).length})</span></button>)}</div><p role="status">{entities.length} {entities.length===1?'collection':'collections'} shown · Curated selections, not complete fleets.</p><p className="airframe-directory-note">Team branding is not proof of team ownership or who is onboard. Historical associations and source dates are shown on each collection.</p><div className="airframe-grid">{entities.map(e=>{const rows=entityAircraft(c,e.id);return <article className="airframe-card" key={e.id}><p className="airframe-eyebrow">{entityTypeLabel(e)}</p><h2><a href={`/notable/${e.slug}/`}>{e.displayName}</a></h2><p>{e.description}</p><ul className="airframe-directory-list">{rows.map(a=><li key={a.id}><div><a href={`/aircraft/${a.id}/`}><strong>{aircraftLabel(a)}</strong></a><span>{a.manufacturer} {a.model}</span>{a.retired&&<small>Retired</small>}</div><button aria-label={`${ids.includes(a.id)?'Unfollow':'Follow'} ${aircraftLabel(a)}`} aria-pressed={ids.includes(a.id)} onClick={()=>onToggle(a.id)}>{ids.includes(a.id)?'Following':'Follow'}</button></li>)}</ul><a href={`/notable/${e.slug}/`}>View aircraft and sources →</a></article>;})}</div>{!entities.length&&<section className="airframe-card"><h2>No matching collections</h2><p>Try a team, organization or registration, or clear your filters.</p><button onClick={()=>update('','All')}>Clear filters</button></section>}<details><summary>How this directory is curated</summary><p>Every aircraft association requires a reviewed public source. Registrations, operator history and live observations are separate. A source documents a relationship at a particular time; it does not guarantee current ownership, paint scheme or tracking coverage. Personal live-location directories are excluded.</p><p>Browsing these collections makes no live-tracking requests. Observation checks and optional monitoring are available on aircraft profiles.</p></details></>}</>;
}
