import {useEffect,useMemo,useState} from 'react';
import type {Aircraft,TrailPoint} from '../types';
import type {City} from '../lib/cities';
import {nearestCity} from '../lib/cities';
import {countryAt,localZone,observedDistance,type CountryShape,type ZoneReference} from '../lib/passengerGeography';
let cached:Promise<{countries:CountryShape[];zones:ZoneReference[]}>|null=null;
function geography(){return cached??=(Promise.all(['world.geojson','timezone-references.json'].map(file=>fetch(import.meta.env.BASE_URL+'data/'+file).then(r=>{if(!r.ok)throw Error();return r.json();}))).then(([world,tz])=>({countries:world.features.filter((f:any)=>['Polygon','MultiPolygon'].includes(f.geometry?.type)).map((f:any)=>({name:f.properties.NAME_EN||f.properties.ADMIN,code:f.properties.ISO_A2,polygons:f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates})),zones:tz.zones})).catch(e=>{cached=null;throw e;}));}
export function PassengerGeography({aircraft:a,points,cities,now}:{aircraft:Aircraft;points:TrailPoint[];cities:City[];now:number}){
 const [data,setData]=useState<Awaited<ReturnType<typeof geography>>|null>(null),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);useEffect(()=>{let alive=true;setFailed(false);geography().then(d=>{if(alive)setData(d);}).catch(()=>{if(alive)setFailed(true);});return()=>{alive=false;};},[attempt]);
 const place=useMemo(()=>a.lon===null||a.lat===null?null:nearestCity(cities,a.lon,a.lat),[a.lon,a.lat,cities]);const country=useMemo(()=>data&&a.lon!==null&&a.lat!==null?countryAt(data.countries,a.lon,a.lat):null,[data,a.lon,a.lat]);const zone=useMemo(()=>data&&a.lon!==null&&a.lat!==null?localZone(data.zones,a.lon,a.lat,country?.code):null,[data,a.lon,a.lat,country]);const distance=useMemo(()=>observedDistance(points),[points]);let local='Unavailable';try{if(zone)local=new Intl.DateTimeFormat('en-GB',{timeZone:zone.zone,hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short',timeZoneName:'short'}).format(now);}catch{}
 return <details className="identity-details" open><summary>Below the aircraft</summary><dl className="identity-grid"><div><dt>Mapped country</dt><dd>{!data?(failed?'Geography unavailable':'Loading geography…'):country?.name??'Over water or outside mapped land'}</dd></div><div><dt>Nearest reference city</dt><dd>{place?`${place.city.name} · ${place.km} km ${place.direction}`:'Unavailable'}</dd></div><div><dt>Approximate local time</dt><dd>{country?local:'UTC '+new Date(now).toISOString().slice(11,16)}{country&&zone&&<small> · {zone.zone}</small>}</dd></div><div><dt>Observed distance</dt><dd>{distance.km.toFixed(1)} km · {distance.gaps} gaps excluded</dd></div></dl><p>Country boundaries are coarse reference data. Local time uses the nearest IANA timezone reference within the mapped country, so it may differ near timezone boundaries. Distance covers retained fixes since {points[0]?new Date(points[0].time).toISOString().slice(11,19)+' UTC':'tracking began'}, excluding unobserved gaps.</p>{failed&&<button onClick={()=>setAttempt(n=>n+1)}>Retry geography</button>}</details>;
}
