import {problemSnapshot,downloadProblemSnapshot,recordFeedTiming} from '../lib/problemSnapshot';
import {readRenderStats} from '../lib/renderDiagnostics';
import {useEffect,useState,useRef} from 'react';
import type * as Cesium from 'cesium';
export function PerformanceMonitor({viewer,quality,automatic,feed}:{viewer:Cesium.Viewer|null;quality:string;automatic:string|null;feed:{error:string;updatedAt:number|null}}){
 useEffect(()=>{if(viewer)recordFeedTiming(viewer,!!feed.error,feed.updatedAt);},[viewer,feed.error,feed.updatedAt]);
 const diagnostics=viewer?readRenderStats(viewer):null;
 const dialog=useRef<HTMLDialogElement>(null);
 const [open,setOpen]=useState(false),[stats,setStats]=useState({fps:0,models:0,entities:0}),[provider,setProvider]=useState<number|null>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 useEffect(()=>{if(!open||!viewer||viewer.isDestroyed())return;let frames=0,start=performance.now();const remove=viewer.scene.postRender.addEventListener(()=>frames++);const timer=setInterval(()=>{if(viewer.isDestroyed())return;const now=performance.now(),all=[...viewer.entities.values];for(let i=0;i<viewer.dataSources.length;i++)all.push(...viewer.dataSources.get(i).entities.values);setStats({fps:Math.round(frames*1000/(now-start)),models:all.filter(e=>e.show&&e.model?.show?.getValue(viewer.clock.currentTime)!==false&&e.model).length,entities:all.filter(e=>e.show).length});frames=0;start=now;},2000);return()=>{remove();clearInterval(timer);};},[viewer,open]);
 useEffect(()=>{if(!open)return;const c=new AbortController();const poll=async()=>{if(document.hidden)return;try{const r=await fetch('/api/status',{signal:AbortSignal.any([c.signal,AbortSignal.timeout(5000)])});const d=await r.json();if(!r.ok||!Number.isFinite(d.meanProviderMs))throw Error();if(!c.signal.aborted)setProvider(d.meanProviderMs);}catch{if(!c.signal.aborted)setProvider(null);}};void poll();const timer=setInterval(poll,10000);return()=>{c.abort();clearInterval(timer);};},[open]);
 return <div className="performance-monitor"><div className="map-tool-row"><button aria-describedby="map-performance-help" aria-expanded={open} onClick={()=>setOpen(!open)}>Performance</button><small id="map-performance-help">Check rendering speed and feed response.</small></div>{open&&<dialog ref={dialog} className="data-dialog utility-dialog" aria-label="Performance monitor" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><h3>Performance monitor</h3><dl><dt>Rendered frames / second</dt><dd>{stats.fps}</dd><dt>Enabled model entities</dt><dd>{stats.models}</dd><dt>Visible-enabled entities</dt><dd>{stats.entities}</dd><dt>Browser frame time · 95th percentile</dt><dd>{Math.round(diagnostics?.p95??0)} ms</dd><dt>Frames over 50 ms</dt><dd>{diagnostics?.slowPercent??0}%</dd><dt>Models loading / over 5 seconds</dt><dd>{diagnostics?.pendingModels??0} / {diagnostics?.slowModels??0}</dd><dt>Last model load</dt><dd>{Math.round(diagnostics?.lastModelMs??0)} ms</dd><dt>Graphics quality</dt><dd>{quality}</dd><dt>Mean upstream response</dt><dd>{provider===null?'Unavailable':`${Math.round(provider)} ms`}</dd><dt>Area fetch age</dt><dd>{feed.updatedAt===null?'Unavailable':`${Math.max(0,Math.round((Date.now()-feed.updatedAt)/1000))} s`}</dd></dl><p>{diagnostics?.backgroundLimited?'Background model detail temporarily reduced; watched aircraft retained. ':''}{automatic?`Automatically reduced to ${automatic}: sustained slow browser frame scheduling. Your saved preference is unchanged.`:'No quality reduction this session. Automatic quality can reduce nearby background models during frame pressure while keeping the watched aircraft.'}</p><small>Idle or hidden views render fewer frames. Entity counts include offscreen objects; model counts are enabled models, not GPU draw calls. Provider latency is the server-wide mean, not position age.</small>{feed.error&&<p>{feed.error}</p>}<button disabled={!viewer||viewer.isDestroyed()} onClick={()=>{if(viewer&&!viewer.isDestroyed())downloadProblemSnapshot(problemSnapshot(viewer,quality,automatic));}}>Download problem snapshot</button><small>Downloads camera, rendering and recent feed timing diagnostics to your device. Nothing is uploaded.</small><button onClick={()=>setOpen(false)}>Close performance</button></dialog>}</div>;
}
