import {useEffect,useState} from 'react';
import {AIRPORTS,type Aircraft} from '../types';
import {airlineNames} from '../lib/aircraft';
import {sanitizeFavorites,type Favorites} from '../lib/discovery';
const key='skyward.favorites.v1';
export function PersonalFavorites({airport,rows,selected,go,view,lookup}:{airport:string;rows:Aircraft[];selected:Aircraft|null;go:(id:string)=>void;view:(a:Aircraft)=>void;lookup:(hex:string)=>Promise<Aircraft|null>}){
 const [value,setValue]=useState<Favorites>(()=>{try{return sanitizeFavorites(JSON.parse(localStorage.getItem(key)??'{}'));}catch{return sanitizeFavorites(null);}}),[operator,setOperator]=useState('THY'),[hex,setHex]=useState(selected?.hex??''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(value));setNotice('');}catch{setNotice('Storage unavailable: favorites will last only while this panel remains open.');}},[value]);
 const available=[...new Map([...rows,...(selected?[selected]:[])].map(a=>[a.hex,a])).values()];const chosen=available.find(a=>a.hex===hex);
 const find=async(id:string)=>{setBusy(id);try{const a=await lookup(id);if(a)view(a);else setNotice('No current observation for that saved aircraft.');}catch{setNotice('Lookup unavailable; your saved aircraft is unchanged.');}finally{setBusy('');}};
 return <section className="personal-favorites"><h3>Favorite airports, airlines &amp; aircraft</h3><p>Stored on this device, with up to 50 entries of each kind. Saving a favorite does not start background tracking.</p>{notice&&<p role="status" className="warning">{notice}</p>}<div className="discovery-grid"><section><h4>Airports</h4><button className="quiet-button" disabled={value.airports.includes(airport)||value.airports.length>=50} onClick={()=>setValue(v=>({...v,airports:[...v.airports,airport]}))}>Save {airport} as favorite</button><ul className="favorite-list">{value.airports.map(id=><li key={id}><button className="text-button" onClick={()=>go(id)}>{id} · {AIRPORTS[id].city||AIRPORTS[id].name}</button><button aria-label={`Remove favorite airport ${id}`} onClick={()=>setValue(v=>({...v,airports:v.airports.filter(a=>a!==id)}))}>×</button></li>)}</ul></section><section><h4>Airlines</h4><label>Favorite airline<select aria-label="Favorite airline" value={operator} onChange={e=>setOperator(e.target.value)}>{Object.entries(airlineNames).map(([id,name])=><option key={id} value={id}>{name} · {id}</option>)}</select></label><button className="quiet-button" disabled={value.airlines.includes(operator)||value.airlines.length>=50} onClick={()=>setValue(v=>({...v,airlines:[...v.airlines,operator]}))}>Save airline</button><ul className="favorite-list">{value.airlines.map(id=><li key={id}><span>{airlineNames[id]??id}<small>{available.filter(a=>a.callsign.startsWith(id)).length} received this session</small></span><button aria-label={`Remove favorite airline ${id}`} onClick={()=>setValue(v=>({...v,airlines:v.airlines.filter(a=>a!==id)}))}>×</button></li>)}</ul>{value.airlines.flatMap(id=>available.filter(a=>a.callsign.startsWith(id)).slice(0,5)).map(a=><button key={a.hex} className="quiet-button" onClick={()=>view(a)}>{a.callsign} · view last observation</button>)}</section></div><section><h4>Aircraft</h4><label>Choose a received aircraft<select aria-label="Favorite aircraft" value={hex} onChange={e=>setHex(e.target.value)}><option value="">Choose aircraft</option>{available.map(a=><option key={a.hex} value={a.hex}>{a.callsign||a.registration||a.hex} · {a.registration||a.hex}</option>)}</select></label><button className="quiet-button" disabled={!chosen||value.aircraft.some(a=>a.hex===hex)||value.aircraft.length>=50} onClick={()=>chosen&&setValue(v=>({...v,aircraft:[...v.aircraft,{hex:chosen.hex,label:chosen.registration||chosen.callsign||chosen.hex}]}))}>Save aircraft</button><ul className="favorite-list">{value.aircraft.map(a=><li key={a.hex}><span>{a.label} · {a.hex}</span><button className="text-button" disabled={!!busy} onClick={()=>void find(a.hex)}>{busy===a.hex?'Looking up…':'Find latest'}</button><button aria-label={`Remove favorite aircraft ${a.hex}`} onClick={()=>setValue(v=>({...v,aircraft:v.aircraft.filter(x=>x.hex!==a.hex)}))}>×</button></li>)}</ul></section></section>;
}
