import {useRef,useState} from 'react';
import {sessionHealth} from '../lib/sessionHealth';
export function ProblemReport({count,failed}:{count:number;failed:number}){
 const dialog=useRef<HTMLDialogElement>(null),[description,setDescription]=useState(''),[review,setReview]=useState(false),[attach,setAttach]=useState(true),[diagnostics,setDiagnostics]=useState(''),[message,setMessage]=useState('');
 const open=()=>{setReview(false);setMessage('');setDiagnostics(JSON.stringify({version:1,page:location.pathname,browser:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight},online:navigator.onLine,session:sessionHealth(),traffic:{count,failed},capturedAt:new Date().toISOString()},null,2));dialog.current?.showModal();};
 const payload=()=>JSON.stringify({product:'Skyward',description:description.trim(),...(attach?{diagnostics:JSON.parse(diagnostics)}:{})},null,2);
 const validate=()=>{try{if(attach)JSON.parse(diagnostics);setMessage('');setReview(true);}catch{setMessage('Diagnostics must be valid JSON. Fix the text or uncheck Attach diagnostics.');}};
 return <><button className="quiet-button" onClick={open}>Report a problem</button><dialog ref={dialog} className="problem-report" aria-labelledby="problem-report-title"><header><h2 id="problem-report-title">Report a problem</h2><button aria-label="Close problem report" onClick={()=>dialog.current?.close()}>×</button></header><p>Describe what happened and what you expected. Remove any personal information before sharing.</p><label>What happened?<textarea aria-label="Problem description" maxLength={4000} value={description} onChange={e=>{setDescription(e.target.value);setReview(false);}} placeholder="Steps to reproduce, expected result and what you saw…"/></label><label className="report-checkbox"><input type="checkbox" checked={attach} onChange={e=>{setAttach(e.target.checked);setReview(false);}}/>Attach technical diagnostics</label>{attach&&<details open={review}><summary>Review and edit diagnostics</summary><textarea aria-label="Problem report diagnostics" value={diagnostics} onChange={e=>{setDiagnostics(e.target.value);setReview(false);}} spellCheck={false}/></details>}<p className="muted">Diagnostics exclude account details, keys, precise map coordinates and browsing history. No report is sent automatically. Export it to share with your support contact.</p>{message&&<p role="status">{message}</p>}{review?<><p role="status">Report ready. Only the description and checked diagnostics will be included.</p><button onClick={async()=>{try{await navigator.clipboard.writeText(payload());setMessage('Report copied.');}catch{setMessage('Clipboard unavailable; download the report instead.');}}}>Copy reviewed report</button><button onClick={()=>{const url=URL.createObjectURL(new Blob([payload()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='skyward-problem-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Report downloaded. Nothing was sent.');}}>Download reviewed report</button><button onClick={()=>setReview(false)}>Edit report</button></>:<button disabled={!description.trim()} onClick={validate}>Review report</button>}</dialog></>;
}
