import {ageSeconds,duration} from '../lib/aircraft';
import {loadAirframeCatalog} from '../lib/airframeLibrary';
import {catalogSearch,type Catalog} from '../lib/airframeCatalog';
import {searchRoute,matchesFlightSearch,recentSearches,emptySearch,type SearchFields} from '../lib/flightSearch';
import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import {AIRPORTS,type Aircraft} from '../types';
import {sanitizeFavorites} from '../lib/discovery';
export function QuickSearch({rows,select,airport,actions,onOpen,lookup,remote}:{remote:(kind:string,query:string)=>Promise<void>;lookup:(hex:string)=>Promise<void>;rows:Aircraft[];select:(a:Aircraft)=>void;airport:(id:string)=>void;actions:{name:string;run:()=>void}[];onOpen:(v:boolean)=>void}){
 const [fields,setFields]=useState<SearchFields>({...emptySearch}),[recent,setRecent]=useState<SearchFields[]>(()=>{try{return recentSearches(JSON.parse(localStorage.getItem('skyward.searches.v1')??'[]'));}catch{return [];}});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[index,setIndex]=useState(0);const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!el.closest('input,textarea,select,[contenteditable="true"],dialog')){e.preventDefault();setOpen(true);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{onOpen(open);if(open){dialog.current?.showModal();input.current?.focus();}else dialog.current?.close();},[open,onOpen]);
 const [catalog,setCatalog]=useState<Catalog|null>(null);
 useEffect(()=>{if(open&&!catalog)loadAirframeCatalog().then(setCatalog).catch(()=>{});},[open,catalog]);
 const deferredQuery=useDeferredValue(query);
 const favorites=useMemo(()=>{try{return sanitizeFavorites(JSON.parse(localStorage.getItem('skyward.favorites.v1')??'{}'));}catch{return sanitizeFavorites(null);}},[open]);
 const results=useMemo(()=>{const q=deferredQuery.trim().toLowerCase(),filtered=!!(fields.airline||fields.type||fields.registration||fields.origin||fields.destination);const flights=[...new Map(rows.map(a=>[a.hex,a])).values()].filter(a=>matchesFlightSearch(a,{...fields,text:deferredQuery})).sort((a,b)=>Number(favorites.aircraft.some(f=>f.hex===b.hex)||favorites.airlines.some(f=>b.callsign.startsWith(f)))-Number(favorites.aircraft.some(f=>f.hex===a.hex)||favorites.airlines.some(f=>a.callsign.startsWith(f)))).slice(0,12).map(a=>({name:`Flight · ${a.callsign||a.hex} · ${a.registration||a.aircraftType} · ${a.simulation?'Simulated':'Last observation '+duration(ageSeconds(a,Date.now()))}${searchRoute(a)?' · '+searchRoute(a)!.airports.map(p=>p.iata||p.icao).join(' → '):''} ${favorites.aircraft.some(f=>f.hex===a.hex)?'★':''}`,run:()=>select(a)}));const ports=(filtered?[]:Object.entries(AIRPORTS)).filter(([id,a])=>`${id} ${a.icao} ${a.name} ${a.city} ${a.country}`.toLowerCase().includes(q)).sort(([a,aa],[b,bb])=>(Number(b.toLowerCase()===q||bb.icao?.toLowerCase()===q)-Number(a.toLowerCase()===q||aa.icao?.toLowerCase()===q))*10+Number(favorites.airports.includes(b))-Number(favorites.airports.includes(a))).slice(0,12).map(([id,a])=>({name:`Airport · ${id} · ${a.name} ${favorites.airports.includes(id)?'★':''}`,run:()=>airport(id)}));const saved=(filtered?[]:favorites.aircraft).filter(f=>!rows.some(a=>a.hex===f.hex)&&`${f.label} ${f.hex}`.toLowerCase().includes(q)).map(f=>({name:`Saved aircraft · ${f.label} · ${f.hex} ★ · find latest`,run:()=>lookup(f.hex)}));const exact=q.toUpperCase(),remoteResults=!filtered&&/^[A-Z0-9-]{2,12}$/.test(exact)?[{name:`Look up callsign · ${exact}`,run:()=>remote('callsign',exact)},{name:`Look up registration · ${exact}`,run:()=>remote('registration',exact)}]:[];return [...(filtered?[]:actions).filter(a=>a.name.toLowerCase().includes(q)),...saved,...flights,...(catalog?catalogSearch(catalog,q).slice(0,6).map(a=>({name:`Aircraft · ${a.registrations.at(-1)?.value??a.id} · ${a.manufacturer} ${a.model}`,run:()=>{location.href=`/aircraft/${a.id}/`;}})):[]),...(catalog?.entities.filter(e=>e.displayName.toLowerCase().includes(q)).slice(0,4).map(e=>({name:`Notable entity · ${e.displayName}`,run:()=>{location.href=`/notable/${e.slug}/`;}}))??[]),...ports,...remoteResults];},[catalog,rows,deferredQuery,fields,favorites,actions,select,airport,lookup,remote]);
 const close=()=>{setError('');setOpen(false);setQuery('');setFields({...emptySearch});setIndex(0);trigger.current?.focus();};const choose=async(n:number)=>{const result=results[n];if(!result||busy||query!==deferredQuery)return;setBusy(true);setError('');try{await result.run();const entry={...fields,text:query.trim()},next=recentSearches([entry,...recent.filter(r=>JSON.stringify(r)!==JSON.stringify(entry))]);setRecent(next);try{localStorage.setItem('skyward.searches.v1',JSON.stringify(next));}catch{/* Search continues without persistence. */}close();}catch(e){setError(e instanceof Error?e.message:'Lookup unavailable.');}finally{setBusy(false);}};
 useEffect(()=>{dialog.current?.querySelector('.search-active')?.scrollIntoView({block:'nearest'});},[index]);
 return <><button ref={trigger} className="quiet-button search-trigger" onClick={()=>setOpen(true)}>Search /</button>{open&&<dialog ref={dialog} className="data-dialog quick-search" aria-label="Search Skyward" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="dialog-heading"><h2>Search Skyward</h2><button aria-label="Close search" onClick={close}>×</button></div><input ref={input} aria-label="Search airports, flights and controls" value={query} maxLength={100} placeholder="Callsign, airline, aircraft, city or airport…" onChange={e=>{setQuery(e.target.value);setIndex(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(results.length-1,i+1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();choose(Math.min(index,results.length-1));}}}/><div className="search-fields">{(['airline','type','registration','origin','destination'] as const).map(k=><label key={k}>{k==='type'?'Aircraft type':k==='airline'?'Airline':k==='origin'?'Origin':k==='destination'?'Destination':'Registration'}<input aria-label={`Search ${k}`} value={fields[k]} maxLength={100} onChange={e=>{setFields(f=>({...f,[k]:e.target.value}));setIndex(0);}}/></label>)}</div><button className="text-button" onClick={()=>{setQuery('');setFields({...emptySearch});setIndex(0);}}>Clear search filters</button>{!query&&!Object.values(fields).some(Boolean)&&recent.length>0&&<section aria-label="Recent searches"><h3>Recent searches</h3><div className="recent-searches">{recent.map((r,i)=><button key={i} onClick={()=>{setQuery(r.text);setFields(r);setIndex(0);}}>{Object.values(r).filter(Boolean).join(' · ')}</button>)}</div><button onClick={()=>{setRecent([]);try{localStorage.removeItem('skyward.searches.v1');}catch{}}}>Clear recent searches</button></section>}<p>↑ ↓ then Enter · Escape to close. Favorites appear first within each group. Listed flights are received observations. Use “Look up callsign” or “Look up registration” to request a current match beyond this area. Origin and destination match routes opened in this session within the last 30 minutes; flights with unknown routes are excluded by route filters.</p>{busy&&<p role="status">Finding latest observation…</p>}{error&&<p role="alert">{error}</p>}<ul aria-busy={query!==deferredQuery}>{results.map((r,i)=><li key={r.name}><button disabled={busy||query!==deferredQuery} className={index===i?'search-active':''} onFocus={()=>setIndex(i)} onClick={()=>choose(i)}>{r.name}</button></li>)}</ul>{!results.length&&<p>No matching received flights, airports or commands. All entered flight filters must match. Clear a filter, try a callsign or registration, or move the map to receive another area. This search does not contain every flight worldwide.</p>}</dialog>}</>;
}
