import {fleetUri} from '../lib/flightPresentation';
import {aircraftModelAttitude} from '../lib/aircraftAttitude';
import {contiguous} from '../lib/positionQuality';
import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import {sessionFrame,type Recording} from '../lib/sessionRecording';
export function RecordedInspection({viewer,recording,time}:{viewer:Cesium.Viewer|null;recording:Recording;time:number}){
 const model=useRef<Cesium.Entity|null>(null);
 const [hex,setHex]=useState(''),[camera,setCamera]=useState('free');const frame=useMemo(()=>sessionFrame(recording,time),[recording,time]);const a=frame.find(a=>a.hex===hex),track=recording.tracks.find(t=>t.identity.hex===hex);
 useEffect(()=>{const pick=(e:Event)=>{const id=(e as CustomEvent).detail;if(recording.tracks.some(t=>t.identity.hex===id)){setHex(id);setCamera('side');}};addEventListener('skyward-replay-select',pick);return()=>removeEventListener('skyward-replay-select',pick);},[recording]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed()||!track)return;const C=window.Cesium;const entity=viewer.entities.add({id:'replay-cinematic-aircraft',model:{uri:'/watch/'+fleetUri(track.identity),scale:1,minimumPixelSize:0,maximumScale:1}});model.current=entity;return()=>{if(!viewer.isDestroyed())viewer.entities.remove(entity);model.current=null;};},[viewer,track]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed()||!model.current)return;const C=window.Cesium;model.current.show=!!a;if(!a)return;const p=C.Cartesian3.fromDegrees(a.lon!,a.lat!,Math.max(0,a.altitude??0)*.3048+8);model.current.position=new C.ConstantPositionProperty(p);model.current.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(p,new C.HeadingPitchRoll(...aircraftModelAttitude(a.heading??0,0,0))));viewer.scene.requestRender();},[viewer,a]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed())return;const C=window.Cesium,h=new C.ScreenSpaceEventHandler(viewer.canvas);h.setInputAction((e:{position:Cesium.Cartesian2})=>{const ids=viewer.scene.drillPick(e.position,12).map(p=>p?.id?.id);const id=ids.find(id=>recording.tracks.some(t=>t.identity.hex===id));if(id)setHex(id);},C.ScreenSpaceEventType.LEFT_CLICK);return()=>h.destroy();},[viewer,recording]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed()||!track)return;const C=window.Cesium,entities:Cesium.Entity[]=[];const pts=track.points.filter(p=>p.time<=time);if(a&&pts.length&&a.observedAt!>pts[pts.length-1].time)pts.push({lat:a.lat!,lon:a.lon!,altitude:a.altitude??0,time:a.observedAt!,ground:a.ground,groundSpeed:a.groundSpeed});let segment:typeof pts=[];const flush=()=>{if(segment.length>1)entities.push(viewer.entities.add({polyline:{positions:segment.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,Math.max(0,p.altitude)*.3048+8)),width:3,material:C.Color.fromCssColorString('#c3abff')}}));segment=[];};for(const p of pts){if(segment.length&&!contiguous(segment[segment.length-1],p))flush();segment.push(p);}flush();viewer.scene.requestRender();return()=>{if(!viewer.isDestroyed()){entities.forEach(e=>viewer.entities.remove(e));viewer.scene.requestRender();}};},[viewer,track,time,a]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed()||!a||camera==='free')return;const C=window.Cesium,position=viewer.dataSources.getByName('recorded-session')[0]?.entities.getById(a.hex)?.position?.getValue(viewer.clock.currentTime);if(!position)return;viewer.camera.cancelFlight();viewer.camera.lookAt(position,new C.HeadingPitchRange(((a.heading??0)+(camera==='side'?90:0))*Math.PI/180,camera==='bird'?-1.45:-.25,camera==='bird'?500:160));viewer.camera.lookAtTransform(C.Matrix4.IDENTITY);viewer.scene.requestRender();},[viewer,a,camera]);
 useEffect(()=>{if(!viewer||viewer.isDestroyed())return;const release=()=>setCamera('free');viewer.canvas.addEventListener('pointerdown',release);return()=>viewer.canvas.removeEventListener('pointerdown',release);},[viewer]);
 return <section className="recorded-inspection" aria-label="Recorded aircraft inspection"><label>Inspect recorded aircraft<select aria-label="Recorded aircraft" value={hex} onChange={e=>setHex(e.target.value)}><option value="">Click a plane or choose…</option>{recording.tracks.map(t=><option key={t.identity.hex} value={t.identity.hex}>{t.identity.callsign||t.identity.hex} · {t.identity.aircraftType||'type unknown'}</option>)}</select></label>{track&&<><label>Replay camera<select aria-label="Replay camera" value={camera} onChange={e=>setCamera(e.target.value)}><option value="free">Free camera</option><option value="side">Side view</option><option value="bird">Bird view</option></select></label><strong>{track.identity.callsign||hex} · {track.identity.registration||hex}</strong><p>{track.identity.aircraftType||'Unknown aircraft type'} · recorded identity</p>{a?<p>{a.lat?.toFixed(4)}°, {a.lon?.toFixed(4)}° · {Math.round(a.altitude??0).toLocaleString()} ft · {a.groundSpeed==null?'Speed unavailable':`${Math.round(a.groundSpeed)} kt`}<br/>{a.ground?'On ground':'Airborne'} · {Math.round((time-a.observedAt!)/1000)}s position age</p>:<p>No usable position at this playback time.</p>}<small>Trail ends at playback time. Gaps over two minutes remain disconnected. Identity is the last identity saved for this track.</small><button onClick={()=>setHex('')}>Close recorded details</button></>}</section>;
}
