import {replayInterval,replayCamera} from '../lib/replayEdit';
import {recordingBounds} from '../lib/sessionRecording';
import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import {replayHighlights} from '../lib/replayHighlights';
import {recordReplayClip} from '../lib/replayClip';
import {accountRequest,type Account} from '../lib/membership';
import type {Recording} from '../lib/sessionRecording';
export function ReplayHighlights({viewer,recording,jump}:{viewer:Cesium.Viewer|null;recording:Recording;jump:(t:number)=>void}){
 const bounds=recordingBounds(recording),duration=(bounds.end-bounds.start)/1000;
 const [start,setStart]=useState(0),[end,setEnd]=useState(duration),[portrait,setPortrait]=useState(false),[title,setTitle]=useState(recording.name),[sequence,setSequence]=useState('side-bird'),[track,setTrack]=useState(recording.tracks[0].identity.hex);
 const [seconds,setSeconds]=useState(10),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const capture=useRef<AbortController|null>(null),pending=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;capture.current?.abort();};},[]);const highlights=useMemo(()=>replayHighlights(recording),[recording]);
 async function exportClip(){if(!viewer||pending.current)return;pending.current=true;setBusy(true);setMessage('');try{const a=await accountRequest<Account>('/api/account');if(!alive.current)return;if(!a.user?.premium)throw Error('Premium is required to export a video highlight.');const interval=replayInterval(recording,start,end);jump(interval.start);window.dispatchEvent(new CustomEvent('skyward-replay-select',{detail:track}));const controller=new AbortController();capture.current=controller;const blob=await recordReplayClip(viewer,seconds,controller.signal,`${recording.source||'User-supplied recording'} · ${recording.license||'License not supplied'}`,{portrait,title,frame:progress=>{jump(interval.start+(interval.end-interval.start)*progress);window.dispatchEvent(new CustomEvent('skyward-replay-camera',{detail:replayCamera(progress,sequence)}));}}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='skyward-replay.'+(blob.type.includes('mp4')?'mp4':'webm');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Clip saved locally.');}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'Export failed.');}finally{capture.current=null;pending.current=false;if(alive.current)setBusy(false);}}
 return <details><summary>Cinematic highlights · Premium</summary><p>Transitions are inferred from consecutive recorded ground flags, not confirmed runway events.</p><div className="replay-highlights">{highlights.map(h=><button key={h.hex+':'+h.time} onClick={()=>{jump(h.time-10000);window.dispatchEvent(new CustomEvent('skyward-replay-select',{detail:h.hex}));}}>{h.callsign} · {h.kind}</button>)}</div>{!highlights.length&&<p>No continuous takeoff or landing transition was recorded.</p>}<div className="replay-editor"><label>Clip aircraft<select value={track} disabled={busy} onChange={e=>setTrack(e.target.value)}>{recording.tracks.map(t=><option key={t.identity.hex} value={t.identity.hex}>{t.identity.callsign||t.identity.hex}</option>)}</select></label><label>Trim start (seconds)<input type="number" min="0" max={duration} value={start} disabled={busy} onChange={e=>setStart(Number(e.target.value))}/></label><label>Trim end (seconds)<input type="number" min="0" max={duration} value={end} disabled={busy} onChange={e=>setEnd(Number(e.target.value))}/></label><label>Route title<input value={title} maxLength={80} disabled={busy} onChange={e=>setTitle(e.target.value)}/></label><label>Camera sequence<select value={sequence} disabled={busy} onChange={e=>setSequence(e.target.value)}><option value="side-bird">Side → bird</option><option value="bird-side">Bird → side</option><option value="side">Side</option><option value="bird">Bird</option></select></label><label>Video format<select value={portrait?'portrait':'landscape'} disabled={busy} onChange={e=>setPortrait(e.target.value==='portrait')}><option value="landscape">Landscape</option><option value="portrait">Portrait 9:16</option></select></label></div><label>Clip duration<select value={seconds} disabled={busy} onChange={e=>setSeconds(Number(e.target.value))}>{[10,20,30].map(n=><option key={n} value={n}>{n} seconds</option>)}</select></label><button disabled={busy||!viewer} onClick={()=>void exportClip()}>{busy?'Recording visible replay…':'Export video highlight'}</button>{busy&&<button onClick={()=>capture.current?.abort()}>Cancel video export</button>}<p className="clip-notice">Records this map and camera on your device. The selected interval plays automatically during export; long intervals are accelerated. Portrait keeps the full map with letterboxing. No cloud upload or audio capture.</p>{message&&<p role="status">{message}</p>}</details>;
}
