import {RouteUnits,useRouteSettings} from './RouteSettings';
import {routeDistance} from '../lib/routeUnits';
import {FlightMiniMap} from './FlightMiniMap';
import {routeOverview} from '../lib/routeOverview';
import type {Aircraft,FlightRoute,TrailPoint} from '../types';
export function RouteOverview({aircraft,route,trail,now,loading,error,showRoute}:{aircraft:Aircraft;route:FlightRoute|null;trail:TrailPoint[];now:number;loading:boolean;error:string;showRoute:()=>void}){
 const {unit,viewAirport}=useRouteSettings();const distance=(n:number)=>`${routeDistance(n,unit).toLocaleString()} ${unit}`;
 const r=routeOverview(route,aircraft,trail,now);
 if(loading)return <section className="route-overview" aria-label="Flight route overview"><p>Looking up origin and destination…</p></section>;
 if(!r)return <section className="route-overview" aria-label="Flight route overview"><h3>Flight route</h3><p>{route?.status==='POSITION_MISMATCH'?'The route record does not match this aircraft’s position. Current itinerary is unconfirmed.':route&&route.airports.length>2?'Multiple route legs reported; the current leg is unknown.':error||'No origin and destination reported for this callsign.'}</p>{route&&route.airports.length>0&&<p>{route.airports.map(p=>p.iata||p.icao).join(' → ')} · provider record only</p>}</section>;
 const fresh=aircraft.observedAt!==null&&now-aircraft.observedAt<=30000;
 return <section className="route-overview" aria-label="Flight route overview"><div className="route-overview-heading"><h3>Flight route</h3><span>{route!.status==='PLAUSIBLE'?'Estimated callsign route':'Unverified callsign route'}</span></div><div className="route-endpoints">{[r.origin,r.destination].map((p,i)=><div key={i}><small>{i?'Destination':'Origin'}</small><button className="route-airport-link" onClick={()=>viewAirport(p)} aria-label={`View ${i?'destination':'origin'} airport ${p.iata||p.icao}`}><strong>{p.iata||p.icao}</strong></button><b>{p.city||p.name}</b><span>{p.name}</span></div>)}</div><div className="route-position" aria-label="Estimated geographic position along airport pair"><span style={{left:`${Math.max(3,Math.min(97,r.fraction*100))}%`}}>✈</span></div><p className="route-position-note">Geographic position between route airports · not flight-time progress</p><FlightMiniMap aircraft={aircraft} cities={[]} route={route} trail={trail} routeView/><RouteUnits/><div className="route-distance-grid"><div><small>To destination · direct</small><strong>{distance(r.remaining)}</strong></div><div><small>Observed session track</small><strong>{distance(r.observed)}</strong></div><div><small>Airport-to-airport · direct</small><strong>{distance(r.total)}</strong></div></div><p>{aircraft.ground?'Reported on ground':fresh?'Recent airborne position':'Last received position'} · {aircraft.observedAt?new Date(aircraft.observedAt).toISOString().slice(11,19)+' UTC':'time unavailable'}{r.gaps?` · ${r.gaps} gaps excluded from observed distance`:''}</p><p className="route-data-limit">Scheduled departure, arrival ETA and gates are not supplied by this feed. Dashed paths are geographic estimates, not a filed flight plan.</p><div className="route-overview-actions"><button className="quiet-button" onClick={showRoute}>Show full route</button><small>{route!.source} · lookup {new Date(route!.fetchedAt).toISOString().slice(11,19)} UTC</small></div></section>;
}
