import {useEffect,useRef} from 'react';
import type * as Cesium from 'cesium';
import type {Aircraft,FlightRoute,TrailPoint} from '../types';
import {coloredTrail} from '../lib/positionQuality';
import {routeArc,splitRouteProgress} from '../lib/routeOverview';
export function RouteLayer({viewer,route,aircraft,trail,active,follow=false}:{viewer:Cesium.Viewer|null;route:FlightRoute|null;aircraft:Aircraft|null;trail:TrailPoint[];active:boolean;follow?:boolean}){
 const progress=useRef({key:'',fraction:0});
 useEffect(()=>{if(!active||!viewer||viewer.isDestroyed()||!route||route.airports.length!==2||!['PLAUSIBLE','UNVERIFIED'].includes(route.status))return;const C=window.Cesium,entities:Cesium.Entity[]=[];const line=(points:{lat:number;lon:number;altitude?:number}[],color:string,dashed:boolean)=>{if(points.length<2)return;entities.push(viewer.entities.add({polyline:{positions:points.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,p.altitude==null?5000:Math.max(0,p.altitude)*.3048+20)),width:dashed?2:3,material:dashed?new C.PolylineDashMaterialProperty({color:C.Color.fromCssColorString(color),dashLength:14}):C.Color.fromCssColorString(color)}}));};if(follow){const key=JSON.stringify([aircraft?.hex,route.callsign,route.airports.map(a=>[a.icao,a.iata,a.lat,a.lon])]);if(progress.current.key!==key)progress.current={key,fraction:0};const parts=splitRouteProgress(routeArc(route.airports[0],route.airports[1]),aircraft?.lat!=null&&aircraft.lon!=null?{lat:aircraft.lat,lon:aircraft.lon}:null,progress.current.fraction);progress.current.fraction=parts.fraction;line(parts.completed,'#8fdfc8',true);line(parts.ahead,'#c9a4f7',true);}else{line(routeArc(route.airports[0],route.airports[1]),'#8d9aab',true);if(aircraft?.lat!=null&&aircraft.lon!=null)line(routeArc({lat:aircraft.lat,lon:aircraft.lon},route.airports[1]),'#c9a4f7',true);}for(const s of coloredTrail(follow?[]:trail))line(s.points,s.color,false);route.airports.forEach((a,i)=>entities.push(viewer.entities.add({position:C.Cartesian3.fromDegrees(a.lon,a.lat,5000),point:{pixelSize:10,color:C.Color.fromCssColorString('#c9a4f7'),outlineColor:C.Color.BLACK,outlineWidth:2,disableDepthTestDistance:Infinity},label:{text:`${i?'TO':'FROM'} ${a.iata||a.icao} · ${a.city||a.name}`,font:'13px sans-serif',pixelOffset:new C.Cartesian2(0,-20),showBackground:true,disableDepthTestDistance:Infinity}})));viewer.scene.requestRender();return()=>{if(!viewer.isDestroyed()){entities.forEach(e=>viewer.entities.remove(e));viewer.scene.requestRender();}};},[viewer,route,aircraft?.lat,aircraft?.lon,trail,active,follow]);return null;
}
