import {useEffect,useState} from 'react';
import {deleteSession,listSessions,renameSession,saveSession,type SavedSession} from '../lib/sessionLibrary';
import {downloadRecording,parseRecording,type Recording} from '../lib/sessionRecording';
export function SessionLibrary({current,play}:{current:Recording|null;play:(r:Recording)=>void}){
 const [rows,setRows]=useState<SavedSession[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(''),[name,setName]=useState(''),[remove,setRemove]=useState('');
 const refresh=async()=>setRows(await listSessions());useEffect(()=>{void refresh().catch(e=>setError(String(e)));},[]);
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await refresh();}catch(e){setError(e instanceof Error?e.message:'Browser storage unavailable. Export a file instead.');}finally{setBusy(false);}};
 return <section className="session-library"><h3>Saved-session library</h3><p>Stored in this browser only. Clearing site data removes these sessions; export files for a backup. Limit: 20 sessions / 100 MB.</p><p>{rows.length} saved · {(rows.reduce((n,r)=>n+r.bytes,0)/1048576).toFixed(2)} MB used by recordings</p><button className="quiet-button" disabled={!current||busy} onClick={()=>current&&void run(()=>saveSession(current))}>Keep session in browser</button>{error&&<p role="alert" className="warning">{error}</p>}<ul className="library-list">{rows.map(r=><li key={r.id}><strong>{r.name}</strong><small>{r.recording.tracks.length} aircraft · {(r.bytes/1048576).toFixed(2)} MB · {new Date(r.createdAt).toLocaleDateString()}</small><div className="tools-controls"><button disabled={busy} onClick={()=>{try{play(parseRecording(r.recording));}catch(e){setError(String(e));}}}>Replay {r.name}</button><button onClick={()=>downloadRecording(r.recording)}>Export {r.name}</button><button disabled={busy} onClick={()=>{setEdit(r.id);setName(r.name);}}>Rename {r.name}</button><button disabled={busy} onClick={()=>setRemove(r.id)}>Delete {r.name}</button></div>{edit===r.id&&<form className="inline-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await renameSession(r.id,name);setEdit('');});}}><input aria-label="Session name" value={name} maxLength={80} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()}>Save name</button><button type="button" onClick={()=>setEdit('')}>Cancel rename</button></form>}{remove===r.id&&<p>Delete this browser copy? <button disabled={busy} onClick={()=>void run(async()=>{await deleteSession(r.id);setRemove('');})}>Confirm delete</button> <button onClick={()=>setRemove('')}>Keep it</button></p>}</li>)}</ul>{!rows.length&&<p>No sessions saved in this browser yet.</p>}</section>;
}
