import {ReplayHighlights} from './ReplayHighlights';
import {RecordedInspection} from './RecordedInspection';
import {useEffect,useMemo,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import {recordingBounds,sessionFrame,type Recording} from '../lib/sessionRecording';
const planeIcon='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="#c3abff" stroke="#152334" d="M16 2c1 0 2 2 2 4v7l11 7v3l-11-4v7l4 3v2l-6-2-6 2v-2l4-3v-7L3 23v-3l11-7V6c0-2 1-4 2-4Z"/></svg>');
export function SessionReplayControls({viewer,recording,time,change,close,paused}:{viewer:Cesium.Viewer|null;recording:Recording;time:number;change:(t:number)=>void;close:()=>void;paused:boolean}){const [playing,setPlaying]=useState(true),[speed,setSpeed]=useState(10);const bounds=useMemo(()=>recordingBounds(recording),[recording]),state=useRef({time,change});state.current={time,change};useEffect(()=>{if(!playing||paused)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now(),dt=Math.min(1000,now-last);last=now;if(document.hidden)return;const next=Math.min(bounds.end,state.current.time+dt*speed);state.current.change(next);if(next>=bounds.end)setPlaying(false);},250);return()=>clearInterval(id);},[playing,paused,speed,bounds.end]);return <section className="session-playback" aria-label="Session replay controls"><strong>{recording.name} · recorded · {new Date(time).toISOString().slice(11,19)} UTC</strong><p>{recording.name.startsWith('SAMPLE ·')?'Fictional Premium preview. This sample does not represent a real flight.':'All aircraft shown are recorded observations. Gaps over two minutes are not interpolated.'}</p><input aria-label="Session playback time" type="range" min={bounds.start} max={bounds.end||1} value={time} onChange={e=>{setPlaying(false);change(Number(e.target.value));}}/><div><button onClick={()=>{if(time>=bounds.end)change(bounds.start);setPlaying(!playing);}}>{playing?'Pause session':'Play session'}</button><select aria-label="Session playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,10,60].map(s=><option key={s} value={s}>{s}×</option>)}</select><button onClick={()=>{setPlaying(false);change(bounds.start);}}>Restart replay</button><button onClick={close}>Exit session replay</button></div><ReplayHighlights key={recording.createdAt+recording.name} viewer={viewer} recording={recording} jump={t=>{setPlaying(false);change(Math.max(bounds.start,t));}}/></section>;}
export function SessionReplayLayer({viewer,recording,time,labels=true,skipInitialFrame=false}:{skipInitialFrame?:boolean;viewer:Cesium.Viewer|null;recording:Recording;time:number;labels?:boolean}){
 const source=useRef<Cesium.CustomDataSource|null>(null);useEffect(()=>{const v=viewer;if(!v||v.isDestroyed())return;const C=window.Cesium,s=new C.CustomDataSource('recorded-session');source.current=s;let alive=true;void v.dataSources.add(s).then(()=>{if(!alive&&!v.isDestroyed())v.dataSources.remove(s,true);});const timer=setTimeout(()=>{if(!alive||v.isDestroyed()||skipInitialFrame)return;if(recording.camera){const p=recording.camera;v.camera.setView({destination:C.Cartesian3.fromDegrees(p.lon,p.lat,p.height),orientation:{heading:p.heading,pitch:p.pitch,roll:p.roll}});return;}const positions=recording.tracks.map(t=>C.Cartesian3.fromDegrees(t.points[0].lon,t.points[0].lat));const sphere=C.BoundingSphere.fromPoints(positions);sphere.radius=Math.max(40000,sphere.radius);v.camera.flyToBoundingSphere(sphere,{duration:0,offset:new C.HeadingPitchRange(0,-Math.PI/2,0)});},150);return()=>{alive=false;clearTimeout(timer);if(!v.isDestroyed())v.dataSources.remove(s,true);source.current=null;};},[viewer,recording,skipInitialFrame]);
 useEffect(()=>{const v=viewer,s=source.current;if(!v||v.isDestroyed()||!s)return;const C=window.Cesium,ids=new Set<string>();for(const a of sessionFrame(recording,time)){ids.add(a.hex);let e=s.entities.getById(a.hex);if(!e)e=s.entities.add({id:a.hex,billboard:{image:planeIcon,width:22,height:22,distanceDisplayCondition:new C.DistanceDisplayCondition(0,900000)},point:{pixelSize:4,color:C.Color.fromCssColorString('#c3abff'),outlineWidth:1,outlineColor:C.Color.BLACK,distanceDisplayCondition:new C.DistanceDisplayCondition(900000,40000000)},label:{show:labels,text:a.callsign||a.hex,font:'11px sans-serif',pixelOffset:new C.Cartesian2(0,-14),fillColor:C.Color.WHITE,showBackground:true,distanceDisplayCondition:new C.DistanceDisplayCondition(0,200000)}});if(e.billboard)e.billboard.rotation=new C.ConstantProperty(-(a.heading??0)*Math.PI/180);e.position=new C.ConstantPositionProperty(C.Cartesian3.fromDegrees(a.lon!,a.lat!,Math.max(0,a.altitude??0)*.3048+8));}for(const e of [...s.entities.values])if(!ids.has(e.id))s.entities.remove(e);v.scene.requestRender();},[viewer,recording,time,labels]);
 useEffect(()=>{const v=viewer;if(!v||v.isDestroyed())return;const C=window.Cesium;let last=0;const remove=v.scene.preRender.addEventListener(()=>{const now=performance.now();if(now-last<300)return;last=now;let changed=false;const boxes:{x:number;y:number;width:number}[]=[];for(const e of source.current?.entities.values??[]){const pos=e.position?.getValue(v.clock.currentTime);if(!pos||!e.label)continue;const pt=C.SceneTransforms.worldToWindowCoordinates(v.scene,pos),width=String(e.label.text?.getValue(v.clock.currentTime)??'').length*7+8;const show=!!(labels&&pt&&pt.x>0&&pt.y>0&&pt.x<v.canvas.clientWidth&&pt.y<v.canvas.clientHeight&&C.Cartesian3.distance(pos,v.camera.positionWC)<200000&&boxes.length<40&&!boxes.some(b=>Math.abs(b.x-pt.x)<(b.width+width)/2&&Math.abs(b.y-pt.y)<22));if(show)boxes.push({x:pt!.x,y:pt!.y,width});if(e.label.show?.getValue(v.clock.currentTime)!==show){e.label.show=new C.ConstantProperty(show);changed=true;}}if(changed)v.scene.requestRender();});return()=>remove();},[viewer,labels]);return <RecordedInspection viewer={viewer} recording={recording} time={time}/>;
}
