import {useEffect,useRef,useState} from 'react';
export type SharedTravelerData={id:string;alias:string;side:'left'|'right';position:'front'|'wing'|'rear';callsign:string;date:string;from:string;to:string;hex:string|null;observedAt:number|null;expires:number;status:string};
export function SharedTraveler({watch}:{watch:(trip:SharedTravelerData)=>Promise<void>}){
 const [id]=useState(()=>new URLSearchParams(location.search).get('traveler')),[trip,setTrip]=useState<SharedTravelerData|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[compact,setCompact]=useState(false);
 const refresh=useRef<()=>Promise<SharedTravelerData|null>>(async()=>null);
 useEffect(()=>{if(!id)return;const controller=new AbortController();let pending=false;
  const load=async()=>{if(pending)return null;pending=true;try{const r=await fetch('/api/travelers/'+encodeURIComponent(id),{signal:controller.signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Shared trip unavailable.');setTrip(d);setMessage('');return d as SharedTravelerData;}catch(e){if(!controller.signal.aborted){setTrip(null);setMessage((e as Error).message);setCompact(false);}return null;}finally{pending=false;}};
  refresh.current=load;void load();const timer=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>{controller.abort();clearInterval(timer);};
 },[id]);
 if(!id)return null;
 if(compact&&trip)return <button className="shared-traveler compact" onClick={()=>setCompact(false)}>{trip.alias}’s window · simulated · Details</button>;
 return <section className="shared-traveler" aria-label="Shared traveler journey"><a href="/travelers/">← Travel together</a><h2>{trip?`${trip.alias}’s journey`:'Shared journey'}</h2>{trip&&<><strong>{trip.from||'?'} → {trip.to||'?'}</strong><p>{trip.callsign} · {trip.date}</p><small>{trip.status}{trip.observedAt?' · '+new Date(trip.observedAt).toLocaleTimeString():''}</small><p>Explore the scenery from {trip.alias}’s chosen {trip.side} window position. This is a simulated view, not a live camera or an exact seat map. Presence onboard is self-reported.</p><button disabled={busy||trip.date!==new Date().toISOString().slice(0,10)} onClick={async()=>{setBusy(true);try{const current=await refresh.current();if(!current)throw Error('This shared journey is no longer available.');await watch(current);setCompact(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Watch from {trip.alias}’s window</button>{!trip.hex&&<p>No aircraft is matched yet. On the trip’s UTC date, use Watch to look for a current observation. No flight position is invented.</p>}<small>Sharing expires {new Date(trip.expires).toLocaleString()}.</small></>}{!trip&&!message&&<p>Loading shared trip…</p>}{message&&<p role="status">{message}</p>}<a href="/?account=upgrade">Share your own journey with Premium →</a></section>;
}
