import {LoadingSkeleton} from './SystemState';
import {useEffect,useRef,useState} from 'react';
import {travelMetric} from '../lib/travelMetrics';
import {downloadText} from '../lib/flightCard';
import {hiddenTravelers,mergeTravelMoments,readTravelRecap,saveTravelRecap,type TravelMoment} from '../lib/travelRecap';
export type SharedTravelerData={id:string;alias:string;side:'left'|'right';position:'front'|'wing'|'rear';callsign:string;date:string;from:string;to:string;hex:string|null;observedAt:number|null;expires:number;status:string;progress:number|null;remainingKm:number|null;destinationTimeZone:string|null;arrivalEstimate:number|null;arrivalStatus:string|null;detailsCheckedAt:number|null;milestones:TravelMoment[];reactions:{kind:string;time:number}[];reactionsEnabled:boolean};
export function SharedTraveler({watch,capture}:{watch:(trip:SharedTravelerData)=>Promise<void>;capture?:()=>Promise<void>}){
 const [id]=useState(()=>new URLSearchParams(location.search).get('traveler')||new URLSearchParams(location.search).get('myTraveler')),[trip,setTrip]=useState<SharedTravelerData|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[compact,setCompact]=useState(false),[viewed,setViewed]=useState(false),[notify,setNotify]=useState(false),[weather,setWeather]=useState(''),[clock,setClock]=useState(Date.now()),[reason,setReason]=useState('privacy'),[hidden,setHidden]=useState(()=>!!id&&hiddenTravelers().includes(id)),[moments,setMoments]=useState<TravelMoment[]>(()=>id?readTravelRecap(id):[]);
 const [privateView]=useState(()=>new URLSearchParams(location.search).has('myTraveler'));
 const refresh=useRef<()=>Promise<SharedTravelerData|null>>(async()=>null),notifyRef=useRef(false),announced=useRef(new Set<string>());notifyRef.current=notify;
 useEffect(()=>{if(!id||hidden)return;const controller=new AbortController();let pending=false;
  const load=async()=>{if(pending)return null;pending=true;try{const r=await fetch((privateView?'/api/premium/travelers/':'/api/travelers/')+encodeURIComponent(id),{signal:controller.signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Shared trip unavailable.');setTrip(d);setClock(Date.now());setMoments(old=>{const rows=mergeTravelMoments(old,d.milestones||[]);saveTravelRecap(id,rows);return rows;});
   for(const m of d.milestones||[]){const key=m.kind+':'+m.time;if(!announced.current.has(key)){announced.current.add(key);if(notifyRef.current&&['arrival','landing'].includes(m.kind)&&Date.now()-m.time<120000&&'Notification' in window&&Notification.permission==='granted'){try{new Notification('Skyward arrival update',{body:m.label,tag:'skyward-arrival-'+id});}catch{setMessage('This browser could not show a notification. Arrival updates remain available here.');}}}}
   return d as SharedTravelerData;
  }catch(e){if(!controller.signal.aborted){setTrip(null);setMessage((e as Error).message);setCompact(false);}return null;}finally{pending=false;}};
  refresh.current=load;void load();const timer=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>{controller.abort();clearInterval(timer);};
 },[id,hidden,privateView]);
 useEffect(()=>{if(!trip?.to)return;const controller=new AbortController();const load=async()=>{try{const r=await fetch('/api/airport-weather?airport='+encodeURIComponent(trip.to),{signal:controller.signal});if(!r.ok)throw Error();const d=await r.json(),o=d.observation;if(!o||Date.now()-o.observedAt>90*60000||o.observedAt>Date.now()+5000)throw Error();setWeather(`${o.station}: ${o.raw} · observed ${new Date(o.observedAt).toLocaleTimeString()}`);}catch{if(!controller.signal.aborted)setWeather('Current destination weather unavailable.');}};void load();const timer=setInterval(()=>{if(!document.hidden)void load();},900000);return()=>{controller.abort();clearInterval(timer);};},[trip?.to]);
 async function interact(body:object){setBusy(true);try{const r=await fetch('/api/travelers/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'Interaction unavailable.');setMessage('action' in body&&body.action==='report'?'Report received for review. You can also hide this trip on this device.':'Reaction sent.');await refresh.current();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function moment(kind:'scenery'|'sunset'){setBusy(true);try{if(!capture)throw Error('Scene capture unavailable.');await capture();const next=mergeTravelMoments(moments,[{kind,label:kind==='sunset'?'User-marked sunset scene':'User-marked scenery scene',source:'simulated',time:Date.now()}]);setMoments(next);saveTravelRecap(id!,next);setMessage('Scene image downloaded and added to your recap.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!id)return null;
 if(hidden)return <section className="shared-traveler"><p>This trip is hidden on this device.</p><button onClick={()=>{try{localStorage.setItem('skyward.hidden-travelers.v1',JSON.stringify(hiddenTravelers().filter(k=>k!==id)));}catch{}setHidden(false);}}>Unhide trip</button><a href="/travelers/">Travel together</a></section>;
 if(compact&&trip)return <button className="shared-traveler compact" onClick={()=>setCompact(false)}>{trip.alias}’s window · simulated · Details</button>;
 return <section className="shared-traveler" aria-label="Shared traveler journey"><a href="/travelers/">← Travel together</a>{viewed&&trip&&<button aria-label="Minimize journey companion" onClick={()=>setCompact(true)}>Minimize</button>}<h2>{trip?`${trip.alias}’s journey`:'Shared journey'}</h2>{trip&&<><strong>{trip.from||'?'} → {trip.to||'?'}</strong><p>{trip.callsign} · {trip.date}</p><small>{trip.status}{trip.observedAt?' · '+new Date(trip.observedAt).toLocaleTimeString():''}</small>
 <section aria-label="Arrival companion"><h3>Arrival companion</h3>{trip.progress!==null&&trip.progress!==undefined?<><progress max="100" value={trip.progress}/><p>{trip.progress}% · {trip.remainingKm} km remaining<br/><small>Straight-line route estimate, not distance actually flown.</small></p></>:<p>Route progress unavailable until a matching position is received.</p>}<p>{trip.arrivalStatus?'Reported status: '+trip.arrivalStatus:'Arrival status not verified.'}<br/>{trip.arrivalEstimate?'Estimated arrival: '+new Date(trip.arrivalEstimate).toLocaleString():'No verified arrival estimate available.'}</p>{trip.destinationTimeZone&&<p>Destination time: {new Intl.DateTimeFormat(undefined,{timeZone:trip.destinationTimeZone,hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(clock)}</p>}<details><summary>Destination weather</summary><p>{weather||'Checking nearby station…'}</p></details><button onClick={async()=>{if(notify){setNotify(false);return;}if(!('Notification' in window)){setMessage('Browser notifications are unavailable.');return;}try{const permission=await Notification.requestPermission();setNotify(permission==='granted');if(permission!=='granted')setMessage('Notifications were not enabled.');}catch{setMessage('Notifications are unavailable in this browser.');}}}>{notify?'Disable arrival notifications':'Notify me of arrival'}</button><small>Notifications require this page to remain open and checking updates. Possible landings are labeled as observations, not confirmed arrivals.</small></section>
 <p>Explore the scenery from {trip.alias}’s chosen {trip.side} window position. This is a simulated view, not a live camera or an exact seat map. Presence onboard is self-reported.</p><button disabled={busy||trip.date!==new Date().toISOString().slice(0,10)} onClick={async()=>{setBusy(true);try{const current=await refresh.current();if(!current)throw Error('This shared journey is no longer available.');await watch(current);travelMetric('guest_watch');setViewed(true);setCompact(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Watch from {trip.alias}’s window</button>{!trip.hex&&<p>No aircraft is matched yet. On the trip’s UTC date, use Watch to look for a current observation.</p>}
 <section aria-label="Shared reactions"><h3>Send a little encouragement</h3><button disabled={busy||trip.reactionsEnabled===false} onClick={()=>void interact({action:'react',kind:'wave'})}>👋 Wave</button> <button disabled={busy||trip.reactionsEnabled===false} onClick={()=>void interact({action:'react',kind:'heart'})}>♥ Heart</button>{trip.reactionsEnabled===false&&<p>The traveler has turned reactions off.</p>}<p aria-live="polite">{(trip.reactions||[]).map((r,i)=><span key={i}>{r.kind==='wave'?'👋':'♥'} </span>)}</p></section>
 <details><summary>Journey milestones &amp; recap ({moments.length})</summary><p>Observed/reported events appear only when received. Gaps are not reconstructed.</p><ol>{moments.map((m,i)=><li key={i}>{m.label} · {m.source} · {new Date(m.time).toLocaleTimeString()}</li>)}</ol><button disabled={!viewed||busy} onClick={()=>void moment('scenery')}>Save scenery moment</button> <button disabled={!viewed||busy} onClick={()=>void moment('sunset')}>Save sunset moment</button><small>Scene captures are simulated scenery you mark yourself; images download to this device. Recap events stay in this tab’s session.</small><button disabled={!moments.length} onClick={()=>downloadText('skyward-journey-recap.json',JSON.stringify({flight:trip.callsign,date:trip.date,from:trip.from,to:trip.to,moments},null,2))}>Download recap</button></details>
 {!privateView&&<details><summary>Report or hide this trip</summary><label>Reason<select aria-label="Report reason" value={reason} onChange={e=>setReason(e.target.value)}><option value="privacy">Privacy concern</option><option value="impersonation">Impersonation</option><option value="inappropriate">Inappropriate content</option><option value="spam">Spam</option></select></label><button disabled={busy} onClick={()=>void interact({action:'report',reason})}>Report trip</button><button onClick={()=>{try{localStorage.setItem('skyward.hidden-travelers.v1',JSON.stringify([...new Set([...hiddenTravelers(),id])].slice(-100)));}catch{}setHidden(true);}}>Hide this trip on my device</button></details>}<small>Sharing expires {new Date(trip.expires).toLocaleString()}.</small></>}{!trip&&!message&&<LoadingSkeleton label="Loading shared journey…" rows={2}/>}{message&&<p role="status">{message}</p>}<a href="/?account=upgrade">Share your own journey with Premium →</a></section>;
}
