import type {FlightScene} from '../lib/watchDiscovery';
import {useRef,useState,useEffect} from 'react';
import type * as Cesium from 'cesium';
import {cameraSnapshot,encodeCamera,downloadGlobeImage} from '../lib/sharedCamera';
export function ShareView({airport,hex,facility,mode,getViewer,getFlightScene}:{getFlightScene:()=>FlightScene|null;airport:string;hex?:string;facility?:string;mode:string;getViewer:()=>Cesium.Viewer|null}) {
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
 const trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLElement>(null);
 const capture=()=>{const url=new URL(location.pathname,location.origin),q=new URLSearchParams({airport,mode});if(hex)q.set('aircraft',hex);else if(facility)q.set('facility',facility);const scene=getFlightScene();if(scene&&scene.hex===hex){q.set('scene','flight');q.set('view',scene.view);}const pose=cameraSnapshot(getViewer());if(mode==='3D'&&pose)q.set('camera',encodeCamera(pose));url.hash=q.toString();setLink(url.href);setMessage('');};
 const close=()=>{setOpen(false);trigger.current?.focus();};
 useEffect(()=>{if(!open)return;panel.current?.querySelector('input')?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopPropagation();setOpen(false);trigger.current?.focus();}};document.addEventListener('keydown',escape,true);return()=>document.removeEventListener('keydown',escape,true);},[open]);
 return <div className="share-view"><button ref={trigger} className="quiet-button" aria-expanded={open} onClick={()=>{capture();setOpen(!open);}}>Share view</button>{open&&<section ref={panel} className="share-panel" aria-label="Share current view" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close();}}}><h2>Open this view again</h2><input aria-label="Shareable view link" readOnly value={link} onFocus={e=>e.target.select()}/><p>Opens current observations and the captured 3D camera position. When shared from Flight view, it also restores that viewpoint and follows the latest position. It does not replay this moment. The recipient needs access to this host; localhost is local to their computer.</p><div><button className="quiet-button" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Link copied');}catch{setMessage('Select the link above and copy it manually.');}}}>Copy link</button><button className="quiet-button" onClick={capture}>Update camera link</button><button className="quiet-button" disabled={busy} onClick={async()=>{const v=getViewer();if(!v){setMessage('Map is still loading. Try again when it is visible.');return;}setBusy(true);try{await downloadGlobeImage(v,hex??airport);setMessage('Map image downloaded with source credits.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed. Try again.');}finally{setBusy(false);}}}>{busy?'Exporting…':'Save map image'}</button><button className="quiet-button" onClick={close}>Close share</button></div><p role="status">{message}</p></section>}</div>;
}
