import {useEffect,useState} from 'react';
import {AIRFRAMES,FUEL_PROFILES,type FlightPlan,type FlightState} from '../lib/flightSimulator';
import {copilotHelp,landingCue,lessonResult,practiceSuggestion,type HelpTarget,type FlightLog} from '../lib/simulatorTraining';
export function focusFlightControl(target:HelpTarget){
 const labels:Record<HelpTarget,string>={brakes:'Release brakes',throttle:'Throttle',flaps:'Flaps',trim:'Pitch trim',controls:'↑',gear:'Landing gear',pitch:'↑',bank:'←',fuel:'Fuel remaining'};
 const controls=document.querySelector('.pilot-controls');const el=Array.from(controls?.querySelectorAll<HTMLElement>('button,input,select')??[]).find(e=>(target==='brakes'&&['Release brakes','Apply brakes'].includes(e.getAttribute('aria-label')??''))||e.getAttribute('aria-label')===labels[target]||e.textContent?.startsWith(labels[target]))??(target==='fuel'?document.querySelector<HTMLElement>('[aria-label="Fuel remaining"]'):null);
 if(el){el.scrollIntoView({block:'center',behavior:'smooth'});el.focus({preventScroll:true});el.animate([{outline:'3px solid #ffd284'},{outline:'3px solid transparent'}],{duration:1800});}
}
export function SimulatorLearning({s,p,log,speak}:{s:FlightState;p:FlightPlan;log:FlightLog;speak:(text:string)=>void}){
 const [checked,setChecked]=useState<string[]>([]),[help,setHelp]=useState('');const cue=landingCue(s,p),finished=['landed','crashed'].includes(s.phase);
 const checks:[string,boolean,HelpTarget,string][]=[['Fuel',s.fuelKg>FUEL_PROFILES[p.aircraftType].capacity*.1,'fuel','Check fuel before starting. To change the load, choose another flight.'],['Parking brake',s.brakes,'brakes','Keep the brake applied while you prepare; release it when ready to roll.'],['Takeoff flaps',s.flaps===1,'flaps','Select Takeoff in the flap control.'],['Trim',Math.abs(s.trim)<2,'trim',p.difficulty==='easy'?'Easy mode starts with neutral trim.':'Set pitch trim near zero for departure.'],['Controls',checked.includes('Controls'),'controls','Move the yoke or hold the pitch and bank controls to check their response. Ground rotation stays locked below takeoff speed.']];
 return <section className="pilot-learning" aria-label="Flight coach"><h3>Flight coach</h3>{p.lesson&&p.lesson!=='free'&&<p role="status">{lessonResult(p,s,log)}</p>}
 {s.ground&&s.phase==='ready'&&<details open={p.lesson==='takeoff'||undefined}><summary>Preflight checklist · {checks.filter(([name,ok])=>ok&&checked.includes(name)).length}/5 checked</summary>{checks.map(([name,ok,target,text])=><button key={name} aria-pressed={checked.includes(name)&&ok} onClick={()=>{setChecked(old=>old.includes(name)?old:old.concat(name));setHelp(text);focusFlightControl(target);}}>{checked.includes(name)&&ok?'✓ ':''}{name} · {name==='Controls'?'verify':ok?'ready':'check'}</button>)}</details>}
 {!finished&&<button onClick={()=>{const answer=copilotHelp(s,p);setHelp(answer.text);speak(answer.text);focusFlightControl(answer.target);}}>Help me</button>}{help&&<p className="pilot-cue" role="status">{help}</p>}
 {!s.ground&&['approach','landing'].includes(s.phase)&&<div aria-label="Landing coach"><h4>Approach guidance</h4><label>Centreline <meter min={-150} max={150} low={-15} high={15} optimum={0} value={cue.cross}/>{Math.round(Math.abs(cue.cross))} m {cue.cross>0?'right':'left'}</label><label>Glide path <meter min={-500} max={500} low={-100} high={100} optimum={0} value={cue.heightError}/>{Math.round(Math.abs(cue.heightError))} ft {cue.heightError>0?'high':'low'}</label><p>Target {AIRFRAMES[p.aircraftType].approach} kt · {s.gearPosition>.98?'Gear locked':'Check gear'}</p>{cue.flare&&<p className="pilot-warning">Flare gently. Reduce power; avoid a steep pull.</p>}</div>}
 </section>;
}
export function SimulatorDebrief({log,p}:{log:FlightLog;p:FlightPlan}){
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false);const samples=log.samples,s=samples[Math.min(index,samples.length-1)];
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>{if(i>=samples.length-1){setPlaying(false);return i;}return i+1;}),150);return()=>clearInterval(timer);},[playing,samples.length]);
 if(!s)return null;const xs=samples.map(v=>((v.lon-samples[0].lon+540)%360)-180),ys=samples.map(v=>v.lat),xmin=Math.min(...xs),ymin=Math.min(...ys),dx=Math.max(.001,Math.max(...xs)-xmin),dy=Math.max(.001,Math.max(...ys)-ymin);const point=(i:number)=>`${10+(xs[i]-xmin)/dx*260},${150-(ys[i]-ymin)/dy*130}`;
 return <section className="pilot-debrief" aria-label="Flight debrief"><h3>Flight debrief</h3><p>{p.from} → {p.to} · {log.touchdown?`Touchdown score ${log.touchdown.score}/100 · ${Math.round(Math.abs(log.touchdown.rate))} ft/min`:'No touchdown recorded'}</p><svg viewBox="0 0 280 165" role="img" aria-label="Recorded flight route"><polyline points={samples.map((_,i)=>point(i)).join(' ')} fill="none" stroke="#b4f3dc" strokeWidth="2"/><circle cx={point(Math.min(index,samples.length-1)).split(',')[0]} cy={point(Math.min(index,samples.length-1)).split(',')[1]} r="5" fill="#ffd284"/></svg><label>Replay position<input aria-label="Replay position" type="range" min={0} max={samples.length-1} value={Math.min(index,samples.length-1)} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/></label><button onClick={()=>{if(index>=samples.length-1)setIndex(0);setPlaying(!playing);}}>{playing?'Pause replay':'Play replay'}</button><p>{Math.round(s.time)}s · {s.phase}<br/>{Math.round(s.altitude)} ft · {Math.round(s.speed)} kt · {Math.round(s.fuel)} kg fuel</p><svg viewBox="0 0 280 90" role="img" aria-label="Altitude history"><polyline points={samples.map((v,i)=>`${10+i/Math.max(1,samples.length-1)*260},${80-v.altitude/Math.max(100,log.maxAltitude)*70}`).join(' ')} fill="none" stroke="#b4f3dc" strokeWidth="2"/></svg>{s.warning&&<p>{s.warning}</p>}<details><summary>Coaching notes · {log.events.length}</summary><ul>{log.events.map((e,i)=><li key={i}>{Math.round(e.time)}s · {e.text}</li>)}</ul></details><p><strong>Practice next:</strong> {practiceSuggestion(log)}</p><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({plan:p,...log},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='skyward-flight-debrief.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download debrief</button><small>Replay is kept for this flight; download it before leaving.</small></section>;
}
