import {useEffect,useState} from 'react';
import {listAccountItems,getAccountItem,deleteAccountItem,type LibraryItem} from '../lib/accountLibrary';
import {LESSONS,type Lesson,type FlightLog} from '../lib/simulatorTraining';
import {SimulatorDebrief} from './SimulatorLearning';
interface SavedFlight {practiceReset?:boolean;from:string;to:string;lesson?:Lesson;lessonCompleted?:boolean;touchdownScore?:number;result:string;assisted:boolean;completedAt:number;hasReplay?:boolean;replay?:FlightLog;}
export function SimulatorHistory(){const [items,setItems]=useState<LibraryItem<SavedFlight>[]>([]),[selected,setSelected]=useState<SavedFlight|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;listAccountItems<SavedFlight>('missions').then(r=>{if(active)setItems(r.items);}).catch(()=>{if(active)setError('Saved training could not load. Reopen this page to retry.');});return()=>{active=false;};},[]);
 return <details className="sim-history"><summary>Saved training and replays · {items.length}</summary>{error&&<p role="status">{error}</p>}<ul>{Object.entries(LESSONS).filter(([id])=>id!=='free').map(([id,l])=>{const runs=items.filter(i=>i.value.lesson===id),best=runs.reduce((score,i)=>Math.max(score,i.value.touchdownScore??0),0);return <li key={id}>{l.name}: {runs.filter(i=>i.value.lessonCompleted).length} completed / {runs.length} attempts{best>0?` · best ${best}/100`:''}</li>;})}</ul>{items.map(item=><div key={item.key}><p>{item.value.from} → {item.value.to} · {item.value.practiceReset?'Landing practice':item.value.lesson?LESSONS[item.value.lesson]?.name:'Free flight'} · {item.value.result} · {item.value.assisted?'assisted':'manual'}<br/>{new Date(item.value.completedAt).toLocaleString()}</p><button disabled={busy||!item.value.hasReplay} onClick={async()=>{setBusy(true);try{const record=await getAccountItem<SavedFlight>('missions',item.key);setSelected(record.value);setError('');}catch{setError('Replay could not load. Try again.');}finally{setBusy(false);}}}>Open saved replay</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await deleteAccountItem('missions',item);setItems(old=>old.filter(i=>i.key!==item.key));setSelected(null);}catch{setError('Could not remove this saved result.');}finally{setBusy(false);}}}>Delete result</button></div>)}{selected?.replay&&<SimulatorDebrief key={selected.completedAt} log={selected.replay} p={selected}/>}</details>;
}
