import type {SpotterCameraMode} from './SpotterCamera';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {Aircraft,TrailPoint} from '../types';
import {spotterCandidates} from '../lib/spotter';
export function Spotter({airport,rows,histories,now,select,stop,paused,cameraMode,setCameraMode,userPaused,setUserPaused,hasRunway}:{cameraMode:SpotterCameraMode;setCameraMode:(m:SpotterCameraMode)=>void;userPaused:boolean;setUserPaused:(v:boolean)=>void;hasRunway:boolean;airport:string;rows:Aircraft[];histories:Map<string,TrailPoint[]>;now:number;select:(a:Aircraft)=>void;stop:()=>void;paused:boolean}){
 const [current,setCurrent]=useState(''),[skipped,setSkipped]=useState<string[]>([]);const missing=useRef(0);const options=useMemo(()=>spotterCandidates(rows,histories,airport,now),[rows,histories,airport,now]);const callbacks=useRef(select);callbacks.current=select;
 useEffect(()=>{if(paused||userPaused||document.hidden)return;const active=options.find(x=>x.aircraft.hex===current);if(active){missing.current=0;return;}if(current&&!missing.current){missing.current=now;return;}if(current&&now-missing.current<10000)return;const next=options.find(x=>!skipped.includes(x.aircraft.hex)&&x.aircraft.hex!==current);if(next){setCurrent(next.aircraft.hex);missing.current=0;callbacks.current(next.aircraft);}else if(current)setCurrent('');},[options,current,skipped,now,paused,userPaused]);
 const selected=rows.find(a=>a.hex===current);
 return <section className="spotter-panel" aria-label="Airport spotter"><strong>{airport} · Airport spotter</strong><p>{userPaused?'Spotter paused':paused?'Paused while tools are open':selected?`Following ${selected.callsign||selected.hex} · approach inferred`:'Waiting for a fresh, consistent approach trend…'}</p><label>Spotter camera<select aria-label="Spotter camera" value={cameraMode} onChange={e=>setCameraMode(e.target.value as SpotterCameraMode)}><option value="follow">Follow aircraft</option><option value="overhead">Overhead aircraft</option><option value="runway" disabled={!hasRunway}>Fixed runway viewpoint</option></select></label>{cameraMode==='runway'&&<small>Illustrative viewpoint beside the first mapped runway, not a confirmed arrival runway.</small>}<button onClick={()=>setUserPaused(!userPaused)}>{userPaused?'Resume spotter':'Pause spotter'}</button><small>{options.length} candidates · these are not confirmed arrivals. Switches after the approach ends or observations go stale.</small><div><button disabled={!current||paused||userPaused} onClick={()=>{setSkipped(s=>[...s,current].slice(-100));setCurrent('');missing.current=0;}}>Next aircraft</button><button onClick={()=>setSkipped([])}>Reset queue</button><button onClick={stop}>Stop spotter</button></div></section>;
}
