import {readAmbienceMix} from '../lib/audioMix';
import {useEffect,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import type {Aircraft} from '../types';
export function TowerAudio({viewer,observations,suspended}:{viewer:Cesium.Viewer|null;observations:Aircraft[];suspended:boolean}){
 const [enabled,setEnabled]=useState(false),[volume,setVolume]=useState(.3),[error,setError]=useState('');
 const context=useRef<AudioContext|null>(null),state=useRef({observations,suspended,volume});state.current={observations,suspended,volume};
 useEffect(()=>{if(!enabled||!viewer||viewer.isDestroyed())return;const ctx=context.current;if(!ctx)return;const C=window.Cesium;
 const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),samples=buffer.getChannelData(0);let smooth=0;for(let i=0;i<samples.length;i++){smooth=.96*smooth+.04*(Math.random()*2-1);samples[i]=smooth*3;}
 const voices=Array.from({length:3},()=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),pan=ctx.createStereoPanner();const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;noise.connect(gain);noise.start();oscillator.type='triangle';gain.gain.value=0;oscillator.connect(gain).connect(pan).connect(ctx.destination);oscillator.start();return{oscillator,noise,gain,pan};});
 const update=()=>{if(viewer.isDestroyed())return;const s=state.current;if(document.hidden||s.suspended){void ctx.suspend();return;}if(ctx.state==='suspended')void ctx.resume().catch(()=>setError('Use the audio button to resume sound.'));const origin=viewer.camera.positionWC;const rows=s.observations.filter(a=>a.targetKind==='aircraft').map(a=>{const entity=viewer.entities.getById(`aircraft-${a.hex}`),position=entity?.show&&entity.position?.getValue(viewer.clock.currentTime);return position?{a,position,distance:C.Cartesian3.distance(origin,position)}:null;}).filter(r=>r!==null&&r.distance>=1&&r.distance<8000).sort((a,b)=>a!.distance-b!.distance).slice(0,3);
 voices.forEach((v,i)=>{const row=rows[i];v.gain.gain.setTargetAtTime(row?s.volume*readAmbienceMix().engine*.12/(1+(row.distance/1200)**2):0,ctx.currentTime,.15);if(row){const direction=C.Cartesian3.normalize(C.Cartesian3.subtract(row.position,origin,new C.Cartesian3()),new C.Cartesian3());v.pan.pan.setTargetAtTime(Math.max(-1,Math.min(1,C.Cartesian3.dot(direction,viewer.camera.rightWC))),ctx.currentTime,.15);v.oscillator.frequency.setTargetAtTime(45+Math.min(300,row.a.groundSpeed??0)*.16,ctx.currentTime,.3);}});};
 const timer=window.setInterval(update,150);document.addEventListener('visibilitychange',update);update();return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',update);voices.forEach(v=>{v.noise.stop();v.noise.disconnect();v.oscillator.stop();v.oscillator.disconnect();v.gain.disconnect();v.pan.disconnect();});void ctx.close();if(context.current===ctx)context.current=null;};
 },[enabled,viewer]);
 const toggle=()=>{setError('');if(enabled){setEnabled(false);return;}try{context.current=new AudioContext();void context.current.resume().catch(()=>setError('Audio could not start. Try again.'));setEnabled(true);}catch{setError('Audio is unavailable in this browser.');}};
 return <div className="tower-audio"><button aria-pressed={enabled} onClick={toggle}>Tower audio {enabled?'on':'off'}</button>{enabled&&<label>Volume<input aria-label="Tower audio volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label>}<small>Synthesized engine sound · direction and distance follow the view.</small>{error&&<small role="status">{error}</small>}</div>;
}
