import {useMemo} from 'react';
import type {Aircraft} from '../types';
import {airlineNames} from '../lib/aircraft';
import {emptyFilters,filtersActive,type TrafficFilters as Filters} from '../lib/trafficFilters';
export function TrafficFilters({value,change,aircraft,airport}:{value:Filters;change:(v:Filters)=>void;aircraft:Aircraft[];airport:string}){
 const operators=useMemo(()=>[...new Set(aircraft.map(a=>a.callsign.slice(0,3)).filter(s=>/^[A-Z]{3}$/.test(s)))].sort(),[aircraft]);
 const prefixes=[...new Set([...operators,...(value.airline?[value.airline]:[])])].sort();
 return <details className="advanced-traffic"><summary>Flight filters{filtersActive(value)?' · active':''}</summary><label>Airline / callsign prefix<select aria-label="Airline filter" value={value.airline} onChange={e=>change({...value,airline:e.target.value})}><option value="">All operators</option>{prefixes.map(p=><option key={p} value={p}>{airlineNames[p]??p} · {p}</option>)}</select></label><label>Aircraft model<input aria-label="Aircraft model filter" placeholder="B738, Airbus, Boeing…" value={value.type} onChange={e=>change({...value,type:e.target.value})}/></label>{(['Altitude','Speed'] as const).map(k=><fieldset key={k}><legend>{k} · {k==='Altitude'?'ft':'kt'}</legend>{(['min','max'] as const).map(bound=>{const key=`${bound}${k}` as 'minAltitude'|'maxAltitude'|'minSpeed'|'maxSpeed';return <label key={key}>{bound==='min'?'From':'To'}<input aria-label={`${bound==='min'?'Minimum':'Maximum'} ${k.toLowerCase()}`} type="number" min={k==='Speed'?0:-2000} max={k==='Speed'?3000:100000} value={value[key]} onChange={e=>change({...value,[key]:e.target.value})}/></label>;})}</fieldset>)}<label>Observed direction near {airport}<select aria-label="Airport direction filter" value={value.direction} onChange={e=>change({...value,direction:e.target.value as Filters['direction']})}><option value="all">Any direction</option><option>Approaching</option><option>Moving away</option></select></label><small>Requires at least 3 recent fixes within 20 nm of {airport}. A direction trend is not a confirmed arrival or departure. Unknown values are excluded from active numeric filters.</small><button className="text-button" onClick={()=>change({...emptyFilters})}>Reset flight filters</button></details>;
}
